### ISSUE TITLE
Vertraging voor pakketverzending per product kunnen instellen

### ISSUE THREAD

**Issue by GuidoHub** [myparcelnl/magento#100]
Op dit moment kun je aangeven of er een vertraging is voor de verzending van een order, dit geldt dan voor alles. Zou mooi zijn als je dit per product zou kunnen aangeven en hier dan rekening mee wordt gehouden in de checkout.

**Comment by RichardPerdaan** [comment]
In versie [4.0.0-beta.1](https://github.com/myparcelnl/magento/releases/tag/4.0.0-beta.1) is de functionaliteit toegevoegd
