### ISSUE TITLE
Fit in Mailbox aan alle attribute sets toegevoegd

### ISSUE THREAD

**Issue by GuidoHub** [myparcelnl/magento#102]
Weet niet of dit de bedoeling was / is maar de attribute "Fit in Mailbox" wordt nu aan alle bestaande attribute sets toegevoegd. De optie wordt dus nu ook weergegeven op de product detail page.

**Comment by reindert-vetter** [comment]
Zie #110

**Comment by GuidoHub** [comment]
Persoonlijk heb ik hem liever niet toegevoegd aan mijn bestaande sets omdat deze dan ook naar voren komt in de backend bij het product. Waarom een attribute tonen bij een product als die daar niet van toepassing is. Ik heb juist meerdere sets gemaakt om de verschillende attributen te schikken;)

**Comment by GuidoHub** [comment]
zie @ #120 , geeft problemen wanneer je hem uit je set haalt.

**Comment by RichardPerdaan** [comment]
In versie [3.1.0](https://github.com/myparcelnl/magento/releases/tag/3.1.0) is dit probleem opgepakt.
