### ISSUE TITLE
Minicart heeft geen "Schat verzendkosten" meer

### ISSUE THREAD

**Issue by bezigeboefjes** [myparcelnl/magento#109]
Wanneer ik de 2.2 versie van de extensie installeer, dan krijg ik in mijn minicart geen schatting meer van de verzendkosten. Is dit bewust? Of is dit een bug?

![image](https://user-images.githubusercontent.com/20379631/31584811-61e56516-b1b6-11e7-902d-063b2c3da8c4.png)
(Links is zonder de extensie, rechts is met de extensie)

**Comment by bezigeboefjes** [comment]
Ik heb al gevonden dat dit de reden is:
https://github.com/myparcelnl/magento/commit/fd9ffc65fac994113c22b2fa0c4c4d4b331be9a2#diff-22c2ed0e5ad791dbc33257b82cd23aa0

Is dit tijdelijk? Of permanent? Vind het namelijk wel jammer dat de klant niet meteen verzendkosten kan berekenen (als zou in de berekening alleen de standaard verzendmethode meegenomen worden, zou ik het al acceptabel vinden).

**Comment by reindert-vetter** [comment]
Vervelend dat het niet werkt zoals je het graag had gezien. Dit gebeurt inderdaad door de plugin. We hebben hiervoor gekozen omdat je anders problemen krijgt. De plugin maakt naast de standaard verzendmethode, ook andere verzendmethodes aan. Als iemand kiest voor een van die verzendmethode, dan kan die niet geselecteerd worden in de checkout. De klant vult daar zijn adres is en op basis daarvan wordt er (opnieuw) berekend welke verzendopties de klant kan kiezen.
![image](https://user-images.githubusercontent.com/16726304/32038953-821cd1d8-ba2c-11e7-9ea1-6f4607457ccc.png)

**Comment by jeroencusters** [comment]
Ik liep hier zojuist ook tegenaan. Klanten worden nu gedwongen om helemaal naar afrekenen te gaan om de verzendkosten te zien. Ik vind het zelf altijd heel irritant als ik niet eenvoudig (een indicatie van) de verzendkosten kan zien in een webshop.
