### ISSUE TITLE
attribuut fit in mailbox automatisch op no

### ISSUE THREAD

**Issue by RichardPerdaan** [myparcelnl/magento#110]
Het attribuut fit in mailbox bij de update automatisch word getoond op productpagina's. 
![image](https://user-images.githubusercontent.com/11389731/31667291-4d19ded8-b34f-11e7-8f47-3cf9a9bc481d.png)

De 2 opties zouden beiden op No moeten staan. Wellicht handig voor de volgende update. 

@00043953

**Comment by bamboekeizer** [comment]
Hi Richard, yet it is really useful to have it disabled by default. I just upgraded to magento 2 (read fresh deployment and fresh myparcel module install), and it is indeed annoying to have to find out through github issues that I need to clear it. I

**Comment by RichardPerdaan** [comment]
In versie [3.1.0](https://github.com/myparcelnl/magento/releases/tag/3.1.0) is dit probleem opgepakt.
