### ISSUE TITLE
[ kritiek] foutief adres, geen huisnummer, geeft problemen bij aanmaken verzending

### ISSUE THREAD

**Issue by GuidoHub** [myparcelnl/magento#112]
Bij een van onze orders was een klant vergeten het huisnummer op te geven. Tijdens de batch actie "Print MyParcel labels" als concept kwam er hier een error op. Op basis hiervan is het adres aangepast. Wat blijkt nu is dat alle  orders die voor de order zat met het foutieve adres geen shipment record hebben in magento met alle gevolgen van dien.

Reproduce:

- Creeer meerdere orders waarvan 1 met foutief adres.
- Selecteer alle orders in sales->order grid
- Kies actie "Print MyParcel labels" - concept
- Men krijgt nu een foutmelding
- Labels zijn wel aangemaakt in MyParcel maar shipment record in Magento 2 is niet aanwezig voor alle orders die voor de order zaten waarop de foutmelding naar voren kwam maar order is wel om completed gezet.

**Comment by reindert-vetter** [comment]
Klopt het dat je de volgende melding krijgt? ```An error has occurred while validating the address: Hoofdweg. Check number and number suffix. View log file for more information.```

De volgende stappen worden uitgevoerd als je een label print:

1. Er wordt een magento-zending aangemaakt
2. Er word een myparcel-zending aangemaakt in MyParcel
3. De myparcel-zending wordt gekoppeld aan de Magento zending

Magento past zelf de status aan als er een magento-zending is aangemaakt. Ik moet dus voordat er een zending wordt aangemaakt al controleren of het adres wel klopt. Ik zal dit uitzoeken en ik hoop dat het me lukt om dit deze week op te lossen.

**Comment by reindert-vetter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [foutief adres, geen huisnummer, geeft problemen bij aanmaken verzending](https://trello.com/c/3Q1sMqvT/35-foutief-adres-geen-huisnummer-geeft-problemen-bij-aanmaken-verzending)

**Comment by GuidoHub** [comment]
Dat is inderdaad de melding die je krijgt.

Vandaag was het de eerste in de batch waarbij er geen huisnummer was opgegeven. Gelukkig is de magento zending nu wel aangemaakt, dit was de vorige keer niet het geval waardoor ook de statussen in order-gird niet meer bijgewerkt worden.

In de shipment staat wel dat er een concept label is aangemaakt maar deze is er niet, komt ook niet terug in jullie backend. Ik heb nu per order de label opnieuw aangemaakt en gelukkig wordt er geen nieuwe magento zending aangemaakt maar alleen het label.

Het zou mooi zijn als jullie dit aan de voorkant ook al controleren. Daar strippen jullie het adres al om het huisnummer te krijgen om vervolgens de plugin te laden. Zou mooi zijn als er nog geen standaard shipment zou zijn zodat je ook niet door kunt gaan met het afronden van de bestelling.

**Comment by reindert-vetter** [comment]
Ik heb nu een nieuwe versie gemaakt. Als je die nieuwe versie installeert, dan zal je een melding zien in je order overzicht als het adres niet volledig is:
https://github.com/myparcelnl/magento/releases/tag/2.3.0-beta.4

Zou je deze versie willen testen. Als mijn collega deze versie ook heeft getest, kunnen we die versie als stabiel mankeren.

**Comment by GuidoHub** [comment]
Ik heb het niet kunnen testen. Zodra ik de bestelling probeer af te ronden krijg ik 2 errors:

- POST http://xxxx/rest/xxxx/V1/guest-carts/3bd3e6bfeb1db50a65af063789e147bc/payment-information 500 (Internal Server Error)

Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.process (error-processor.min.js:1)
    at Object.<anonymous> (place-order.min.js:1)
    at fire (6e244ce5661831bc34d6a58b46c118eb.min.js:528)
    at Object.fireWith [as rejectWith] (6e244ce5661831bc34d6a58b46c118eb.min.js:534)
    at done (6e244ce5661831bc34d6a58b46c118eb.min.js:944)
    at XMLHttpRequest.callback (6e244ce5661831bc34d6a58b46c118eb.min.js:971)

**Het ergste van allemaal is dat de bestelling niet word afgerond maar het product wel wordt afgeboekt in de backend.** Zodra je de pagina refreshed kom je op de pagina checkout/cart met de melding dat het product niet op voorraad is (in mijn geval had ik er 1 op voorraad)

Getest met Onepagecheckout van MagePlaza en betaling Multisafepay. Zodra de extensie is uitgeschakeld kan ik zonder problemen de bestelling afronden.

**Comment by GuidoHub** [comment]
Blijkbaar moet de SDK ook geupdate worden. Misschien handig om deze in de package op te nemen.

<b>Fatal error</b>:  Uncaught Error: Call to undefined method MyParcelNL\Sdk\src\Model\Repository\MyParcelConsignmentRepository::isCorrectAddress() in 

Waar ik me wel ontzetten zorgen om maak is het afboeken van de voorraad. Het kan niet zo zijn dat als ik een error krijgt toch de voorraad wordt bijgewerkt. Ik zou toch graag zien dat jullie hier ook nog even naar kijken.

**Comment by GuidoHub** [comment]
@reindert-vetter , ik heb jullie nog een adres gestuurd waarbij het aanmaken van de labels alsnog fout ging. Het ging om een adres met een huisnummer toevoeging van 5 karakters.

**Comment by reindert-vetter** [comment]
We gaan niet meer dan 4 karakters ondersteunen, maar we gaan (waarschijnlijk in januari) het volgende oppakken:
https://github.com/myparcelnl/magento/issues/39
