### ISSUE TITLE
MyParcel opties in backend

### ISSUE THREAD

**Issue by reindert-vetter** [myparcelnl/magento#118]
@Bobstores

Kan geen myparcel opties kiezen in de admin in combinatie met table rates. Dit lukt wel in combinatie met flat rate.

**Comment by reindert-vetter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [MyParcel opties in backend](https://trello.com/c/afQ5gOn8/44-myparcel-opties-in-backend)

**Comment by erik921** [comment]
+1 
Wij hebben dit probleem ook.
Op het moment dat table rates geselecteerd is zijn alle extra opties te zien.
Deze zijn via de backend niet uit te zetten, omdat de opties zelfs bij uit te zien blijven.

Het volgende is al geprobeerd:
- Opties op No zetten
- Reindex
- deploy static-content
- Flash flush & clean

**Comment by reindert-vetter** [comment]
@erik921 
Bedankt voor het melden van het probleem. Zou je willen controleren of voor jou werkt?
https://github.com/myparcelnl/magento/releases/tag/2.3.0-beta.4

Als je composer gebruikt, kan je deze versie binnenhalen met het volgende:
```composer require myparcelnl/magento "~2.3.0@beta"```

**Comment by erik921** [comment]
Hello,

Sorry voor de late reactie.
Ik ga er vanavond naar kijken!

**Comment by RichardPerdaan** [comment]
Beste @erik921,
Is het gelukt om via composer de juiste versie binnen te halen?

**Comment by erik921** [comment]
Hallo @RichardPerdaan 

Ja dat is gelukt.
Als ik nu Table Rate selecteer krijg ik helemaal geen extra opties meer.

**Comment by erik921** [comment]
Oh nee wacht iets te snel geweest.
De plugin werkt grafisch nog niet optimaal met onze checkout maar daar zal ik de developers van de checkout wel naar laten kijken.

![image](https://user-images.githubusercontent.com/5640785/32751410-240f6d6e-c8c6-11e7-9d2f-af002601b394.png)
Is het normaal dat onder bezorgopties altijd het adres van de klant blijft staan ook als de klant een ophaallocatie selecteerd? Het lijkt mij persoonlijk namelijk logischer dat hier dan de naam van de afhaallocatie komt te staan.

**Comment by erik921** [comment]
Nog een probleem dat ik tegen kwam.
Als ik myparcel selecteer en daarna een optie die door een andere plugin is gemaakt worden ze beide geselecteerd.

![image](https://user-images.githubusercontent.com/5640785/32809204-4b53c818-c996-11e7-8a1b-9d93cc096b0a.png)

Myparcel laat dan niet meer de optie los. (zie selectie)

**Comment by bezigeboefjes** [comment]
> Als ik myparcel selecteer en daarna een optie die door een andere plugin is gemaakt worden ze beide geselecteerd.

Deze heb ik ook geconstateerd bij ons. 

Ik ben eerlijk gezegd niet zo kapot van de huidige oplossing, ik zou liever zien dat gewoon de "normale" radio-buttons gebruikt werden.

**Comment by erik921** [comment]
Ik ben het hier mee eens.
De oplossing om radio buttons te vervangen is goed bedacht alleen zie ik het niet snel gebeuren ivm te veel custom werk.

**Comment by RichardPerdaan** [comment]
De problemen die in de issue zijn besproken zijn opgelost vanaf versie [2.4.0](https://github.com/myparcelnl/magento/releases/tag/2.4.0) van de MyParcel Magento 2 plugin. 
Mochten er nog problemen zijn dan kan je de issue gewoon weer openen.
