### ISSUE TITLE
Error in system.log

### ISSUE THREAD

**Issue by GuidoHub** [myparcelnl/magento#120]
Below errors are coming back in system.log

Update script has been run several times but no difference.

main.CRITICAL: Can't get settings with path:myparcelnl_magento_checkout/ [] []
main.CRITICAL: Can't get field from database (myparcel_fit_in_mailbox FROM catalog_product). Run update scrip again. [] []

**Comment by GuidoHub** [comment]
ISSUE: main.CRITICAL: Can't get field from database (myparcel_fit_in_mailbox FROM catalog_product). Run update scrip again. [] []

\vendor\myparcelnl\magento\Model\Sales\Repository\PackageRepository.php
line 158

if (!key_exists('myparcel_fit_in_mailbox', $attributesHolder)) {
            $this->_logger->critical('Can\'t get field from database (myparcel_fit_in_mailbox FROM catalog_product). Run update scrip again.');
            return null;
        }

Leuk dat jullie hier controleren of het attribute aanwezig is maar ik heb deze uit mijn set gehaald omdat het niet van toepassing is voor mijn producten.

**Comment by GuidoHub** [comment]
ISSUE: main.CRITICAL: Can't get settings with path:myparcelnl_magento_checkout/ [] []

\htdocs\vendor\myparcelnl\magento\Helper\Checkout.php
line 147

$this->setTmpScope('');

Dit zorgt er voor dat line 257:            $this->_logger->critical('Can\'t get settings with path-tmp:' . self::XML_PATH_CHECKOUT . $tmp_scope); wordt getriggerd. Misschien het controleren van de system.log meenemen in jullie test procedure.

**Comment by RichardPerdaan** [comment]
In versie 2.3.0-beta.5 is het bovenstaande opgelost. De volgende 2 errors zouden niet meer zichtbaar moeten zijn:
* main.CRITICAL: Can't get settings with path:myparcelnl_magento_checkout/ [] []
* main.CRITICAL: Can't get field from database (myparcel_fit_in_mailbox FROM catalog_product). Run update scrip again. [] []

@GuidoHub Zou je willen controleren of dit het probleem oplost?

**Comment by RichardPerdaan** [comment]
Voor nu sluit ik deze issue, mocht de error nog steeds aanwezig zijn dan hoor ik dat graag van je.

**Comment by phagens** [comment]
Fit in mailbox is zinloos attribuut. Als er een item is van 1 cm dik staat dit attribuut aan maar als een klant er 4 bestelt is het te dik en past het dus niet in een mailbox. Om brievenbuspakjes te kunnen selecteren heb je de dikte van elk item nodig en moet die gesommeerd worden om te bepalen of het als briefpost kan. Kan als brievenbuspakje als totaal gewich <3000 gr en totale dikte < 3.2 cm

**Comment by RichardPerdaan** [comment]
Dit probleem is besproken per mail en er is een issue aangemaakt (#132).
