### ISSUE TITLE
[security] XSS (Cross-site-scripting) in bezorgopties

### ISSUE THREAD

**Issue by erik921** [myparcelnl/magento#124]
Het lijkt er op dat javascript uitgevoerd kan worden door middel bij "staat en huisnummer" javascript in te voeren.

![afbeelding](https://user-images.githubusercontent.com/5640785/33580624-329933cc-d94e-11e7-8da9-c0a6ba3278af.png)

**Comment by reindert-vetter** [comment]
Hallo Erik,

Bedankt voor het melden. Ik heb een pull-request aangemaakt. Zou je willen controleren of dit de oplossing is voor jou?

Vanmiddag zal ik dit in master voegen.

**Comment by erik921** [comment]
De oplossing lijkt mij te werken.
Ik moet het zelf even uit me cache halen dus heb het niet echt kunnen testen nog.
