### ISSUE TITLE
[Feature - Request] Gratis verzenden boven X bedrag

### ISSUE THREAD

**Issue by erik921** [myparcelnl/magento#126]
Ik heb een cart rule staan voor gratis verzenden bij een x bedrag echter werkt dit niet met myparcel.
Het bedrag blijft gewoon staan op de normale verzendkosten.

Het zou fijn zijn als er een optie zou zijn waarbij er een bedrag in te voeren is van de total_cart_price (-shipping) en als het bedrag hier dan boven komt,, dat het verzenden dan automatisch gratis is voor klanten.

**Comment by RichardPerdaan** [comment]
Beste @erik921,

Zou je een mail naar support@myparcel.nl willen sturen. 
Ik zal dan contact met jou opnemen en zou dan graag met jou mee willen kijken via een remote sessie.

**Comment by erik921** [comment]
@RichardPerdaan 
Ik heb net de email verstuurd.
