### ISSUE TITLE
Order grid is not updated with shipment information

### ISSUE THREAD

**Issue by GuidoHub** [myparcelnl/magento#127]
Order grid is not updated anymore because of wrong table name in file \vendor\myparcelnl\magento\Model\Sales\MagentoCollection.php

In function  getTracksCollectionByOrderId you don't take into account that some installations use tabel prefix.

**Comment by reindert-vetter** [comment]
Can you check if this is the solution?
https://github.com/myparcelnl/magento/pull/128

**Comment by RichardPerdaan** [comment]
Hi @GuidoHub,
Is this problem still there?
If the problem no longer occurs, would you like to close the issue?
