### ISSUE TITLE
Toevoeging huisnummer komt (soms) niet mee.

### ISSUE THREAD

**Issue by Chris707** [myparcelnl/magento#129]
Het magento systeem pakt geen extra nummers bij het huisnummer, het gaat ook te vaak fout met huisnummer met een A,B of C toevoeging. Ik neem aan dat jullie hiermee bekend zijn. Is hier wat aan te doen?

**Comment by RichardPerdaan** [comment]
Case: 00254384

**Comment by RichardPerdaan** [comment]
In version [2.4.0](https://github.com/myparcelnl/magento/releases/tag/2.4.0) is this problem solved and with [v1.4.1](https://github.com/myparcelnl/sdk/releases/tag/v1.4.1) of the SDK.
