### ISSUE TITLE
Exclude countries

### ISSUE THREAD

**Issue by koopjesboom** [myparcelnl/magento#138]
Best,

We have several options for shipping in Magento 2 like DHL and so on for different countries.
In this case we don't want to use PostNL for every country and need to exclude the ones we don't want to use.

Is it possible to exclude country's from myparcel/PostNL extension?
![country selection](https://user-images.githubusercontent.com/15247780/34608470-c05b66fc-f218-11e7-8ea6-fb67b8cb9bc3.png)

Best regards Bram

**Comment by RichardPerdaan** [comment]
Thank you for your comment. You can solve this issue by using table rates.

For more information about table rates, you can see the following website:
http://docs.magento.com/m2/ce/user_guide/shipping/shipping-table-rate.html

There is also a website (https://www.elgentos.nl/tablerates/) you can use to make a csv file, so you can upload this inside your Magento environment.

When you need help, you can always contact us by phone (0233030315).
