### ISSUE TITLE
Fout in berekening totaalbedrag

### ISSUE THREAD

**Issue by Kroellie** [myparcelnl/magento#139]
Hi,

In onze development shop valt me op als ik bezorging in de avond kies, met "niet bij buren" op ja, en "handtekening" op ja, dat dan het totaalbedrag van verzending op 11,57 (incl BTW) komt. Dit bedrag is opgebouwd als volgt:

4,95 standaard verzending
1,25 additional fee avond levering
0,00 niet bij buren (inclusief bij avondlevering)
0,42 handtekening
======
6,62 totaal

verschil = 4,95 EUR.

**Comment by RichardPerdaan** [comment]
Hi @Kroellie,
Thank you commented you issue. Today I made a new version of plugin, I would like to recommend to install the new version (2.3.3-beta.1).

What has changed can be found in this (#149 ) pull request.
