### ISSUE TITLE
Magento Swagger / REST API is broken

### ISSUE THREAD

**Issue by Kroellie** [myparcelnl/magento#141]
https://webshop_url/nl/rest/all/schema?services=all

Error message:
Class "array" does not exist. Please note that namespace must be specified.
....
Magento\Webapi\Model\Config\ClassReflector->reflectClassMethods('MyParcelNL\\Mage...', Array)
....

**Comment by Kroellie** [comment]
https://github.com/magento/magento2/issues/2417 

??

**Comment by RichardPerdaan** [comment]
Dear @Kroellie,

We have also reproduce this issue and unfortunately we have not been able to solve it.
It is unclear when we will solve this issue, I will contact you when we start with this issue.

**Comment by GuidoHub** [comment]
Hello Richard,

You can find the problem in file \vendor\myparcelnl\magento\Api\DeliverySettingsInterface.php on line 27 you have set @return array All Settings but array is not a valid type. Needs to be changed to the right type. 

More information about this can be found here: http://devdocs.magento.com/guides/v2.0/extension-dev-guide/service-contracts/service-to-web-service.html

**Comment by Kroellie** [comment]
#153

**Comment by reindert-vetter** [comment]
Thank you for your contribution! It is already in master. My colleague will make a new release for this.

**Comment by reindert-vetter** [comment]
Fixed in version 2.3.3-beta.2:
https://github.com/myparcelnl/magento/releases
