### ISSUE TITLE
Send return label with 2 orders

### ISSUE THREAD

**Issue by RichardPerdaan** [myparcelnl/magento#144]
Als er 2 zendingen zijn van 1 bestelling en je klikt in magento 2 op send return label dan gebeurt er niks. (Hij zegt wel dat het verstuurd is) maar er wordt geen label gemaakt in jullie backend en ook geen mail verstuurd. Als er maar 1 zending geweest is werkt het wel goed.

**Comment by reindert-vetter** [comment]
Dit is opgelost in de SDK v1.3.4. Gebruik dus `composer update myparcelnl/sdk`, en controleer  in vendor/myparcenl/sdk/composer.json op deze versie.
