### ISSUE TITLE
Add HS code to shipment / order

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/magento#146]
Add the option to add the HS code to a shipment / order (world shipments)

**Comment by TimBlom** [comment]
Case 00301282

**Comment by soedesh** [comment]
Export lukt niet met magento 2.2 en plgn 2.5.2. Klant vermoedt dat dit te maken heeft met de douane formulieren. Kan geen HS code invoeren (Case 566611)

**Comment by RichardPerdaan** [comment]
Feature implemented in version [3.2.0-beta.1](https://github.com/myparcelnl/magento/releases/tag/3.2.0-beta.1)
