### ISSUE TITLE
Undefined index: price_comment in View.php on line 79

### ISSUE THREAD

**Issue by gerben86** [myparcelnl/magento#147]
Some zie ik in de logging deze error voorbijkomen:
`[2018-02-18 11:19:33] main.CRITICAL: Notice: Undefined index: price_comment in /..../webroot/vendor/myparcelnl/magento/Block/Sales/View.php on line 79 [] []`
Het lijkt erop dat er op die momenten ook geen shipping options in de Checkout getoond worden.

Waar kan dit aan liggen en hoe zou ik het kunnen oplossen?

Ik maak gebruik van Magento 2.1.10 en de MyParcel extensie versie 2.3.2.

Alvast bedankt!

**Comment by RichardPerdaan** [comment]
Beste @gerben86,

Dank je wel voor het plaatsen van de issue.
Deze error komt vanuit de order view en heeft niks te maken met de checkout, hierdoor kan ik je geruststellen dat jouw klant gewoon de order kan plaatsen. Waar het mis gaat met het tonen van de gewenste verzendoptie, is in de admin.

Via de error is te zien dat je de order op `[2018-02-18 11:19:33]` heb geopend, vandaar dat er in de error deze tijd te zien is.

Is deze error vaker voorgekomen of is het bij één order gebleven?
Als deze error vaker voorkomt dan is het mogelijk om een log in te bouwen zodat we kunnen zien waneer het probleem zich precies voordoet, met welke order. Zodat we verder kunnen onderzoeken waarom het bij deze order verkeerd gaat.

Graag zou ik contact met jou opnemen via de mail, zou je daarom een mail willen sturen naar support@myparcel.nl.

**Comment by gerben86** [comment]
Hallo Richard,

Bedankt voor je reactie!
Zou dit de oorzaak kunnen zijn dat ik niet zie dat een klant voor afhalen op PostNL-locatie heeft gekozen of voor bezorging thuis?

Deze melding komt vaker voor:
`[2018-02-28 09:39:16] main.CRITICAL: Notice: Undefined index: price_comment in /var/hpwsites/u_ruiten/website/html/webroot/vendor/myparcelnl/magento/Block/Sales/View.php on line 79 [] []
[2018-02-28 13:42:08] main.CRITICAL: Notice: Undefined index: price_comment in /var/hpwsites/u_ruiten/website/html/webroot/vendor/myparcelnl/magento/Block/Sales/View.php on line 79 [] []
[2018-03-03 11:35:15] main.CRITICAL: Notice: Undefined index: price_comment in /var/hpwsites/u_ruiten/website/html/webroot/vendor/myparcelnl/magento/Block/Sales/View.php on line 79 [] []
[2018-03-03 11:35:42] main.CRITICAL: Notice: Undefined index: price_comment in /var/hpwsites/u_ruiten/website/html/webroot/vendor/myparcelnl/magento/Block/Sales/View.php on line 79 [] []
[2018-03-03 11:36:08] main.CRITICAL: Notice: Undefined index: price_comment in /var/hpwsites/u_ruiten/website/html/webroot/vendor/myparcelnl/magento/Block/Sales/View.php on line 79 [] []
`

**Comment by gerben86** [comment]
@RichardPerdaan 
Hebben jullie hier al naar kunnen kijken?
Op het moment dat ik nu op een order klik in het bestellingen scherm komt deze error al te voorschijn, dus ik kan geen order-details meer zien...

`1 exception(s):
Exception #0 (Exception): Notice: Undefined index: price_comment in .../vendor/myparcelnl/magento/Block/Sales/View.php on line 79

Exception #0 (Exception): Notice: Undefined index: price_comment in .../vendor/myparcelnl/magento/Block/Sales/View.php on line 79
#0 .../vendor/myparcelnl/magento/Block/Sales/View.php(79): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/var/site/u...', 79, Array)
#1 .../vendor/myparcelnl/magento/view/adminhtml/templates/order_view.phtml(38): MyParcelNL\Magento\Block\Sales\View->getCheckoutOptionsHtml()
#2 .../vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/site/u...')
#3 .../vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(MyParcelNL\Magento\Block\Sales\View), '/var/site/u...', Array)
#4 .../vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/var/site/u...')
#5 .../vendor/magento/module-backend/Block/Template.php(124): Magento\Framework\View\Element\Template->_toHtml()
#6 .../vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Template->_toHtml()
#7 .../vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#8 .../vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('order_shipping_...')
#9 .../generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('order_shipping_...')
#10 ./vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('order_shipping_...')
#11 ./generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('order_shipping_...', true)
#12 ./vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement('order_shipping_...', true)
#13 ./vendor/magento/module-sales/view/adminhtml/templates/order/view/tab/info.phtml(39): Magento\Framework\View\Element\AbstractBlock->getChildHtml('order_shipping_...')
#14 ./vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/site/u...')
#15 ./vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Sales\Block\Adminhtml\Order\View\Tab\Info), '/var/site/u...', Array)
#16 ./vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/var/site/u...')
#17 ./vendor/magento/module-backend/Block/Template.php(124): Magento\Framework\View\Element\Template->_toHtml()
#18 ./vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Template->_toHtml()`

**Comment by reindert-vetter** [comment]
Beste @gerben86,
Zou je het volgende willen vervangen:
/vendor/myparcelnl/magento/Block/Sales/View.php:79
`if($data['time'][0]['price_comment'] != 'standard')`

Vervangen met:
`if(isset($data['time'][0]['price_comment']) && $data['time'][0]['price_comment'] != 'standard')`

**Comment by RichardPerdaan** [comment]
Beste @gerben86,

Ik zie dat je al een mail had gestuurd, ik zal deze nu behandelen.

**Comment by gerben86** [comment]
@reindert-vetter ; @RichardPerdaan : Bedankt! Dit blijkt te oplossing te zijn voor deze bug!
