### ISSUE TITLE
recipient.street Must be at most 40 characters long

### ISSUE THREAD

**Issue by magefan** [myparcelnl/magento#148]
The myparcelnl is not working for our client in some orders. The reason it too long street address entered by the customer. 

> Error backtrace
> URL: https://DOMAIN.COM/ADMIN/myparcelnl/order/CreateAndPrintMyParcelTrack/key/4602a731190df55e731d4979eb734252754d29513fa4b89b0a1de6d98cd12608/?selected_ids=8431&mypa_request_type=download&mypa_package_type=default&mypa_paper_size=A4&mypa_positions%5B%5D=2
> 
> Time: 2018-02-21 17:12:45 GMT
> Error:
> Error in MyParcel API request: 0 - data.shipments[0].recipient.street Must be at most 40 characters long - Failed validation against JSON-SCHEMA shipment/post_shipments_request.json Url: https://api.myparcel.nl/shipments Request: {"data":{"shipments":[{"recipient":{"cc":"BE","person":"xxx xxx","postal_code":"xxx","city":"xxxx","email":"xxxxx","phone":"xxxxx","street":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"},"options":{"package_type":1,"label_description":"xxxxx"},"carrier":1,"reference_identifier":"xxxxx"}]}}
> 
> Trace:
> #0 /vendor/myparcelnl/sdk/src/Helper/MyParcelCollection.php(234): MyParcelNL\Sdk\src\Model\MyParcelRequest->sendRequest()
> #1 /vendor/myparcelnl/magento/Model/Sales/MagentoOrderCollection.php(182): MyParcelNL\Sdk\src\Helper\MyParcelCollection->createConcepts()
> #2 /vendor/myparcelnl/magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack.php(114): MyParcelNL\Magento\Model\Sales\MagentoOrderCollection->createMyParcelConcepts()
> #3 /vendor/myparcelnl/magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack.php(59): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack->massAction()
> #4 /vendor/magento/framework/App/Action/Action.php(107): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack->execute()
> #5 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
> #6 /vendor/magento/framework/Interception/Interceptor.php(138): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->___callParent('dispatch', Array)
> #7 /vendor/magento/framework/Interception/Interceptor.php(153): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
> #8 /generated/code/MyParcelNL/Magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack/Interceptor.php(26): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->___callPlugins('dispatch', Array, Array)
> #9 /vendor/magento/framework/App/FrontController.php(55): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
> #10 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
> #11 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
> #12 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
> #13 /generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
> #14 /vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
> #15 /generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
> #16 /vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
> #17 /pub/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
> #18 {main}

We have created a quick dirty fix in the file
Helper/MyParcelCollection.php

and have changed the function 
private function apiEncode($consignments)\
from
```
    private function apiEncode($consignments)
    {
        $data = [];

        foreach ($consignments as $consignment) {
            $data['data']['shipments'][] = $consignment->apiEncode();
        }

        return json_encode($data);
    }
```
to
```
    private function apiEncode($consignments)
    {
        $data = [];

        foreach ($consignments as $consignment) {
            $encode = $consignment->apiEncode();
            if (isset($encode['recipient'])) {
                if (isset($encode['recipient']['street'])) {
                    $len = mb_strlen($encode['recipient']['street']);
                    if ($len > 40) {
                        $encode['recipient']['street'] = mb_substr($encode['recipient']['street'], 0, 37) . '...';
                    }
                }
            }
            $data['data']['shipments'][] = $encode;

        }

        return json_encode($data);
    }

```

But maybe you have better solution for this.
Also, could you please include fix for this issue in next release?

**Comment by reindert-vetter** [comment]
Hello magefan,

Sorry it does not work well for your customer. Is this especially wrong with foreign addresses? Do you have a sample address for me?

This problem is known and we can solve this by also using the street_additional_info field. I will program this so that the address is divided over street and street_additional_info. 

I'll keep you informed.

**Comment by magefan** [comment]
@reindert-vetter it can be addressed with any country. User can just enter a long address, or just put the city name in the street field as the addition. The user is user :-(

**Comment by reindert-vetter** [comment]
The new release 1.3.7 in the SDK (code that the plugin uses) now supports this. Just run `composer update myparcelnl/sdk` to get the latest version.

https://github.com/myparcelnl/sdk/releases/tag/v1.3.7
