### ISSUE TITLE
Carrier Title oneigenlijk misbruikt

### ISSUE THREAD

**Issue by Kroellie** [myparcelnl/magento#152]
In alle zichtbare subtotaal opsommingen in de frontend, backend, en email communicatie voegt Magento zelf standaard de Carrier Title en Method Title samen (vendor/magento/module-quote/Model/Quote/Address/Total/Shipping.php:174). In combinatie met de herschrijving door de MyParcel plugin komt dit tot vreemde resultaten:

Ik heb zelf de table rate als basis verzendmethode met 'PostNL' als carrier title en 'Bezorging' als method title, dit gaat redelijk goed in 80% van de gevallen, en wordt samengevoegd als:

"PostNL - Bezorging"

Nu na wat opties te wijzigen in de MyParcel module:

Poging 1
"signature_only_recip - Niet bij de buren bezorgen + handtekening voor ontvangst"

Poging 2
"only_recipient - Niet bij de buren bezorgen"

Poging 3
"pickup_express - Ophalen bij een PostNL locatie (extra vroeg ophalen)"

Ik zou zelf het liefst niet de carrier title gebruiken, zeker omdat je de delivery_options kolom hebt toegevoegd voor de parameters. En dus gewoon netjes 1 Carrier variabele in MyParcel checkout settings plaatsen, en al naar gelang de gekozen opties de Methode veranderen.

**Comment by RichardPerdaan** [comment]
In versie [4.0.0-beta.1](https://github.com/myparcelnl/magento/releases/tag/4.0.0-beta.1) is de functionaliteit toegevoegd
