### ISSUE TITLE
Labels kunnen niet worden gedownload in Magento 2.2.3

### ISSUE THREAD

**Issue by gerben86** [myparcelnl/magento#157]
Magento 2.2.3
Labels worden na het aanmaken van de bestelling (Print MyParcel Labels) niet ter download aangeboden in de Magento admin.
Opnieuw downloaden via "Bestellingen-Verzendingen" in de admin werkt helaas ook niet.
Ook zie ik ze niet op de server staan (als ze daar al geplaatst worden).

Dit betekend dat ik dan op de MyParcel backend moet inloggen om ze daarna handmatig te selecteren en te downloaden.

Wat is hier een betere workaround voor?

**Comment by RichardPerdaan** [comment]
Beste @gerben86,

Dank je wel voor het doorgegeven van het probleem. Het is mij opgevallen dat het printen van één label wel goed gaat. Het gaat verkeerd als je meerdere label tegelijk probeert aan te maken. Wanneer ik de oplossing heb, zal ik het op deze pagina noteren.

**Comment by Kroellie** [comment]
@RichardPerdaan Same here...

**Comment by gerben86** [comment]
@RichardPerdaan : Is er al een mogelijke oplossing bekend?

**Comment by RichardPerdaan** [comment]
Beste @gerben86 en @Kroellie,

Het probleem omtrent het kunnen printen van meerdere label tegelijk is opgelost.
Het probleem zat hem niet in de plugin maar de SDK, deze zouden jullie dan ook moeten updaten. 
Als je gebruik maakt van Composer dan kan je de volgende commando runnen in de terminal:
`composer require myparcelnl/sdk "~v1.3.9"`. 

Mocht je Composer niet gebruiken dan kan je de nieuwe versie terug vinden op de volgende GitHub pagina: https://github.com/myparcelnl/sdk/releases

Mochten na het updaten van deze versie nog niet goed gaan dan hoor ik dat graag van je.

**Comment by Kroellie** [comment]
@RichardPerdaan Fixed! 👍
