### ISSUE TITLE
Making plugin compatible with virtual products

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/magento#158]
Case 00320040

**Comment by RichardPerdaan** [comment]
case: 00306206

**Comment by tbiest** [comment]
I think this is more a bug than a feature: I want to be able to sell giftcards, these do not have a delivery address. In checkout, this generates errors with Myparcel:

<b>Fatal error</b>:  Uncaught Error: Call to a member function getStreet() on null in /home/deb104330/domains/brewz.nl/public_html/dev003/vendor/myparcelnl/magento/Model/Quote/SaveOrderBeforeSalesModelQuoteObserver.php:76
Stack trace:
#0 /home/deb104330/domains/brewz.nl/public_html/dev003/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): MyParcelNL\Magento\Model\Quote\SaveOrderBeforeSalesModelQuoteObserver-&gt;execute(Object(Magento\Framework\Event\Observer))
#1 /home/deb104330/domains/brewz.nl/public_html/dev003/vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault-&gt;_callObserverMethod(Object(MyParcelNL\Magento\Model\Quote\SaveOrderBeforeSalesModelQuoteObserver), Object(Magento\Framework\Event\Observer))
#2 /home/deb104330/domains/brewz.nl/public_html/dev003/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault-&gt;dispatch(Array, Object(Magento\Framework\Event\Observer))
#3 /home/deb104330/domains/brewz.nl/public_html/dev003/ in <b>/home/deb104330/domains/brewz.nl/public_html/dev003/vendor/myparcelnl/magento/Model/Quote/SaveOrderBeforeSalesModelQuoteObserver.php</b> on line <b>76</b><br />
{"messages":{"error":[{"code":500,"message":"Fatal Error: 'Uncaught Error: Call to a member function getStreet() on null in \/home\/deb104330\/domains\/brewz.nl\/public_html\/dev003\/vendor\/myparcelnl\/magento\/Model\/Quote\/SaveOrderBeforeSalesModelQuoteObserver.php:76\nStack trace:\n#0 \/home\/deb104330\/domains\/brewz.nl\/public_html\/dev003\/vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php(72): MyParcelNL\\Magento\\Model\\Quote\\SaveOrderBeforeSalesModelQuoteObserver->execute(Object(Magento\\Framework\\Event\\Observer))\n#1 \/home\/deb104330\/domains\/brewz.nl\/public_html\/dev003\/vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php(60): Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod(Object(MyParcelNL\\Magento\\Model\\Quote\\SaveOrderBeforeSalesModelQuoteObserver), Object(Magento\\Framework\\Event\\Observer))\n#2 \/home\/deb104330\/domains\/brewz.nl\/public_html\/dev003\/vendor\/magento\/framework\/Event\/Manager.php(66): Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch(Array, Object(Magento\\Framework\\Event\\Observer))\n#3 \/home\/deb104330\/domains\/brewz.nl\/public_html\/dev003\/' in '\/home\/deb104330\/domains\/brewz.nl\/public_html\/dev003\/vendor\/myparcelnl\/magento\/Model\/Quote\/SaveOrderBeforeSalesModelQuoteObserver.php' on line 76","trace":"Trace is not available."}]}}

**Comment by RichardPerdaan** [comment]
In version [4.0.0-beta.1] (https://github.com/myparcelnl/magento/releases/tag/4.0.0-beta.1) the functionality has been added
