### ISSUE TITLE
Track en trace implementeren

### ISSUE THREAD

**Issue by Kroellie** [myparcelnl/magento#159]
Svp het track & trace mechanisme zoals deze ook in MyParcel - Magento 1 bestaat, implementeren.

**Comment by Kroellie** [comment]
Hi, when can we expect this rather common feature?

**Comment by RichardPerdaan** [comment]
In version [4.0.0-beta.1] (https://github.com/myparcelnl/magento/releases/tag/4.0.0-beta.1) the functionality has been added
