### ISSUE TITLE
Foutmelding bij aanmaken verzending

### ISSUE THREAD

**Issue by gerben86** [myparcelnl/magento#169]
Na het installeren van [Mageplaza Review Reminder](https://www.mageplaza.com/magento-2-review-reminder/) krijg ik deze foutmelding bij het aanmaken van een verzending in Magento 2.2.3: "Er kan geen zending met deze bestelling gemaakt worden. Zendingen kunnen niet worden aangemaakt als de status 'Wordt vastgehouden' is of als het product digitaal is."
De status van de order is Gaande en het is geen digitaal product.
Waar zou het dan aan kunnen liggen?
Nu ik de Review Reminder gedisabled heb gaat het goed, maar wat zou een betere oplossing hiervoor zijn?
Want de getoonde foutmelding is sowieso niet correct in dit geval.

**Comment by gerben86** [comment]
Issue is opgelost door MagePlaza.

**Comment by koffiekoningin** [comment]
Ik heb steeds dezelfde foutmelding die jij had, alleen had geen mageplaza. 
Kun je me vertellen wat de solution was?

**Comment by gerben86** [comment]
@koffiekoningin : helaas weet ik niet hoe ze het gefixed hebben (er waren meerdere fixes nodig om dat product goed werkend te krijgen).
Volgens mij ligt het eraan dat er iets fout gaat bij een listener op het event "save order".

**Comment by RichardPerdaan** [comment]
Is dit probleem nog steeds aanwezig?
Mocht dit niet meer voorkomen dan zou ik je willen vragen om de issue te sluiten.

**Comment by gerben86** [comment]
Probleem is opgelost door Mageplaza
