### ISSUE TITLE
UpgradeSchema.php + module.xml not in sync

### ISSUE THREAD

**Issue by Kroellie** [myparcelnl/magento#17]
UpgradeSchema.php Line 30: 
if (version_compare($context->getVersion(), '0.0.1') < 0) {
should be
if (version_compare($context->getVersion(), '0.1.11') < 0) {

Module.xml Line 2:
module name="MyParcelNL_Magento" setup_version="0.1.10"
should be
module name="MyParcelNL_Magento" setup_version="0.1.11"

**Comment by Kroellie** [comment]
The consequence was that the MyParcel adjustments of the DB tables were not executed at setup:upgrade.

**Comment by reindert-vetter** [comment]
Fixed in #18
