### ISSUE TITLE
sdk/src/Model/MyParcelClassConstants.php wordt gebruikt, maar mist

### ISSUE THREAD

**Issue by AlexNauta** [myparcelnl/magento#183]
vendor/myparcelnl/magento/Block/Sales/OrderAction.php doet een aanroep naar sdk/src/Model/MyParcelClassConstants.php voor het inladen van de EU landenlijst, maar in de nieuwste SDK versie zit dit bestand niet (sdk/src/Model/MyParcelClassConstants.php)
(tenminste, na wat zoekwerk leek me dat het hier fout ging)

Hierdoor kunnen er geen orders meer worden geopend in het admin panel.

Magento versie 2.1.12
PHP 7.0.x

Melding:
PHP message: PHP Fatal error:  Uncaught Error: Class 'MyParcelNL\\Sdk\\src\\Model\\MyParcelClassConstants' not found in /var/www/vhosts/--------.nl/httpdocs/vendor/myparcelnl/magento/Block/Sales/OrderAction.php:83\nStack trace:\n#0 /var/www/vhosts/--------.nl/httpdocs/var/view_preprocessed/html/vendor/myparcelnl/magento/view/adminhtml/templates/order_view_action.phtml(17): MyParcelNL\\Magento\\Block\\Sales\\OrderAction->isCdCountry()\n#1 /var/www/vhosts/--------.nl/httpdocs/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/vhosts...')\n#2 /var/www/vhosts/--------.nl/httpdocs/vendor/magento/framework/View/Element/Template.php(255): Magento\\Framework\\View\\TemplateEngine\\Php->render(Object(MyParcelNL\\Magento\\Block\\Sales\\OrderAction), '/var/www/vhosts...', Array)\n#3 /var/www/vhosts/--------.nl/httpdocs/vendor/magento/framework/View/Element/Template.php(279): Magento\\Framework\\View\\Element\\Template->fetchView('/var/www/vhosts...')\n#4 /var/www/vhosts/--------.nl/httpdocs/vendor/magento...\n', referer: https://www.--------.nl/admin/sales/order/index/key/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/

(domeinnaam en key verwijderd)

**Comment by gerben86** [comment]
@RichardPerdaan, @reindert-vetter: Hier hetzelfde probleem. Graag snel een oplossing, zo kunnen wij niets meer doen met een order in het admin-panel...

**Comment by TimBlom** [comment]
Beste Gerben en Alex,

Wellicht hebben jullie al contact gehad met mijn collega's, maar voor nu zou ik aan willen raden om een versie 1.3.13 van de SDK te gebruiken. Hier is MyParcelClassConstants.php nog wél aanwezig, waardoor je in ieder geval een tijdelijke oplossing hebt. Je moet minimaal PHP versie 5.6 hebben maar zoals ik in jouw bericht zie, is dat geen probleem. Wanneer er een nieuwe versie beschikbaar is, zullen jullie hiervan op de hoogte worden gebracht!

Voor nu wil ik jullie in ieder geval een hele mooie woensdag toewensen.

**Comment by TimBlom** [comment]
Ook case 00382751 en 00383412

**Comment by AlexNauta** [comment]
Ik heb het zelf voor nu even opgelost op deze manier:

In vendor/myparcelnl/magento/Block/Sales/OrderAction.php vervang regel 83:
`MyParcelClassConstants::EU_COUNTRIES`
En maak hiervan:
`'NL','BE','AT','BG','CZ','CY','DK','EE','FI','FR','DE','GB','GR','HU','IE','IT','LV','LT','LU','PL','PT','RO','SK','SI','ES','SE','XK'`

En doe hetzelfde in ShipmentAction.php op regel 95.

Dit is slechts een quick & dirty fix zodat mijn klant weer door kon met orders afhandelen. Ik zal op een rustig moment de SDK even proberen te downgraden.

**Comment by TimBlom** [comment]
Ook case 00386761

**Comment by RichardPerdaan** [comment]
Probleem is opgelost in de volgende versie:
* MyParcel Magento 2 plugin: [2.3.6-beta.1](https://github.com/myparcelnl/magento/releases/tag/2.3.6-beta.1)
* MyParcel SDK : [v1.3.15](https://github.com/myparcelnl/sdk/releases/tag/v1.3.15)

Mochten er vagen zijn dan hoor ik dat graag van jullie.
