### ISSUE TITLE
Andere afhaallocatie kiezen werkt niet

### ISSUE THREAD

**Issue by Kroellie** [myparcelnl/magento#184]
Hi, kan iemand dit voor mij valideren: een afhaalbestelling aanmaken m.b.v. pakjegemak, en dan een andere afhaal locatie dan de standaard voorgestelde locatie kiezen. Na het plaatsen van de bestelling is nog steeds de standaard (1e getoonde) locatie geplaatst in de order.

Versie:
myparcelnl/magento 2.3.5
myparcelnl/sdk v1.3.14

**Comment by michel334** [comment]
Dat gaat bij mij ook fout
Magento 2.2.3 met standaard 2 stappen checkout
Theme Ultimo maar gaat ook fout onder standaard themes zoals Luma
myparcelnl/magento 2.3.5

**Comment by RichardPerdaan** [comment]
Beste @Kroellie en @michel334,

Dank je wel voor het melden van dit probleem.
Ik heb het genoteerd, zodra het opgelost is zal ik contact met jullie opnemen.

**Comment by RichardPerdaan** [comment]
Beste @Kroellie en @michel334,

Dit probleem moet opgelost zijn met behulp van de nieuwe MyParcel checkout. De nieuwe checkout is geïmplementeerd in versie [2.4.0](https://github.com/myparcelnl/magento/releases/tag/2.4.0).
