### ISSUE TITLE
Change parcel to Mailbox 

### ISSUE THREAD

**Issue by adem-demir** [myparcelnl/magento#187]
At this time you can't change parcel to Mailbox in the backend of Magento

**Comment by RichardPerdaan** [comment]
It is possible to change the order under ** ship **, it is also possible to turn it into a Mailbox.

![Nieuwe verzending : Verzendingen : Operations : Sales : Magento Admin 2019-04-08 15-39-03](https://user-images.githubusercontent.com/11389731/55728543-880e6000-5a14-11e9-8c40-c120c24b7329.png)
