### ISSUE TITLE
extensie kunnen uitzetten onder x gram /  envelop met 1 of 2 postzegels

### ISSUE THREAD

**Issue by RichardPerdaan** [myparcelnl/magento#188]
De onderstaande table rate wordt gebruikt:
 
0-20 gram (1 postzegel)
21-50 gram (2 postzegels)
50-XXX gram (myparcel tarieven)
 
Het probleem is echter dat de extensie niet een mogelijkheid heeft om zichzelf uit te schakelen beneden een XX aantal gram.

Een andere optie is om een envelop met 1 of 2 postzegels aan te bieden aan de consumenten (zoals de optie van brievenbuspakje).

@PowerBall.shop

**Comment by gjportegies** [comment]
Dit is ook iets waar wij tegenaan lopen. Wij verzenden gratis kleurwaaiers. Deze kunnen met enkel 1 'digitale postzegel' verzonden worden. Normaal gesproken hanteren wij 6,95 verzendkosten. Voor deze kleurenwaaier hebben wij een winkelwagen prijsregel welke echter gratis verzending mogelijk maakt voor dit artikel. 
De MyParcel module blijft echter alle opties geven(zoals afhalen bij postNL punt) in het afreken proces. Wanneer een klant hiervoor kiest wordt dit echter gekenmerkt als pakketpost terwijl het een eenvoudig brief is.

Momenteel heb ik dit opgelost door wanneer alleen dit specifieke artikel in de winkelwagen zit de MyParcel (flatrate_flatrate) uit te schakelen en de gratis verzending (freedelivery_freedelivery) optie te tonen. Dit is echter niet heel flexibel. Wanneer verwachten jullie deze feature te implementeren?

**Comment by RichardPerdaan** [comment]
Sinds versie [2.5.0](https://github.com/myparcelnl/magento/releases/tag/2.5.0) is het mogelijk om digitale postzegel aan ta maken.

**Comment by Kroellie** [comment]
@RichardPerdaan Kan je wat meer uitleg geven over hoe dat ingericht moet worden? Ik heb nu een tablerate van 0-20 gram en 21-50 gram en daarboven voor postzegels, en die tarieven lijken na installatie van jullie 2.5.1 module nog steeds te gelden, en niet de waarde die ik in de backoffice heb ingesteld bij digitale postzegel.
