### ISSUE TITLE
Bugfix voor 1.0.8

### ISSUE THREAD

**Issue by bezigeboefjes** [myparcelnl/magento#190]
We zitten met onze shops nog steeds op versie 1 van de plugin, omdat versie 2 voor ons (destijds) niet werkt (staat op de planning om de laatste versie weer te testen om te kijken of dat beter voor ons werkt).

Ik loop echter tegen een bug aan die door jullie al in versie 2 gefixed is, namelijk:
Uncaught Error: Class 'myparcelnl\\sdk\\src\\Model\\MyParcelClassConstants' not found

De fix is erg simpel:
In vendor/myparcelnl/magento/Block/Sales/OrderAction.php:
```
    public function isCdCountry()
    {
        return !in_array(
            $this->getCountry(),
            MyParcelClassConstants::EU_COUNTRIES
        );
    }
```
Vervangen door: 
```
    public function isCdCountry()
    {
          return $this->consignmentRepository->isCdCountry();
    }
```
De diff:
```
76,79c76
<         return !in_array(
<             $this->getCountry(),
<             MyParcelClassConstants::EU_COUNTRIES
<         );
---
>           return $this->consignmentRepository->isCdCountry();
```

Kunnen jullie deze patch aanpassen in de 1.0.x release? Ik snap dat deze release misschien niet meer ondersteund wordt, maar ik zou hier al enorm mee geholpen zijn.

**Comment by RichardPerdaan** [comment]
Helaas zullen wij in versie 1.0.x geen aanpassing meer doen. De reden hiervan is omdat wij verder gaan op de nieuwere versies waarbij dit probleem ook al opgelost is.

Ik zou je daarom willen adviseren om de nieuwste versie te installeren. Mochten er dan problemen zijn dan hoor ik dat graag van je, dan kunnen we samen naar de oplossing kijken.
