### ISSUE TITLE
Issue toevoeging labels

### ISSUE THREAD

**Issue by RemcovElk** [myparcelnl/magento#192]
Er is een probleem met het aanmaken van labels naar België die een toevoeging bevatten. Wanneer het huisnummer bijvoorbeeld 12 is en toevoeging is 15 wordt het huisnummer bij exporteren 1215 en komt er bij toevoeging 15 te staan.

Casenr: 432631

**Comment by RichardPerdaan** [comment]
Issue is solved in version[ v1.4.0-beta.1](https://github.com/myparcelnl/sdk/releases/tag/v1.4.0-beta.1) of the [SDK](https://github.com/myparcelnl/sdk)
