### ISSUE TITLE
Create label on filtered order list fails

### ISSUE THREAD

**Issue by Kroellie** [myparcelnl/magento#197]
Version 2.3.6:

When filtering the Magento 2 order list on for example all orders with status 'processing', and selecting 'Print MyParcel labels directly', the system generates an error report:

{"0":"No items selected","1":"#0 \/var\/www\/vendor\/myparcelnl\/magento\/Controller\/Adminhtml\/Order\/CreateAndPrintMyParcelTrack.php(59): MyParcelNL\\Magento\\Controller\\Adminhtml\\Order\\CreateAndPrintMyParcelTrack->massAction()\n#1 \/var\/www\/vendor\/magento\/framework\/App\/Action\/Action.php(107): MyParcelNL\\Magento\\Controller\\Adminhtml\\Order\\CreateAndPrintMyParcelTrack->execute()\n#2 \/var\/www\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\Action\\Action->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#3 \/var\/www\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): MyParcelNL\\Magento\\Controller\\Adminhtml\\Order\\CreateAndPrintMyParcelTrack\\Interceptor->___callParent('dispatch', Array)\n#4 \/var\/www\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): MyParcelNL\\Magento\\Controller\\Adminhtml\\Order\\CreateAndPrintMyParcelTrack\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#5 \/var\/www\/generated\/code\/MyParcelNL\/Magento\/Controller\/Adminhtml\/Order\/CreateAndPrintMyParcelTrack\/Interceptor.php(26): MyParcelNL\\Magento\\Controller\\Adminhtml\\Order\\CreateAndPrintMyParcelTrack\\Interceptor->___callPlugins('dispatch', Array, Array)\n#6 \/var\/www\/vendor\/magento\/framework\/App\/FrontController.php(55): MyParcelNL\\Magento\\Controller\\Adminhtml\\Order\\CreateAndPrintMyParcelTrack\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#7 \/var\/www\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#8 \/var\/www\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#9 \/var\/www\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#10 \/var\/www\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, Array)\n#11 \/var\/www\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#12 \/var\/www\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http->launch()\n#13 \/var\/www\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#14 {main}","url":"\/mgmt\/myparcelnl\/order\/CreateAndPrintMyParcelTrack\/key\/ecc40f41b00f8af90b5a8213c0c8d3b1c0b90bb2d9a177bf3f9796486968f1dc\/","script_name":"\/index.php"}

**Comment by RichardPerdaan** [comment]
Dear @Kroellie,

Is this problem still present with the current version of the plugin?
if this is no longer present, would you like to close the issue?
