### ISSUE TITLE
If there's only 1 shipping method available that one should be selected by default in checkout

### ISSUE THREAD

**Issue by gerben86** [myparcelnl/magento#200]
When only the mailbox-radiobutton is shown to the customer, that option should be selected by default, because he doesn't have a choice anyway :) :

![image](https://user-images.githubusercontent.com/17478858/48304730-881a3a80-e51e-11e8-8202-b6f318e13608.png)

Could this be part of the MyParcel-plugin or is this default Magento behaviour?

**Comment by reindert-vetter** [comment]
We are not going to solve this problem right now. I expect that within 2 months we will solve most of the issues of this plugin. I hope that we will work on this issue also.

**Comment by gerben86** [comment]
> We are not going to solve this problem right now. I expect that within 2 months we will solve most of the issues of this plugin. I hope that we will work on this issue also.

I see that the new version also doesn't have this feature. Could you have a look if this can be implemented?

**Comment by RichardPerdaan** [comment]
In version [4.0.0-beta.1] (https://github.com/myparcelnl/magento/releases/tag/4.0.0-beta.1) the functionality has been added
