### ISSUE TITLE
Cron job doesn't check all statuses

### ISSUE THREAD

**Issue by Webunity** [myparcelnl/magento#201]
In the code (magento/Cron/UpdateStatus.php) you filter on myparcel_status 0,1,2,3,4,5,6

Code-wise, status 0 is never set, so including that doesn't make sense, right?

In the Dutch CSV file there is also a status 8 (Zending op afhaallocatie) and a status 9 (zending daadwerkelijk afgehaald). If you don't query for 8 you never go to 9.

I think this:
```
$trackCollection
            ->addFieldToSelect('order_id')
            ->addAttributeToFilter('myparcel_status', [0, 1, 2, 3, 4, 5, 6])
            ->addAttributeToFilter('myparcel_consignment_id', ['notnull' => true])
            ->addAttributeToFilter(ShipmentTrackInterface::CARRIER_CODE, MyParcelTrackTrace::MYPARCEL_CARRIER_CODE)
            ->setPageSize(300)
            ->setOrder('order_id', 'DESC');
```

Should become:
````
$trackCollection
            ->addFieldToSelect('order_id')
            ->addAttributeToFilter('myparcel_status', [1, 2, 3, 4, 5, 6, 8])
            ->addAttributeToFilter('myparcel_consignment_id', ['notnull' => true])
            ->addAttributeToFilter(ShipmentTrackInterface::CARRIER_CODE, MyParcelTrackTrace::MYPARCEL_CARRIER_CODE)
            ->setPageSize(300)
            ->setOrder('order_id', 'DESC');
````

**Comment by reindert-vetter** [comment]
@Webunity Dit klopt. Bedankt voor je bijdragen. Je kan een pull-request aanmaken, dan zal ik hem gelijk goedkeuren. Anders zullen we dit oppakken zodra we (bijna alle) issues gaan oplossen. Dit staat gepland op begin 2018.
