### ISSUE TITLE
Labels not printed when hyphen in address

### ISSUE THREAD

**Issue by gerben86** [myparcelnl/magento#221]
Hi, printing a label for this street/housenumber didn't work: "Kerkstraat  1 - B ". We got this error:

>  An error has occurred while validating the address: KERKSTRAAT  1 - B. Check number and number suffix.
> An error has occurred while creating a MyParcel label and the error is being logged. You may not have entered the correct API key.

Logging in exception.log:
`[2018-12-21 15:18:36] main.CRITICAL: Error in MyParcel API request: 0 - data.shipments[0].recipient.street NULL value found, but a string is required - Failed validation against JSON-SCHEMA shipment/post_shipments_request.json Url: https://api.myparcel.nl/shipments Request: {"data":{"shipments":[{"recipient":{"cc":"NL","person":"name","postal_code":"1111AA","city":"STAD","email":"ab@cd.ef","phone":"","company":"","street":null,"street_additional_info":"","number":null,"number_suffix":""},"options":{"package_type":1,"label_description":"description;","only_recipient":0,"signature":0,"return":0,"delivery_type":2,"large_format":0,"delivery_date":"2018-12-27 00:00:00"},"carrier":1,"reference_identifier":"123456"}]}} {"exception":"[object] (Exception(code: 0): Error in MyParcel API request: 0 - data.shipments[0].recipient.street NULL value found, but a string is required - Failed validation against JSON-SCHEMA shipment/post_shipments_request.json Url: https://api.myparcel.nl/shipments Request: {\"data\":{\"shipments\":[{\"recipient\":{\"cc\":\"NL\",\"person\":\"NAME\",\"postal_code\":\"1111AA\",\"city\":\"STAD\",\"email\":\"ab@cd.ef\",\"phone\":\"\",\"company\":\"\",\"street\":null,\"street_additional_info\":\"\",\"number\":null,\"number_suffix\":\"\"},\"options\":{\"package_type\":1,\"label_description\":\"description;\",\"only_recipient\":0,\"signature\":0,\"return\":0,\"delivery_type\":2,\"large_format\":0,\"delivery_date\":\"2018-12-27 00:00:00\"},\"carrier\":1,\"reference_identifier\":\"123456\"}]}} at vendor/myparcelnl/sdk/src/Model/MyParcelRequest.php:182)"} []`

Logging in system.log:
`[2018-12-21 15:18:31] main.CRITICAL: An error has occurred while validating the address: KERKSTRAAT 1 - B. Check number and number suffix.-Exception: Invalid full street supplied: KERKSTRAAT 1 - B in /vendor/myparcelnl/sdk/src/Model/Repository/MyParcelConsignmentRepository.php:399
Stack trace:
#0 /vendor/myparcelnl/sdk/src/Model/Repository/MyParcelConsignmentRepository.php(104): MyParcelNL\Sdk\src\Model\Repository\MyParcelConsignmentRepository->splitStreet('KERKSTRAAT 1 -...')
#1 /vendor/myparcelnl/magento/Model/Sales/MyParcelTrackTrace.php(139): MyParcelNL\Sdk\src\Model\Repository\MyParcelConsignmentRepository->setFullStreet('KERKSTRAAT 1 -...')
#2 /vendor/myparcelnl/magento/Model/Sales/MagentoCollection.php(307): MyParcelNL\Magento\Model\Sales\MyParcelTrackTrace->convertDataFromMagentoToApi(Object(Magento\Sales\Model\Order\Shipment\Track), Array)
#3 /vendor/myparcelnl/magento/Model/Sales/MagentoOrderCollection.php(163): MyParcelNL\Magento\Model\Sales\MagentoCollection->getMyParcelTrack(Object(Magento\Sales\Model\Order\Shipment\Track))
#4 /vendor/myparcelnl/magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack.php(112): MyParcelNL\Magento\Model\Sales\MagentoOrderCollection->setMyParcelTrack()
#5 /vendor/myparcelnl/magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack.php(59): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack->massAction()
#6 /vendor/magento/framework/App/Action/Action.php(107): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack->execute()
#7 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#8 /vendor/magento/framework/Interception/Interceptor.php(138): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->___callParent('dispatch', Array)
#9 /vendor/magento/framework/Interception/Interceptor.php(153): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#10/generated/code/MyParcelNL/Magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack/Interceptor.php(26): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->___callPlugins('dispatch', Array, Array)
#11/vendor/magento/framework/App/FrontController.php(55): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#12/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#13/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#14/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#16/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#17/vendor/magento/framework/App/Bootstrap.php(257): Magento\Framework\App\Http->launch()
#18/pub/index.php(68): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#19 {main} [] []`

Once we removed the hyphen (so it became Kerkstraat 1B) the label could be printed.

What would be the best way to solve this? Because I don't like the manual work in here :)

**Comment by gerben86** [comment]
@adem-demir : Kun je uitleggen waarom deze gesloten is? Want ik heb nog geen bericht gekregen dat dit opgelost is.

**Comment by adem-demir** [comment]
@gerben86 zelfde hier werkt inderdaad ook nog niet

**Comment by adem-demir** [comment]
Gerben, ik heb dit nu met de laatste versie getest en ik krijg daarin een label dan wel zonder een "-". Is dit werkbaar voor jou?

**Comment by gerben86** [comment]
Dat lijkt me een prima oplossing!

Op do 9 jul. 2020 om 22:54 schreef Adem Demir <notifications@github.com>:

**Comment by RichardPerdaan** [comment]
Opgelost in versie [4.1.0](https://github.com/myparcelnl/magento/releases/tag/4.1.0)
