### ISSUE TITLE
Support Multi Source Inventory (MSI)

### ISSUE THREAD

**Issue by RichardPerdaan** [myparcelnl/magento#224]
In magento 2.3, is the Multi Source Inventory (MSI) added [(https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.html).](https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.html)

**Comment by RichardPerdaan** [comment]
@PowerBall.shop

**Comment by Kroellie** [comment]
`1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Notice: Undefined variable: sourceCode in /var/www/magento/vendor/magento/module-inventory-shipping/Observer/SourceDeductionProcessor.php on line 112

Exception #0 (Magento\Framework\Exception\LocalizedException): Notice: Undefined variable: sourceCode in /var/www/magento/vendor/magento/module-inventory-shipping/Observer/SourceDeductionProcessor.php on line 112
#0 /var/www/magento/vendor/myparcelnl/magento/Model/Sales/MagentoOrderCollection.php(88): MyParcelNL\Magento\Model\Sales\MagentoOrderCollection->createShipment(Object(Magento\Sales\Model\Order\Interceptor))
#1 /var/www/magento/vendor/myparcelnl/magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack.php(96): MyParcelNL\Magento\Model\Sales\MagentoOrderCollection->setNewMagentoShipment()
#2 /var/www/magento/vendor/myparcelnl/magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack.php(59): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack->massAction()
#3 /var/www/magento/generated/code/MyParcelNL/Magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack/Interceptor.php(24): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack->execute()
#4 /var/www/magento/vendor/magento/framework/App/Action/Action.php(108): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->execute()
#5 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#6 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->___callParent('dispatch', Array)
#7 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#8 /var/www/magento/generated/code/MyParcelNL/Magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack/Interceptor.php(39): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->___callPlugins('dispatch', Array, Array)
#9 /var/www/magento/vendor/magento/framework/App/FrontController.php(159): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#10 /var/www/magento/vendor/magento/framework/App/FrontController.php(99): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor))
#11 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#12 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#13 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#14 /var/www/magento/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#15 /var/www/magento/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#16 /var/www/magento/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#17 /var/www/magento/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#18 /var/www/magento/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#19 {main}`

**Comment by Kroellie** [comment]
Hi, any roadmap to share on this? It feels like a relatively small modification?

**Comment by RichardPerdaan** [comment]
Unfortunately this feature is not currently on the route map. The reason for this is because our priorities are currently at a different point at the moment.

We would like to pick up this feature. Perhaps it is possible to create a pull request as soon as the solution is found.

That way we can improve the plugin together.

**Comment by rsp-vicus** [comment]
This is kind a big issue.

When selecting one or more orders and chose for  "Print MyParcel lables" the error occurs and no shipments are send to MyParcel. 

So  it is only possible to make a shipment one by one and not by batch. 

That is not really how it should work....especially when you have a lot of orders on a day.

> We found a workaround for this by adding an attribute to the logged in user and passing that to the variable "sourceCode" in line 112 above. 

What is the workaround?

**Comment by Kroellie** [comment]
I think you are referring to a different issue. This one was for having stocks at multiple locations and being able to 'choose' which location is sending the order so only that stock on that location is being modified. In chance you are referring to the same: on line 112 in the file /var/www/magento/vendor/magento/module-inventory-shipping/Observer/SourceDeductionProcessor.php there is a variable called "sourcecode" this is the shortcode for the stock location. So if you are person A who is logged in, you can assume sourcecode LOC-A for example, and person B would have LOC-B. Investigating at line 112 who you are and use the corresponding sourcecode would resolve our issue for now.

**Comment by rsp-vicus** [comment]
the issue happens indeed when  Multi Source Inventory (MSI) is used.

But it is a default Magento setting. At this moment MyParcel seems not working together with this MSI in batch.

**Comment by RichardPerdaan** [comment]
Case: 00557657

**Comment by Daniel304** [comment]
This is a rather big deal for us this means we can not use MyParcel or MSI. starting dropshipping from our warehouse is due to this not possible. Is there an idea when this is picked up..

**Comment by Gnobama** [comment]
Hello MyParcel....!
As mentioned before, it's a standard feature from Magento 2 so if you support an api it should work!

**Comment by RichardPerdaan** [comment]
There is a research story to find out what needs to be done within the MyParcel plugin to support the MSI.

**Comment by RichardPerdaan** [comment]
Solved in [4.3.0-alpha.1](https://github.com/myparcelnl/magento/releases/tag/4.3.0-alpha.1)
