### ISSUE TITLE
More shipping method selected

### ISSUE THREAD

**Issue by adem-demir** [myparcelnl/magento#228]
When selecting pickup the other options still selected:
![checkout 2019-01-14 14-44-17](https://user-images.githubusercontent.com/37372250/51116625-f4aa0200-180b-11e9-995b-7fb2cc6fbd60.jpg)

**Comment by adem-demir** [comment]
00496773

**Comment by bezigeboefjes** [comment]
Hier hebben wij ook last van. Heb een schone installatie van Magento geprobeerd, hetzelfde probleem. 

Zou mooi zijn als deze bug gefixed wordt, dit is de enige bug die ons nog tegenhoud om van de oude versie 1 naar deze versie te updaten. We zitten enorm te springen om de extra opties voor leveringen!

**Comment by bezigeboefjes** [comment]
Zou hier naar gekeken kunnen worden? We zitten helaas nog steeds vast in versie 1 van de plugin door dit probleem.

**Comment by RichardPerdaan** [comment]
Binnen kort zal er weer een sprint aankomen waarbij er allemaal GitHub issues worden opgepakt. Dit zal één van de issue's zijn die ik graag op zou willen pakken.

**Comment by figinternet** [comment]
+1 Following, last van het zelfde probleem.

**Comment by Calypso971** [comment]
Deze bug is al sinds begin dit jaar bekend, en via de andere melding is het laatste antwoord van juni dit jaar: "This problem is the number one for me to solve". We zijn inmiddels 2 maanden verder - is er uberhaupt al iets over een oplostermijn te zeggen? Ik ben het met anderen eens dat dit een kritische bug is die implementatie (en voor ons dus gebruik van) MyParcel in de weg staat.

**Comment by adem-demir** [comment]
@Calypso971 we zijn op dit moment bezig met een nieuwe checkout. We gaan morgen hierin een test uitvoeren om te kijken of dit issue dan ook is opgelost. We zullen je morgen uiterlijk vrijdag nog meer informatie kunnen geven.

**Comment by bezigeboefjes** [comment]
Hoop dat het opgelost is met een nieuwe checkout. Op dit moment zitten we door deze bug nog steeds op versie 1 van de plugin (en die begint steeds meer issues te vertonen in de nieuwste versies van Magento). Ik test graag wat voor je uit!

**Comment by Calypso971** [comment]
Zeuren is niet iets waar ik van hou, maar inmiddels is er een maand geleden aangegeven dat er "morgen uiterlijk vrijdag" wat meer informatie zou komen, maar het is aardig stil gebleven. Voor een bug die door behoorlijk wat klanten als "ongewenst" betiteld wordt, en door jullie zelf als "#1 om op te lossen" aangemerkt is, had ik gehoopt dat er nu onderhand wel bekend zou zijn of er progressie is en wat we kunnen verwachten.

**Comment by adem-demir** [comment]
@Calypso971 Goedemorgen! Wij zullen dit probleem oplossen daar zijn we van zeker. Helaas is deze (checkout) nog niet af omdat we nog met een enkel bugs aan het fixen zijn en het langer gaat duren dan gepland. Ik zal morgen met de Magento developer overleggen hoe we dit dan wel zsm kunnen oplossen.

**Comment by RichardPerdaan** [comment]
De code in de volgende pull request #306 zal dit probleem verhelpen.

**Comment by RichardPerdaan** [comment]
De aanpassingen zijn doorgevoerd in versie [3.0.4-beta.1](https://github.com/myparcelnl/magento/releases/tag/3.0.4-beta.1) van de MyParcel plugin.
Mochten er problemen zijn dan hoor ik dat graag van jullie.

**Comment by Calypso971** [comment]
Richard, hier versie 3.0.4 geinstalleerd, maar ik heb het probleem nog steeds. Als ik een andere bezorgingsmethode geselecteerd heb en dan een MyParcel methode selecteer verdwijnt de eerdere selectie. Andersom echter niet; dus eerst een "myparcel" methode selecteren, en daarna een andere. Dan blijft die bij de myparcel methode aangevinkt.

**Comment by Calypso971** [comment]
@RichardPerdaan Richard, dit issue is nog niet opgelost. Sterker nog, zojuist de RC van 3.1.0 geinstalleerd en het stukje wat opgelost was, treedt nu ook weer op. Eigenlijk t.o.v. de originele call niets veranderd dus. Erg frustrerend.
