### ISSUE TITLE
2.4.2 print labels op A6 format ipv ingestelde A4 formaat

### ISSUE THREAD

**Issue by bamboekeizer** [myparcelnl/magento#231]
The printformaat staat ingesteld op A4, maar bij het aanmaken van het label in het bestellingen overzicht middels Track Actie - Download label wordt er toch een A6 pdf aangemaakt.
De magento versie is 2.3.0.

**Comment by RichardPerdaan** [comment]
Goedemorgen @bamboekeizer,

Het is een tijd geleden dat dit op GitHub is gezet, is het probleem nog steeds aanwezig?

**Comment by bamboekeizer** [comment]
No, the problem is gone. I have moved to magento 2.3.2 and myparcel 3.0.3
