### ISSUE TITLE
Mageplaza onestepcheckout compability 

### ISSUE THREAD

**Issue by adem-demir** [myparcelnl/magento#232]
compability with the newest version

**Comment by bamboekeizer** [comment]
Can you comment on what issue exists. I run version OSC 2.6.2 with Magento 2.3.0.

**Comment by tbiest** [comment]
I am also experiencing some problems on M 2.3.0 with Mageplaza checkout version 2.7.0

1) When you select Design style "Material", then in the frontend the customer cannot see the delivery timeslots (only date is showing).
2) I get a jquery error, many failed requests on loading in the background. However the rest of checkout seems to work regardless of this error.

**Comment by tbiest** [comment]
Issues persist on version Magento 2.3.1 with Mageplaza Onestepchecktout V2.7

Javascript error: 
RangeError: Maximum call stack size exceeded.
jQuery.min.js:39

It seams to break up the buildup of the Myparcel delivery options including timeslots etc.

Myparcel version 2.3.5 works, but later versions including current 2.5.2 breaks.
![screenshot OSC2](https://user-images.githubusercontent.com/29130465/56431351-ae13ea00-62c9-11e9-98b6-fbf21d8bba39.png)
![screenshot OSC1](https://user-images.githubusercontent.com/29130465/56431352-ae13ea00-62c9-11e9-9141-38d4757b52ac.png)

**Comment by tbiest** [comment]
Since the last update of mageplaza (version 2.8.1) the errors I was facing got fixed. So the combination of Mageplaza 2.8.1 with Myparcel 2.5.2

**Comment by RichardPerdaan** [comment]
Hi @tbiest,
Thank you for checking the last version of the Mageplaza checkout.

Because this problem is solved by Mageplaza I will close this issue. If there are still problems, you can always open the issue again.
