### ISSUE TITLE
Customer selected pickup location, but shipments is send to his own adres

### ISSUE THREAD

**Issue by gerben86** [myparcelnl/magento#234]
I have a customer who selected a pickup location during the checkout, but the shipment is send to his own house adres.
This is what I see in the Magento Backend for this order:
![image](https://user-images.githubusercontent.com/17478858/52363345-cd2d0a80-2a42-11e9-8c2a-6fea10d33330.png)

Do you know what happend (I don't see anything in the logs)?
Because I get complaints of the customer, while everything went fine from our side.

**Comment by RichardPerdaan** [comment]
Hi @gerben86,

Which version of the MyParcel plugin do you use? This problem has been solved in version [2.4.2](https://github.com/myparcelnl/magento/releases/tag/2.4.2)

**Comment by gerben86** [comment]
Ok, I'm using `De MyParcel extensie versie 2.4.0`

**Comment by gerben86** [comment]
Issue looks solved, I'll close this.
