### ISSUE TITLE
Magento 2.3 - Warning: count(): Parameter must be an array or an object that implements Countable in /data/web/current/vendor/myparcelnl/magento/Model/Rate/Result.php on line 271

### ISSUE THREAD

**Issue by digikeijs** [myparcelnl/magento#242]
When creating a order through the magento 2.3 admin and selecting a shipping method I get t his error
```
main.CRITICAL: Exception message: Warning: count(): Parameter must be an array or an object that implements Countable in /data/web/current/vendor/myparcelnl/magento/Model/Rate/Result.php on line 271
Trace: #0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'count(): Parame...', '/data/web/curre...', 271, Array)```

version

        "myparcelnl/magento": "^2.4",
        "myparcelnl/sdk": "^v1.5",

**Comment by RichardPerdaan** [comment]
The problem wil be solved in the next version of the plugin. The solution can be found in this pull request #243

**Comment by digikeijs** [comment]
@RichardPerdaan how can I see the solution? 243 has a link back to 242

**Comment by RichardPerdaan** [comment]
@digikeijs Wow my mistake the correct link is #237

**Comment by digikeijs** [comment]
@RichardPerdaan haha no problem. Thanks for the very quick response.

**Comment by RichardPerdaan** [comment]
The problem has been solved in version 2.5.0-beta.1.
If there are still problems, you can always reopen the issue.

**Comment by digikeijs** [comment]
@RichardPerdaan looks like this issue is not the latest release 2.5.1. When I use the fix proposed in this issue fix the checkout gives a red error and the customer will not see any myparcel issues.

**Comment by RichardPerdaan** [comment]
Hi @digikeijs,

Can you check version [2.5.2](https://github.com/myparcelnl/magento/releases/tag/2.5.2) of the plugin?
