### ISSUE TITLE
Magento 2.3 - Not able to create shipment for export countries

### ISSUE THREAD

**Issue by digikeijs** [myparcelnl/magento#243]
Shipments to non export are working fine but a shipment to an export country do not work. Product has the default magento 2 weight filled in. 

        "myparcelnl/magento": "^2.4",
        "myparcelnl/sdk": "^v1.5",
```
[2019-03-01 19:37:53] main.CRITICAL: Error in MyParcel API request: data.shipments[0].options.delivery_type - data.shipments[0].options.delivery_type - Shipment validation error Url: https://api.myparcel.nl/shipments 
Request: {"data":{"shipments":[{"recipient":{"cc":"CH","person":"Sander","postal_code":"4460","city":"Gelterkinden","email":"b2b@aa.nl","phone":"","street":"Ribistrasse 10","street_additional_info":""},"options":{"package_type":1,"label_description":"1400005789","delivery_date":"2019-03-05 00:00:00"},"carrier":1,"customs_declaration":{"contents":1,"weight":1,"items":[{"description":"DR4018 16-channel switch decoder","amount":1,"weight":0,"classification":"0000","country":"NL","item_value":{"amount":28,"currency":"EUR"}}],"invoice":"1400005789"},"physical_properties":{"weight":1}}]}} {"exception":"[object] (Exception(code: 0): Error in MyParcel API request: data.shipments[0].options.delivery_type - data.shipments[0].options.delivery_type - Shipment validation error Url: https://api.myparcel.nl/shipments Request: {\"data\":{\"shipments\":[{\"recipient\":{\"cc\":\"CH\",\"person\":\"Sander \",\"postal_code\":\"4460\",\"city\":\"Gelterkinden\",\"email\":\"b2b@33.nl\",\"phone\":\"\",\"street\":\"Ribistrasse 10\",\"street_additional_info\":\"\"},\"options\":{\"package_type\":1,\"label_description\":\"1400005789\",\"delivery_date\":\"2019-03-05 00:00:00\"},\"carrier\":1,\"customs_declaration\":{\"contents\":1,\"weight\":1,\"items\":[{\"description\":\"DR4018 16-channel switch decoder\",\"amount\":1,\"weight\":0,\"classification\":\"0000\",\"country\":\"NL\",\"item_value\":{\"amount\":28,\"currency\":\"EUR\"}}],\"invoice\":\"1400005789\"},\"physical_properties\":{\"weight\":1}}]}} at /data/web/current/vendor/myparcelnl/sdk/src/Model/MyParcelRequest.php:182)"} []```

**Comment by digikeijs** [comment]
@reindert-vetter @RichardPerdaan can you please give an update on this? Also asked per mail but nobody is replying. This has been going on for a long time and all export shipments need to be done manually in your portal which if a lot of extra work. In addition above reference should be removed as it's not related.

**Comment by RichardPerdaan** [comment]
Best @digikeijs ,

Good that you indicate it. I see that the case is on my colleague's name, unfortunately he is sick. 
I see in the request that there is a `delivery_date`.

Unfortunately, it is not possible to use a `delivery_date` with an export country.

Can you try version [v2.0.1-beta.1](https://github.com/myparcelnl/sdk/releases/tag/v2.0.1-beta.1) of the SDK?

**Comment by digikeijs** [comment]
Thanks will try in today. The order went through the normal table rate with myparcel so the delivery date is added by the module.

**Comment by RichardPerdaan** [comment]
I think the composer.lock file stops the update maybe you can rename / delete this file

**Comment by RichardPerdaan** [comment]
Hi @digikeijs ,
The solution is to add "minimum stability": "dev" to your composer.json file.
Can You indicate if this is the solution for the problem?

**Comment by digikeijs** [comment]
@RichardPerdaan not an option because I do not want to install dev versions of all my magento modules. How can we implement this only for your module?

**Comment by RichardPerdaan** [comment]
Version 2.0.2 of the SDK is stable marked, so the installation should no longer be a problem.

@digikeijs unfortunately that is not possible because the SDK is installed via the composer file, that is globally in your root.

When this issue is no longer a problem, would you like to close the issue?

**Comment by digikeijs** [comment]
@RichardPerdaan new issue when creating an export shipment

[2019-03-13 10:14:34] main.CRITICAL: Can't run getConsignmentsByReferenceId() because referenceId can't be null {"exception":"[object] (Exception(code: 0): Can't run getConsignmentsByReferenceId() because referenceId can't be null at /data/web/current/vendor/myparcelnl/sdk/src/Helper/MyParcelCollection.php:107)"} []

**Comment by RichardPerdaan** [comment]
Hi @digikeijs,
This is one of the points that will be improved with the following MyParcel Magento plugin (update 2.5.0). Here you can find the solution: [#239](https://github.com/myparcelnl/magento/pull/239/files)

**Comment by RichardPerdaan** [comment]
Hi @digikeijs 

Is the issue `CRITICAL: Can't run getConsignmentsByReferenceId()` in version [2.5.2](https://github.com/myparcelnl/magento/releases/tag/2.5.2) solved?

**Comment by digikeijs** [comment]
@RichardPerdaan yes it is but please finish the outstanding work on the labels as we since magento 2 still cannot use mypcarcel in combination with magento for export orders.
