### ISSUE TITLE
 Country_id reset to NL when using the + / - qty fields in mageplaza onestepcheckout

### ISSUE THREAD

**Issue by digikeijs** [myparcelnl/magento#247]
When using magento 2.3 with MyParcel, tablerate and the mageplaza onestepcheckout we have the following issue.

When creating an order for NL the free shipping price is calculated correctly. When we change the country to US the shipping price is correct and changed to the correct table rate price. No free shipping for US.

Now comes the problem, when using the qty + / - fields the country ID is reset to NL and we have free shipping again but he country is still US. So this is an issue.

First load

![image](https://user-images.githubusercontent.com/34745091/54199535-6f6c6200-44c9-11e9-9c35-d5dbd6fbe10d.png)

Change to US

![image](https://user-images.githubusercontent.com/34745091/54199561-8612b900-44c9-11e9-861a-cdbcfb1b4204.png)

Change QTY 

![image](https://user-images.githubusercontent.com/34745091/54199623-a9d5ff00-44c9-11e9-9610-ac16ece16854.png)

When your module is turned off the issue does not occur!

**Comment by RichardPerdaan** [comment]
case @00529034

**Comment by digikeijs** [comment]
@RichardPerdaan can you tell me when this will be fixed? Stopping us from going live

**Comment by RichardPerdaan** [comment]
I am currently completing a few major projects. If this is done, then I will start with several github issues, including this one. If everything goes according to plan then I expect to have the solution in 2 weeks.

**Comment by Kroellie** [comment]
This is weird, I also have mageplaza osc, but don't suffer from this problem. Might be because we disabled all other countries. Tried it between the countires we DO have enabled, still the issue doesn't occur.

**Comment by digikeijs** [comment]
> This is weird, I also have mageplaza osc, but don't suffer from this problem. Might be because we disabled all other countries. Tried it between the countires we DO have enabled, still the issue doesn't occur.

Most likely due to multi store setup in magento. Please contact me if you want acces to our dev setup

**Comment by RichardPerdaan** [comment]
Problem is solved in version 3.1.4-beta.2 of the MyParcel plugin
