### ISSUE TITLE
Loading of MyParcel checkout

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/magento#250]
As a client I do not want to show the shipping method before loading the MyParcel checkout.

https://monosnap.com/file/4fqj6xsVH2MMxnh8WYZg30I9JqbjJb

**Comment by TimBlom** [comment]
Case 00534917

**Comment by RichardPerdaan** [comment]
From version 3.1.4-beta.2 of the MyParcel plugin and magento 2.3.3 this problem will no longer exist.
