### ISSUE TITLE
Combination of MyParcel and Postcode.nl (Hoofdfabriek) leads to incorrect adress

### ISSUE THREAD

**Issue by gerben86** [myparcelnl/magento#251]
Around 5% of my orders have this kind of adres (and aren't processed any further).
![myparcel-postcodenl](https://user-images.githubusercontent.com/17478858/54300317-ec2c3880-45bc-11e9-85f9-d196cf5f2db6.png)
This means that I'm loosing revues because the customer isn't send to Mollie.

There's not trace/error in the log (except in the mollie-log, because mollie doesn't accept this address).

This happens if the customer puts a space in the address (which happens quite often).

Do you know how this can be solved?

Versions:
Hoofdfabriek / Postcode.nl: 2.1.2
MyParcel: 2.4.2

**Comment by gerben86** [comment]
I heard that you're in contact with Hoofdfabriek, any estimation when it will be fixed?

**Comment by gerben86** [comment]
Any update on this?

**Comment by RichardPerdaan** [comment]
Yesterday I have released a[ new version](https://github.com/myparcelnl/magento/releases/tag/2.5.3-beta.1) that will provide better support to Hoofdfabriek. This problem must be solved with this version. If that is not the case, you can simply open the issue again.

**Comment by gerben86** [comment]
> Yesterday I have released a[ new version](https://github.com/myparcelnl/magento/releases/tag/2.5.3-beta.1) that will provide better support to Hoofdfabriek. This problem must be solved with this version. If that is not the case, you can simply open the issue again.

Thanks!
Only one noob-question left, how do I install a beta-version of a plugin via commandline?

**Comment by RichardPerdaan** [comment]
Hi @gerben86 ,

You can try to use the following commands:

- composer require myparcelnl/magento "2.5.3-beta.1" --update-with-dependencies
- rm -rf var/di/*; rm -rf pub/static/*; rm -rf var/cache/*; rm -rf var/pagecache/*; rm -rf var/generation/*; rm -rf var/dir/*; rm -rf var/view_preprocessed/*; php bin/magento cache:flush && php bin/magento setup:upgrade && php bin/magento setup:static-content:deploy && php bin/magento setup:static-content:deploy nl_NL && php bin/magento indexer:reindex

**Comment by gerben86** [comment]
@RichardPerdaan : thanks for your help!
The developer managed to get it working, but we're now running into a Javascript issue. Please see the printscreen (or check my shop, which I guess you're able to find):
![image](https://user-images.githubusercontent.com/17478858/57808887-b5ad9e00-7764-11e9-9def-7925233e908f.png)

**Comment by gerben86** [comment]
@RichardPerdaan : thanks for your reply, we gave it a try today but ran into this error:
![image](https://user-images.githubusercontent.com/17478858/57809505-dfb39000-7765-11e9-9862-2c600621cc4b.png)
![image](https://user-images.githubusercontent.com/17478858/57809937-ebec1d00-7766-11e9-9e07-85231b04e15f.png)
File: MyParcelNL_Magento/js/checkout/shipping_method/show-myparcel-shipping-method.js

This is because street.1 doesn't exist in my checkout, and that throws this error.
Replacing the method to be like street.2 solves the issue as far as I can see.

Could you have a look into this?

**Comment by gerben86** [comment]
@RichardPerdaan : are you able to have a look into this issue?

**Comment by RichardPerdaan** [comment]
@gerben86,

Currently there is a pull request open for this problem. As soon as it has been approved by several developers, I will process it in a new version.

**Comment by gerben86** [comment]
@RichardPerdaan : with version Version 2.5.3  this issue is returned:
![image](https://user-images.githubusercontent.com/17478858/59632384-6800c880-914a-11e9-9f51-dd2f669bbbb3.png)

Could you please advise how to fix this asap?
