### ISSUE TITLE
Shipping date field always populated with date

### ISSUE THREAD

**Issue by tbiest** [myparcelnl/magento#254]
When a customer does not select any shipping date in checkout, the standard shipping date is selected (shortest shipping date available). In this situation, the "shipping date" field in the backend is not populated. 

It would be helpful to populate this date so I always exactly know when to ship items as a store owner.

**Comment by Kroellie** [comment]
Added to this: we have disabled the date selector, and notice that sometimes the shipping date is filled in, and sometimes it is not.

**Comment by adem-demir** [comment]
00650001

**Comment by RichardPerdaan** [comment]
In version [4.0.0-beta.1] (https://github.com/myparcelnl/magento/releases/tag/4.0.0-beta.1) the functionality has been added
