### ISSUE TITLE
Class FitInMailboxOptions does not exists magento 2.3.1

### ISSUE THREAD

**Issue by koopjesboom** [myparcelnl/magento#256]
Best,

Edit a product in backend/admin panel results in a error after updating magento to 2.3.1
Class MyParcelNL\Magento\Model\Source\FitInMailboxOptions does not exist

Best regards

**Comment by RichardPerdaan** [comment]
Hi @koopjesboom,

Which version of the MyParcel plugin do you have? 
In the latest version ([2.5.0-beta.1](https://github.com/myparcelnl/magento/releases/tag/2.5.0-beta.1)) of the plugin there was  an adjustment to the mailbox options.

If you do not have this version, I would advise you to install this version.

**Comment by koopjesboom** [comment]
Best,

I have lower version.
Is it possible with composer to install this version?

Best regards

**Comment by RichardPerdaan** [comment]
Hi  @koopjesboom,

In the meantime this version is mark as stable, so you could use the following command to install version [2.5.0](https://github.com/myparcelnl/magento/releases/tag/2.5.0):

* `composer require myparcelnl/magento "~2.5.0"`
* `rm -rf var/di/*; rm -rf pub/static/*; rm -rf var/cache/*; rm -rf var/pagecache/*; rm -rf var/generation/*; rm -rf var/dir/*; rm -rf var/view_preprocessed/*; php bin/magento cache:flush && php bin/magento setup:upgrade && php bin/magento setup:static-content:deploy && php bin/magento setup:static-content:deploy nl_NL && php bin/magento indexer:reindex`

**Comment by koopjesboom** [comment]
Thank you very much problems solved.

**Comment by RichardPerdaan** [comment]
Good to hear that the problem has been solved. Therefore I will close the issue.
