### ISSUE TITLE
configHelper not used in Carrier

### ISSUE THREAD

**Issue by rikwillems** [myparcelnl/magento#267]
Model/Checkout/Carrier.php#L27
Model/Checkout/Carrier.php#L38
Model/Checkout/Carrier.php#L95
Model/Checkout/Carrier.php#L119

These lines mention the UPS config helper but it is not used in the class. Please remove as it adds a dependency on the UPS module. We remove this module but default.

**Comment by RichardPerdaan** [comment]
#300

**Comment by hostep** [comment]
This ticket needs to be reopened, because the UPS config helper was (probably?) accidentally re-added in https://github.com/myparcelnl/magento/commit/c5515f175709349a1c8e9b30f919ecb96c97a284#diff-ff2b20be47273c09a693c0cb6fafab82a4bac2675829b44c3a130406f7bef717

**Comment by RichardPerdaan** [comment]
Hi @rikwillems and @hostep ,
This problem has been resolved in version [4.1.6-RC.1 ](https://github.com/myparcelnl/magento/releases/tag/4.1.6-RC.1)of the MyParcel plugin.
