### ISSUE TITLE
Difference in prices home delivery and pickup location - tax issue

### ISSUE THREAD

**Issue by digikeijs** [myparcelnl/magento#273]
There is a difference in price calculation between a home delivery and a pickup location delivery. The pickup location price is showed as excluding tax amount. This should not be the case!

It should always show the including tax price, so in this example 7,08 is the correct price for both options

![Myparcel thuis](https://user-images.githubusercontent.com/34745091/57832127-2ed5e100-77b7-11e9-8b83-fcc541381ccb.PNG)
![Myparcel pickup](https://user-images.githubusercontent.com/34745091/57832129-2f6e7780-77b7-11e9-825e-df6dfeab4aa8.PNG)

**Comment by adem-demir** [comment]
tested in latest version no issues with taxes
