### ISSUE TITLE
Error when printing a label for "PostNL ophaallocatie"

### ISSUE THREAD

**Issue by gerben86** [myparcelnl/magento#276]
When a customer selected a pickup-location and we want to print the label we get the error as shown in the printscreen.
![IMG-20190524-WA0001](https://user-images.githubusercontent.com/17478858/58481447-ab27d700-815c-11e9-82f9-689798cd1e1f.jpg)
This causes that we're not able to deliver anything to a pickup location anymore.
We're using MyParcel-extension version which was adjusted for Postcode.nl/HoofdFabriek: https://github.com/myparcelnl/magento/issues/251

Could you have a look into this?
I added the report also to the attachments.
[1170846159480-report.txt](https://github.com/myparcelnl/magento/files/3227871/1170846159480-report.txt)

**Comment by gerben86** [comment]
@RichardPerdaan : did you have time to look into this? Because I'm still not able to print labels for Afhaallocaties.

**Comment by TimBlom** [comment]
Please update case 00579696 when the issue is fixed.

**Comment by RichardPerdaan** [comment]
@gerben86,

I have been able to look at this problem, unfortunately I have not succeeded in reproducing the problem. 

Which version of the MyParcel plugin and the MyParcel SDK do you use?

If this is the latest version, then I would like to have contact with you via mail. So that I can further investigate this on your (test) environment.

**Comment by gerben86** [comment]
@RichardPerdaan ,
This are the versions I'm using:
myparcelnl/magento: 2.5.3-beta.1
name: myparcelnl/sdk version: v2.0.7

**Comment by RichardPerdaan** [comment]
@gerben86 
Can you to install version 2.5.3-beta.3 of the MyParcel Magento 2 plugin?

**Comment by gerben86** [comment]
@RichardPerdaan :
myparcelnl/magento 2.5.3-beta.3 requires magento/product-community-edition 2.3.0, I'm using Magento CE 2.2.8, so beta.3 isn't an option.
Any other suggestions? Would like to have this fixed asap.

**Comment by RichardPerdaan** [comment]
Hi @gerben86,

Version 2.5.3 will no longer cause problems with the installation.
Would you like to try this version?

**Comment by gerben86** [comment]
@RichardPerdaan :
I installed the latest version, this is the result if the checkout-page is opened:
![image](https://user-images.githubusercontent.com/17478858/59632142-cd07ee80-9149-11e9-8de3-923d5f0d528f.png)

Are you aware of this issue and how can I solve it?
