### ISSUE TITLE
Integration Mageplaza OSC 2.8.1 / Myparcel 2.5.2 problem

### ISSUE THREAD

**Issue by Kroellie** [myparcelnl/magento#279]
During checkout with a guest account, selecting Belgium, the plugin doesn't refresh, and is only showing the default shipping method.

When logged in, doing the same order, the plugin does refresh, showing the possible pickup locations.

No javascript errors.

Magento 2.3.0, MyParcel 2.5.2, Mageplaza OSC 2.8.1

**Comment by Kroellie** [comment]
I've discovered this issue only occurs when changing the delivery country. When we change the country value, upon executing the javascript function _getFullStreet the value of window.mypa.address.street0 is undefined. I think a refresh of the window.mypa object is needed somewhere. Problem lies between Mageplaza OSC and MyParcel plugin.

**Comment by RichardPerdaan** [comment]
Problem is solved in version 3.1.4-beta.2 of the MyParcel plugin
