### ISSUE TITLE
Fire checkout Uncaught Error: Call to a member function setFinalPrice

### ISSUE THREAD

**Issue by soedesh** [myparcelnl/magento#284]
Fatal Error: 'Uncaught Error: Call to a member function setFinalPrice() on null in /home/bobstores/domains/test.bobstores.nl/public_html/vendor/magento/module-quote/Model/Quote/Item/AbstractItem.php:154↵Stack trace:↵#0 /home/bobstores/domains/test.bobstores.nl/public_html/vendor/myparcelnl/magento/Model/Sales/Repository/PackageRepository.php(267): Magento\Quote\Model\Quote\Item\AbstractItem->getProduct()↵#1 /home/bobstores/domains/test.bobstores.nl/public_html/vendor/myparcelnl/magento/Model/Sales/Repository/PackageRepository.php(215): MyParcelNL\Magento\Model\Sales\Repository\PackageRepository->getAttributesFromProduct('catalog_product...', Object(Magento\Quote\Model\Quote\Item\Interceptor), 'fit_in_mailbox')↵#2 /home/bobstores/domains/test.bobstores.nl/public_html/vendor/myparcelnl/magento/Model/Sales/Repository/PackageRepository.php(163): MyParcelNL\Magento\Model\Sales\Repository\PackageRepository->getAttributesFitInOptions(Object(Magento\Quote\Model\Quote\Item\Interceptor), 'fit_in_mailbox')↵#3 /home/bobstores/domains/' in '/home/bobstores/domains/test.bobstores.nl/public_html/vendor/magento/module-quote/Model/Quote/Item/AbstractItem.php' on line 154

Case 581209

**Comment by adem-demir** [comment]
fixed with latest version
