### ISSUE TITLE
Checkout laat extra vroeg pickup zien ondanks inactief in de plugin

### ISSUE THREAD

**Issue by soedesh** [myparcelnl/magento#289]
Wanneer de consument voor een pickup kiest, dan wordt zonder dat de optie voor early pickup actief is, wel getoond, en in rekening gebracht. Klant gebruikt versie 2.4.2, maar het probleem doet zich ook voor in 2.5.3

Case 587421

**Comment by RichardPerdaan** [comment]
case 627610

**Comment by adem-demir** [comment]
Wij kunnen hierbij melden dat deze optie niet meer mogelijk bij PostNL, waardoor het probleem ook gelijk is opgelost.

We zullen dan ook deze met eerst volgende update uit de plugin halen.
