### ISSUE TITLE
New feature: Editable text field for label kenmerk

### ISSUE THREAD

**Issue by bamboekeizer** [myparcelnl/magento#301]
By default the magento order id (increment_id) is added to the label as "kenmerk". One can edit this is the MyParcel backend, but this is extra, cumbersome work.
We would like to have a text field in the Magento admin for shipments creation that is prefilled with the order id, but where we can add or modify it to our desire.

**Comment by RichardPerdaan** [comment]
This functionality will be processed in the next version (#364 )

**Comment by RichardPerdaan** [comment]
There is a option added in version [3.3.0-beta.1](https://github.com/myparcelnl/magento/releases/tag/3.3.0-beta.1) where it is possible to use the following options for the label description :

- Order nummer
- Bezorgdatum
- Product nummer
- Product naam
- Hoeveelheid producten
- zelf geschreven tekst

It is also possible to combine them and show it together on the label.

**Comment by bamboekeizer** [comment]
Hi Richard, I did not see the possibility for a self written text on the label creation section of the create shipment screen?

**Comment by bamboekeizer** [comment]
I notice product information is not inserted for bundled products. Please mention restrictions like this in the user guide.
