### ISSUE TITLE
Composer issue and Error message on checkout while logged in to custommer account

### ISSUE THREAD

**Issue by koopjesboom** [myparcelnl/magento#303]
Best,

Magento2 version: 2.3.2
Myparcel versions tested 3.0.? and version 2.5.3.

Extra extension: Mageplaza One Step Checkout Latest stable version

**Composer**
When composer is used it does not install version 2.5.5 But 2.5.3 
Even when : composer require myparcelnl/magento:2.5.5 is used it installs version 2.5.3

composer update myparcelnl/magento Does not update to version 2.5.5 also.
While 2.5.5 is the latest stable version.

**Error**
However, After I login on my magento 2 shop there is a problem during checkout.
There is a error message:

Het opslaan van het adres is mislukt. Controleer het adres en probeer het opnieuw.
Trenslated: Saving the address failed. Check the address and try again.

**So step 1**
Create a account in magento 2
**Step 2**
Sign in with this account
**Step 3**
Add a product to the basket
**Step 4**
Checkout (while logged in)

Result:

**Het opslaan van het adres is mislukt. Controleer het adres en probeer het opnieuw.**
Trenslated: Saving the address failed. Check the address and try again.

**I have contacted Mageplaza And there explanation is:**

I disabled the MyParcelNL_Magento module and found that the issue does not occur on One Step Checkout and Magento's Default Checkout.  
As a result, the issue is due to the  MyParcelNL_Magento extension. Please contact MyParcelNL for better support.

At present, the module is still disabled, and you can see that the error does not exist anymore.

Is there a (known) solution for this?

**Comment by adem-demir** [comment]
case: 00642051

**Comment by RichardPerdaan** [comment]
Beste @koopjesboom,

Goed dat je dit heb geplaatst, dit was nog niet bij ons bekend. We gaan het onderzoeken en  zodra wij meer weten dan hoor je dat van ons.

**Comment by koopjesboom** [comment]
Geen Probleem. Ter aanvulling: Ik test elke week het bestelproces en na iedere verandering in mijn omgeving test ik heel magento 2 ook op werking. Te vaak gehad dat klanten verdwenen door fouten en problemen die mij nooit waren opgevallen. Klanten melden tevens nooit een probleem. Dit verwacht en vraag ik ook niet van de klant. Dit testen deed ik nooit met een aangemaakt Klant account maar als gast. Nu dus wel vandaar dat ik de melding kreeg. Hierna de module verwijderd met composer. Vervolgens de module weer geïnstalleerd en toen installeerde composer niet de laatste versie. Dus in het vervolg test ik alles ook met een Klant account.

**Comment by koopjesboom** [comment]
Beste, Ik werk op mijn ontwikkel omgeving maar ik kan mij voorstellen dat er mensen zijn die dit niet door hebben en hetzelfde probleem hebben op hun live server. Heeft u dit al kunnen reproduceren? 

![myparcel](https://user-images.githubusercontent.com/15247780/66116865-c3f53d00-e5d3-11e9-95cd-b1f35b4f1af8.png)

**Comment by koopjesboom** [comment]
Beste,

Ik wil morgen mijn project live zetten alleen de Myparcel module houd mij tegen.
Is er een quick fix voor de door mij aangedragen problemen van 9 dagen geleden?

Ik kan mijn webwinkel zo niet live zetten met dit probleem van de ingelogde klanten die niet kunnen afrekenen en zit hierdoor vast. Ik verneem graag van u.

Mvg.

**Comment by EnigmaWebdesign** [comment]
Hallo allemaal,

Ik kan inmiddels ook melden dat de update van MyParcel in Magento 2 niet goed gaat.
Daarnaast hebben wij ook problemen in de webshop met bestellingen die niet goed gaan.
Tevens zijn er problemen met Postcode checkout in combinatie met MyParcel.

Zover ik begrepen heb is MyParcel bezig om dit op te lossen en heeft men de hoogste prio gegeven om een oplossing te vinden.

Houd ons op de hoogte zodra dit allemaal opgelost is.

gr,

Stevan

**Comment by RichardPerdaan** [comment]
In versie [4.0.0-beta.1](https://github.com/myparcelnl/magento/releases/tag/4.0.0-beta.1) is dit probleem opgelost
