### ISSUE TITLE
Huisnummer/postcode combinatie niet bekend in de extensie, terwijl alle andere sites hem wel herkennen

### ISSUE THREAD

**Issue by gerben86** [myparcelnl/magento#307]
Ik heb een bestelling (via een ander kanaal) waarvan de postcode/huisnummer combinatie niet bekend wordt.
Postcode.nl kent hem wel, volgens de WOZ gegevens heeft deze combinatie al sinds 1850 een woonbestemming. 
Bia de backoffice van MyParcel kan ik ook een verzending aanmaken.
Alleen de MyParcel-extensie geeft een foutmelding:
![image](https://user-images.githubusercontent.com/17478858/66310134-b4476280-e90b-11e9-932c-67be338611eb.png)

Kunnen jullie hier z.s.m. naar kijken?
Op verzoek kan de postcode/huisnummer doorgeven.

**Comment by EdieLemoine** [comment]
Hi Gerben, bedankt voor je melding.

Om het probleem te vinden en vervolgens te verhelpen hebben we wel de postcode nodig. Als je die doorstuurt kunnen we ernaar kijken.

**Comment by gerben86** [comment]
Als je even een mail stuurt, stuur ik je de postcode en huisnummer toe.

**Comment by EdieLemoine** [comment]
We horen net dat iemand anders hetzelfde probleem heeft, we zijn het aan het uitzoeken. 

Je kunt de postcode/huisnummer naar edie@myparcel.nl mailen, ik laat je weten wanneer we een update hebben.

**Comment by reindert-vetter** [comment]
@gerben86 Je kan geen adressen ophalen in Noord Brabant en Belgie. PostNL heeft een storing. Ze nemen contact met ons op als ze het hebben opgelost.

**Comment by gerben86** [comment]
@reindert-vetter : Oke, dat is jammer...
Maar misschien zou het een mooie verbetering zijn om in dit geval dan toch een resillience scenario toe te voegen waarbij alleen bezorging aan huis geselecteerd kan worden als de MyParcel error code 3212 is?
Want nu kan de klant überhaupt zijn bestelling niet afronden...

Dit is de reply die ik van de MyParcel API ontvang:
`{"data":{"delivery":[],"pickup":[],"message":"No results"},"errors":[{"code":3212,"message":"Er zijn geen locaties gevonden die voldoen aan uw verzoek.","human":"Er zijn geen locaties gevonden die voldoen aan uw verzoek."}]}`

**Comment by EdieLemoine** [comment]
@gerben86 de PostNL storing is gistermiddag opgelost, het moet nu weer werken.

Wij kregen deze response van PostNL, die betekent dat de postcodecheck is gefaald. Gezien we in de versie die nu live staat één endpoint gebruiken om zowel pickup als delivery op te halen kunnen we niet een van de twee tonen als de andere is gefaald. 

We zijn echter hard bezig met een nieuwe oplossing voor de bezorgopties, die dit (toevallig) wel kan afvangen. We hebben nieuwe endpoints waardoor je bezorgen en afhalen niet meer in 1 call doet. Dus in het geval dat de pickup locaties request faalt zou je nog steeds thuis bezorgen kunnen selecteren, omdat die call niet zou falen in de situatie van deze storing.
