### ISSUE TITLE
Can't create labels when stock is 0 or last stock has been ordered

### ISSUE THREAD

**Issue by TeunSmit** [myparcelnl/magento#309]
When you have a product that has 0 stock or less you can't create a shipment label. Also when a customer orders the last product of the stock taking it from 1 to 0 then you also can't create a label.

If you add stock and then try to export it works.

**Comment by TeunSmit** [comment]
00653869

**Comment by wespiremedia** [comment]
This problem also occurs when a product is changed from enabled to disabled. Orders created when the product was still enabled can't be processed.

**Comment by gerben86** [comment]
When will this be picked up?

**Comment by adem-demir** [comment]
@gerben86 and @wespiremedia,

When I disable the MyParcel module I still get the same error. Do you've also this?

**Comment by adem-demir** [comment]
the solution what I found from magento is disable MSI

https://www.mexbs.com/magento-blog/disabling-the-magento-msi/

**Comment by wespiremedia** [comment]
@adem-demir But in case you'll need MSI, this of course isn't a solution.

**Comment by adem-demir** [comment]
@wespiremedia we've a feature request open for MSI.

https://github.com/myparcelnl/magento/issues/224
