### ISSUE TITLE
Overwriting the shipping-save-processor blocks other implementations in the checkout

### ISSUE THREAD

**Issue by duckchip** [myparcelnl/magento#311]
Hi guys,

We started using the myparcel module and we noticed that this module is not ready for integrations with other shipping modules that hook in the magento checkout.

The main problem is that this module [overwrites](https://github.com/myparcelnl/magento/blob/066e59880652d249482a96e0ec7fe5f151c401ed/view/frontend/requirejs-config.js#L10) the shipping-save-processor in the `require-js.config` file.

This blocks other implementations and should be avoided. 

In Magento 2.3.0, the payload-extender [got introduced. ](https://github.com/magento/magento2/commit/9fc22ff2fe2e0c62d75d00d8ce1d55207ea6462b#diff-6f15bee8297c1e4e27c4d32164904b80)

It would be a big improvement to the module if this could get implemented the correct way :) 

thanks in advance!

**Comment by RichardPerdaan** [comment]
Hi @duckchip,

Thank you for your feedback. We will look at it and as soon the improvement is done we will contact you.

**Comment by RichardPerdaan** [comment]
Hi @duckchip,

Your pull request has been processed in version [3.1.4-beta.1](https://github.com/myparcelnl/magento/releases/tag/3.1.4-beta.1) of the MyParcel plugin, thank you for your addition.
