### ISSUE TITLE
Combination of MyParcel and Postcode.nl (hoofdfabriek) leads to incorrect adres

### ISSUE THREAD

**Issue by gerben86** [myparcelnl/magento#323]
I have a couple of orders/week which get an incorrect adres:
![image](https://user-images.githubusercontent.com/17478858/68892812-0d34c280-0724-11ea-89cb-66d256038aa1.png)

This also means that the customer isn't able to pay and I'm losing revenue's.

Could you please have again a look on what's causing this issue?

**Comment by wwieskamp** [comment]
Howly cow. We've had this issue for serveral month's and had no way to reproduce this. You mentioned hoofdfabriek and tha'ts the EXACT combination we use! 

The hoofdfabriek extension is no longer mentioned at https://www.postcode.nl/services/adresdata/implementatie, they now only mention this one:

https://www.postcode-checkout.nl/index.php?core%5Bpage%5D=162&postcode-orders%5Bview%5D=step1

I implemented this and it looks like this works correct.

**Comment by gerben86** [comment]
@wwieskamp : Please let me know how it goes with this new extension (or could you ping me your site so I could check it?)!

I guess the issue could be reproduced by adding spaces after the postal code. By example: "9999 AA   " instead of "9999 AA".

**Comment by wwieskamp** [comment]
Mail me at w.wieskamp@crystalsoft.nl

**Comment by adem-demir** [comment]
Hi all,

Did you install the version with MyParcel compatibility? https://www.postcode-checkout.nl/plug-ins/standaard/magento2-myparcel. They made several changes in the plugin so they are compatible with us.

**Comment by gerben86** [comment]
This is the postcode-checkout extension, not the Hoofdfabriek extension.
The hoofdfabriek extension is discontinued as far as I see...

Unfortunately at postcode.nl they are not very stable with their
extension-suppliers...
Issue can be closed due to that.

Op do 9 jul. 2020 om 10:02 schreef Adem Demir <notifications@github.com>:
