### ISSUE TITLE
show-myparcel-shipping-method.js:149 Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by bamboekeizer** [myparcelnl/magento#333]
Add items to the card, can go to checkout page (onestepcheckout is enabled)

On Chrome, the following error is reported on loading the onestepcheckout page:, visible in the Inspect mode

show-myparcel-shipping-method.js:149 Uncaught TypeError: Cannot read property 'replace' of undefined
    at _setAddress (show-myparcel-shipping-method.js:149)
    at show-myparcel-shipping-method.js:83

The PostNL delivery is not loaded until I refresh the page 2 times and also change the quantity of a car item, but this might be related to onestepcheckeout?

Magento 2.3.3
Myparcelnl 3.1.3
Myparcelnl sdk 3.1.1

**Comment by ainigma32** [comment]
We are experiencing a similar problem. When checking out, the default method of PostNL is selected but when the user clicks Next the system displays an error: "The shipping method is missing. Select the shipping method and try again."

The console shows:

Uncaught TypeError: Cannot read property 'replace' of undefined
    at _setAddress (show-myparcel-shipping-method.min.js:14)
    at show-myparcel-shipping-method.min.js:6

When the user selects another option (e.g. pickup point) and then switches back to the standard delivery it is possible to advance to the next step but the shipping method in the checkout summary is not updated which leads to confusion.
The order shows the correct shipping information.

Magento 2.3.3
myparcelnl/magento 3.1.3
myparcelnl/sdk v3.1.1

**Comment by RichardPerdaan** [comment]
Hi @bamboekeizer and @ainigma32, 

It is indeed not nice that the message is visible in the Inspect. I will adjust that in one of the following versions. However, this will not cause any problems. I think the problems come from something else.

I would like to ask you to install [3.1.4-beta.2](https://github.com/myparcelnl/magento/releases/tag/3.1.4-beta.2). In this version I have made a number of adjustments to solve the problems.

**Comment by bamboekeizer** [comment]
The version resolves the 
 Uncaught TypeError: Cannot read property 'replace' of undefined
at _setAddress (show-myparcel-shipping-method.min.js:14)
at show-myparcel-shipping-method.min.js:6
Well done

**Comment by RichardPerdaan** [comment]
Good to hear, because it is resolved with version 3.1.4-beta.2 I will  close the issue.
