### ISSUE TITLE
recipient.company Must be at most 50 characters long

### ISSUE THREAD

**Issue by gerben86** [myparcelnl/magento#339]
**Describe the bug**
We had a customer with a company name of more then 50 chars. 
At that moment it isn't possbile to print a label:

`[2019-12-14 13:11:56] main.ERROR: Error in MyParcel API request: 0 - data.shipments[0].recipient.company Must be at most 50 characters long - Failed validation against JSON-SCHEMA shipment/post_shipments_request.json Url: https://api.myparcel.nl/shipments`

Suggested improvement: trim the length of the company-name before creating the request or fix it in the API itself.

I'm using version 2.5.3 on Magento 2.2.9

**Comment by RichardPerdaan** [comment]
Problem fixed in version [3.2.0-beta.1](https://github.com/myparcelnl/magento/releases/tag/3.2.0-beta.1)

**Comment by gerben86** [comment]
Bedankt!
Zou je deze oplossing ook kunnen toepassen om de Magento 2.2.x versies?

Alvast bedankt!

Op ma 20 jan. 2020 om 09:30 schreef Richard Perdaan <
notifications@github.com>:
