### ISSUE TITLE
Fatal error: Uncaught TypeError: strlen() expects parameter 1 to be string

### ISSUE THREAD

**Issue by magefan** [myparcelnl/magento#344]
Fatal error: Uncaught TypeError: strlen() expects parameter 1 to be string, null given in vendor/myparcelnl/sdk/src/Model/Consignment/AbstractConsignment.php:703 

It happens when street is just one word
https://prnt.sc/qf4bvq

We use
MyParcel Plugin version - 3.1.4-beta.2
MyParcel SDK version - v3.1.2-beta.1

**Comment by RichardPerdaan** [comment]
Hi @magefan,

Thank you for reporting

You will see a similar message in your system.log:
[2020-01-03 12:03:31] main.CRITICAL: An error has occurred while validating the address: Main road. Check number and number suffix.-MyParcelNL \ Sdk \ src \ Exception \ InvalidConsignmentException: Invalid full street supplied: Main road in /Applications/MAMP/htdocs/magento2/app/code/MyParcelNL/Sdk/src/Helper/SplitStreet.php:159

A label cannot be created if there is no house number.

I see that you have created two pull requests for this problem.
I have also opened two pull requests. I just think those are nicer solutions for this problem.
SDK: [#202](https://github.com/myparcelnl/sdk/pull/202)
Magento: [#349](https://github.com/myparcelnl/magento/pull/349)

You could try this code.

**Comment by RichardPerdaan** [comment]
Problem fixed in version [3.2.0-beta.1](https://github.com/myparcelnl/magento/releases/tag/3.2.0-beta.1)
