### ISSUE TITLE
Uncaught Error: Call to a member function getMyParcelConsignmentId() on null

### ISSUE THREAD

**Issue by gerben86** [myparcelnl/magento#345]
**Describe the bug**
When we want to create labels for multipe orders at once this error is thrown:

`2019/12/27 15:58:39 [error] 3813#0: *2131244 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getMyParcelConsignmentId() on null in /vendor/myparcelnl/magento/Model/Sales/MagentoOrderCollection.php:219
Stack trace:
#0 /vendor/myparcelnl/magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack.php(106): MyParcelNL\Magento\Model\Sales\MagentoOrderCollection->createMyParcelConcepts()
#1 /vendor/myparcelnl/magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack.php(59): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack->massAction()
#2 /vendor/magento/framework/App/Action/Action.php(107): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack->execute()
#3 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Obj" while reading response header from upstream, client: 77.163.113.239, server: mijnsite.nl, request: "GET /admin/myparcelnl/order/CreateAndPrintMyParcelTrack/key/8a674cbcb4d505aac006ac57aad155ffc6d0f2/?selected_ids=20898%2C20896%2C20895%2C20894%2C20893%2C20891&mypa_request_type=download&mypa_package_type=default&mypa_paper_size=A6&mypa_positions%5B%5D=2&mypa_positions%5B%5D=4&mypa_positions%5B%5D=1&mypa_positions%5B%5D=3 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php5-fpm-mywebshop.com.sock:", host: "www.mywebshop.com", referrer: "https://www.mywebshop.com/admin/sales/order/index/key/554195ed49ce62056cf5713de4c7e11f6d23cc5c0b99c/"
2019/12/27 15:59:14 [error] 3813#0: *2131244 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getMyParcelConsignmentId() on null in /vendor/myparcelnl/magento/Model/Sales/MagentoOrderCollection.php:219
Stack trace:
#0 /vendor/myparcelnl/magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack.php(106): MyParcelNL\Magento\Model\Sales\MagentoOrderCollection->createMyParcelConcepts()
#1 /vendor/myparcelnl/magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack.php(59): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack->massAction()
#2 /vendor/magento/framework/App/Action/Action.php(107): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack->execute()
#3 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Obj" while reading response header from upstream, client: 77.163.113.239, server: mijnsite.nl, request: "GET /admin/myparcelnl/order/CreateAndPrintMyParcelTrack/key/8a674cbcb4d505aac006ac57aad155ffc6d0f2/?selected_ids=20898%2C20896%2C20895%2C20894%2C20893%2C20891&mypa_request_type=download&mypa_package_type=default&mypa_paper_size=A6&mypa_positions%5B%5D=2&mypa_positions%5B%5D=4&mypa_positions%5B%5D=1&mypa_positions%5B%5D=3 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php5-fpm-mywebshop.com.sock:", host: "www.mywebshop.com", referrer: "https://www.mywebshop.com/admin/sales/order/index/key/554195ed49ce62056cf5713de4c7e11f6d23cc5c0b99c/"
`

**To Reproduce**
1. Select multiple orders
2. Create labels for them

**Expected behavior**
That we would be able to create and download the labels.

**Screenshots**
We get a blank page.

**Desktop (please complete the following information):**
 - MyParcel Plugin version: 2.5.3
 - MyParcel SDK version: 2.1.5
- Magento: 2.2.9

**Additional context**
Printing labels order by order works, but is time consuming

**Comment by gerben86** [comment]
@RichardPerdaan en @reindert-vetter : is some information about this available / is there an update? Because I get a lot of complaints about this.

**Comment by RichardPerdaan** [comment]
Hi @gerben86 ,

I think the cause of this problem has to do with the multiple consignments with the same reference id. In the file MagentoOrderCollection.php on line 216 can you see the following code:

`-> myParcelCollection-> getConsignmentByReferenceId ($ shipment-> getEntityId ());`

The `getConsignmentByReferenceId` method is only deprecated, precisely for this reason. If you change this to `getConsignmentByReferenceId` then I expect that the problem will be solved.

I would like to advise you to see if it is possible to go to the latest version ([3.2.0](https://github.com/myparcelnl/magento/releases/tag/3.2.0)) of the plugin. Because it is already solved here.

**Comment by gerben86** [comment]
Hi @RichardPerdaan ,

Thanks for your quick reply!
I'm still using the 2.5.X version (running on Magento 2.2.x). What should I change to get this fixed?
Could you refer to the commit/compare url so I can update the code for 2.5.x?

Thanks!

**Comment by RichardPerdaan** [comment]
The following was changed on 25 October: https://github.com/myparcelnl/magento/commit/8116873b497832f0b91491796b840abc89d3760b.

I hope this is the solution for you.

**Comment by RichardPerdaan** [comment]
The following was changed on 25 October 2019: https://github.com/myparcelnl/magento/commit/8116873b497832f0b91491796b840abc89d3760b.

Here is the adjustment that are made to solve this problem, among other things.

I hope this is the solution for you.

**Comment by gerben86** [comment]
@RichardPerdaan : I think that the M2.2 and M2.3 version aren't aligned enough to fix this by only this MR.
Because the Magento 2.2-version is lacking a lot of other changes which aren't mentioned in this commit.

Is there another workaround possible, like a null-check on the correct location?

**Comment by gerben86** [comment]
@RichardPerdaan : Do you know if there's another workaround possible, like a null-check on the correct location?

**Comment by RichardPerdaan** [comment]
Opgelost in [4.1.1](https://github.com/myparcelnl/magento/releases/tag/4.1.1)
