### ISSUE TITLE
Fatal error 500 on label creation without phone number

### ISSUE THREAD

**Issue by bamboekeizer** [myparcelnl/magento#348]
**Describe the bug**
When creating a label for an order an HTTP 500 is returned and the label is not created

**To Reproduce**
1. Go to an order that has no phone number, that is in processing
2. Select 'verzenden'
3. On the verzend page, create the label
4. HPP5 500 is returned and the lable is not created. See error apache log:
[Fri Jan 03 12:10:07.488973 2020] [lsapi:error] Backend fatal error: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to MyParcelNL\\Sdk\\src\\Model\\Consignment\\AbstractConsignment::setPhone() must be of the type string, null given, called in /home/whatever/staging/vendor/myparcelnl/magento/Model/Sales/TrackTraceHolder.php on line 173 and defined in /home/whatever/staging/vendor/myparcelnl/sdk/src/Model/Consignment/AbstractConsignment.php:1046\nStack trace:\n#0 /home/whatever/staging/vendor/myparcelnl/magento/Model/Sales/TrackTraceHolder.php(173): MyParcelNL\\Sdk\\src\\Model\\Consignment\\AbstractConsignment->setPhone(NULL)\n#1 /home/whatever/staging/vendor/myparcelnl/magento/Observer/NewShipment.php(102): MyParcelNL\\Magento\\Model\\Sales\\TrackTraceHolder->convertDataFromMagentoToApi(Object(Magento\\Sales\\Model\\Order\\Shipment\\Track), Array)\n#2 /home/whatever/staging/vendor/myparcelnl/magento/Observer in /home/whatever/staging/vendor/myparcelnl/sdk/src/Model/Consignment/AbstractConsignment.php on line 1046\n, referer: admin/order_shipment/new/order_id/563/key/43dd376a583056de38e7c426288e7fe9fe01d9996d4507cd891a7bb6c7bf6ce4/

The same result occurs when creating directly a label from the order overview page

**Expected behavior**
Label to be created

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - MyParcel 3.1.4-beta.2  (composer require myparcelnl/magento:"^3@beta")
and when downgraded to 3.1.3 (composer require myparcelnl/magento:"^3" ) the problem persists
sdk 3.1.1

**Comment by RichardPerdaan** [comment]
Best @bamboekeizer 

Thank you for reporting this issue. 
Monday is my colleague back from vacation and this is the first issue he will pick up.

The changes will be included in the next release.

**Comment by RichardPerdaan** [comment]
Next version of the [MyParcel SDK](https://github.com/myparcelnl/sdk/pull/203)

**Comment by tbiest** [comment]
I experience the same problem. We copy/paste the data manually in the Myparcel.nl backend until the fix can be implemented.

**Comment by RichardPerdaan** [comment]
Problem fixed in version [3.2.0-beta.1](https://github.com/myparcelnl/magento/releases/tag/3.2.0-beta.1)

**Comment by tbiest** [comment]
I tested the 3.2.0-beta 1 version in development environment. Unfortunately it persists:


Fatal error: Uncaught TypeError: Argument 1 passed to MyParcelNL\Sdk\src\Model\Consignment\AbstractConsignment::setPhone() must be of the type string, null given, called in /dev003/vendor/myparcelnl/magento/Model/Sales/TrackTraceHolder.php on line 174 and defined in /dev003/vendor/myparcelnl/sdk/src/Model/Consignment/AbstractConsignment.php:1086 Stack trace: #0 /dev003/vendor/myparcelnl/magento/Model/Sales/TrackTraceHolder.php(174): MyParcelNL\Sdk\src\Model\Consignment\AbstractConsignment->setPhone(NULL) #1 /dev003/vendor/myparcelnl/magento/Model/Sales/MagentoCollection.php(320): MyParcelNL\Magento\Model\Sales\TrackTraceHolder->convertDataFromMagentoToApi(Object(Magento\Sales\Model\Order\Shipment\Track), Array) #2 /dev003/vendor/myparcelnl/magento/Model/Sales/MagentoOrderCollection.php(172): MyParcelNL\Mag in /dev003/vendor/myparcelnl/sdk/src/Model/Consignment/AbstractConsignment.php on line 1086

version 3.2.0-beta.1 installed by composer

**Comment by RichardPerdaan** [comment]
Hi @tbiest ,

Did you also update the MyParcel SDK to v3.1.4-beta.1?

**Comment by tbiest** [comment]
Sorry for the confusion. I thought this was automatically done when updating the plugin with composer. It now works as expected thank you very much.
