### ISSUE TITLE
Uncaught type errors : cannot read property 'replace' and 'allowPickupPoints'

### ISSUE THREAD

**Issue by bamboekeizer** [myparcelnl/magento#358]
Google Chrome inspect reports these two errors:
![myparcel-errors](https://user-images.githubusercontent.com/28304222/73591753-fcaa1200-44f2-11ea-85e6-5ffbc4a4b094.png)

The PostNL pickup point selection only appears after changing the article count on the one step checkout page.

Chrome
 - MyParcel Plugin version 3.2.0
 - MyParcel SDK version 3.1.4

Using OneStepCheckout v2.9.1

**Comment by adem-demir** [comment]
fixed with latest version 4.1.1
