### ISSUE TITLE
bbp in checkout tonen met andere opties

### ISSUE THREAD

**Issue by soedesh** [myparcelnl/magento#361]
**Is your feature request related to a problem? Please describe.**
Deze optie was in het verleden al mogelijk, maar niet meer aanwezig in de laatste versies.

**Describe the solution you'd like**
Klant wilt graag dat bij een bbp tegen bijbetaling ook pakket gekozen kan worden

**Additional context**

![MA2_brievenbuspakje_instelling](https://user-images.githubusercontent.com/46486914/74154123-52c53680-4c12-11ea-87b7-782e3ac0c8be.png)

**Comment by RichardPerdaan** [comment]
In version [4.0.0-beta.1] (https://github.com/myparcelnl/magento/releases/tag/4.0.0-beta.1) the functionality has been added
