### ISSUE TITLE
Productnr and product count in label description

### ISSUE THREAD

**Issue by Nikitaverh** [myparcelnl/magento#367]
**Is your feature request related to a problem? Please describe.**
The productnr and count was always shown on the label, but not anymore since the latest upgrade 

**Describe the solution you'd like**
Please make it possible to show the prodnr and count, like it was before

**Comment by Nikitaverh** [comment]
00717577

**Comment by RichardPerdaan** [comment]
There is a option added in version [3.3.0-beta.1](https://github.com/myparcelnl/magento/releases/tag/3.3.0-beta.1) where you select the options for the label description :

- Order nummer
- Bezorgdatum
- Product nummer
- Product naam
- Hoeveelheid producten
- zelf geschreven tekst
