### ISSUE TITLE
Onjuiste verzendkosten bij verzenden naar Belgie (table rate tabel)

### ISSUE THREAD

**Issue by michel334** [myparcelnl/magento#371]
We hebben een Nederlandse shop met onderstaande table rate verzendkosten tabel

Land,Provincie,Postcode,"Gewicht (en daarboven)",Verzendkosten
BEL,*,*,0.0000,9.5000
BEL,*,*,1000.0000,19.5000
NLD,*,*,0.0000,4.2500
NLD,*,*,1.0000,8.5000
NLD,*,*,1000.0000,14.9000

Bij verzenden naar Belgie pakt MyParcel de Nederlandse verzendkosten uit de table rate tabel, in plaats van de Belgische verzendkosten. Zie screenshot

OS: Windows
Browser chrome
MyParcel Plugin version : 3.2.1
MyParcel SDK version: 3.1.6
Magento versie: Magento ver. 2.3.2

![onjuiste-verzendkosten-belgie](https://user-images.githubusercontent.com/6500172/76001184-01545280-5f05-11ea-8447-b03bf6d51b5d.jpg)

**Comment by Kroellie** [comment]
Ik gebruik ook tablerate icm myparcel en ervaar geen problemen. Kan het zijn omdat je de landcode verkeerd hebt staan in je tablerate tabel? Ik heb namelijk NL en BE.

**Comment by michel334** [comment]
@Kroellie Bedankt voor het meedenken. Ik heb de NL en BE landcode zojuist geprobeerd, maar voor ons maakt het geen verschil. We zien wel voor Belgie in eerste instantie het juiste verzendbedrag staan, daarna volgt een refresh en worden de MyParcel verzendmethodes ingeladen met het onjuiste bedrag (van NL) zoals in het screenshot.. 

Ik lees dat zowel 2, als 3 letter landcodes zijn toegestaan bij Magento:
https://xoons.co.uk/magento2-table-rates-country-codes/

**Comment by Kroellie** [comment]
Ik had je opmerking over de refresh over het hoofd gezien. De standaard table_rate klopt wel, maar na de refresh inderdaad wordt het NL tarief getoond.

+1 dus

**Comment by Kroellie** [comment]
Het lijkt zich wel te herstellen als ik na het zien van het tarief van NL met landkeuze op Belgie, de postcode aanpas. Na deze refresh is het tarief weer goed...?

**Comment by michel334** [comment]
@Kroellie  Zowel op onze live- als testomgeving gaat het na de verzendkosten refresh helaas toch fout. Ook na aanpassen postcode etc. Dit is onze testomgeving:
http://retro-deurbeslag.michelwebdesign.nl/
We zien op onze live webshop Belgische klanten die afrekenen met de verkeerde (Nederlandse) verzendkosten. Maar bedankt voor het meedenken!

**Comment by RichardPerdaan** [comment]
Beste @michel334 met de laatste beta versie zal dit opgelost gaan worden.

**Comment by RichardPerdaan** [comment]
In versie [4.0.0-beta.1](https://github.com/myparcelnl/magento/releases/tag/4.0.0-beta.1) is dit probleem opgelost
