### ISSUE TITLE
 Past in brievenbuspakje toont onjuiste waarde in Backend

### ISSUE THREAD

**Issue by michel334** [myparcelnl/magento#375]
Na update van MyParcel versie 3.0.3 naar versie 3.2.1 (sdk naar v3.1.7) toont veld "Past in brievenbuspakje" bij wijzigen product altijd "Kijk naar het gewicht" in plaats van de database waarde zoals "3 producten 33%"

Enkele andere zaken die me opvielen:
Het veld "Past in brievenbuspakje" is ook verplaatst van tab "MyParcel Opties " naar de hoofdpagina bij het aanpassen van een product in de Magento beheeromgeving. Ik weet niet of dat de bedoeling is?
Daarnaast is dit veld "Past in brievenbuspakje" nu geen filteroptie meer in het productenoverzicht

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser chrome
 - MyParcel Plugin version : 3.2.1
 - MyParcel SDK version: v3.1.7

Dit was de situatie voor de update:
![myparcel-voor-de-update](https://user-images.githubusercontent.com/6500172/76307643-822a9a00-62c9-11ea-962a-b60f9158064d.jpg)

Situatie na de update:
![myparcel-kijk-naar-het-gewicht](https://user-images.githubusercontent.com/6500172/76307662-8bb40200-62c9-11ea-8588-fd1e405658a4.jpg)

**Comment by RichardPerdaan** [comment]
Beste @michel334 met de laatste beta versie zal dit opgelost gaan worden.

**Comment by RichardPerdaan** [comment]
In versie [4.0.0-beta.1](https://github.com/myparcelnl/magento/releases/tag/4.0.0-beta.1) is dit probleem opgelost
