### ISSUE TITLE
Dubbele waardes bij verzendmethodes brievenbuspakje

### ISSUE THREAD

**Issue by michel334** [myparcelnl/magento#376]
In het geval van een product dat is ingericht als een brievenbuspakketje zien we 2 keer brievenbuspakje staan als verzendmethode, zie screenshot

OS: WIndows 10
Browser chrome
MyParcel Plugin version : 3.2.1
MyParcel SDK version: v3.1.7

![myparcel-na-update-321-dubbel-brievenbus](https://user-images.githubusercontent.com/6500172/76307976-24e31880-62ca-11ea-9b1c-53f38c36d839.jpg)

**Comment by aqdennis** [comment]
Inderdaad, dat heb ik ook!  Om er zeker van te zijn dat het écht 2x dezelfde is heb ik 'm even een onzinnaam gegeven, maar inderdaad wordt het brievenbuspakketje 2x afgebeeld. Als je één van de 2 selecteert worden beide radiobuttons geselecteerd.

![image](https://user-images.githubusercontent.com/48013601/79204860-818fa100-7e3d-11ea-9732-8c7ac6da03a2.png)

**Comment by michel334** [comment]
@aqdennis  Bedankt voor je  reactie. MyParcel reageert verder niet meer dus we komen niet veel verder met de issues die we hebben. De meeste van mijn klanten gaan over naar de TIG Magento 2 plugin voor PostNL. Bevalt prima :)

**Comment by adem-demir** [comment]
Goedemiddag. We zijn op dit moment bezig met deze issue van dubbel verzendmethode. Wij zullen jullie op de hoogte brengen wanneer we het opgelst hebben.

**Comment by michel334** [comment]
is het al opgelst?

**Comment by adem-demir** [comment]
Beste @michel334 met de laatste beta versie is dit opgelost.

**Comment by michel334** [comment]
Beste @adem-demir, ok bedankt. Ik zal dan even wachten tot de versie uit beta is.

**Comment by RichardPerdaan** [comment]
In versie [4.0.0-beta.1](https://github.com/myparcelnl/magento/releases/tag/4.0.0-beta.1) is dit probleem opgelost
