### ISSUE TITLE
Geen verzendmethode bij brievenbuspakje Belgie

### ISSUE THREAD

**Issue by michel334** [myparcelnl/magento#377]
Als ik een product probeer af te rekenen met verzending naar Belgie, waarbij het product is ingericht als een brievenbuspakje, dan zien we geen verzendmethodes. Het afrekenen blokkeert, zie screenshot

OS: WIndows 10
Browser chrome
MyParcel Plugin version : 3.2.1 (ging ook al fout in 3.0.2)
MyParcel SDK version: v3.1.7

![myparcel-na-update-321-belgie-geen-verzendmethode](https://user-images.githubusercontent.com/6500172/76308271-b3579a00-62ca-11ea-8c9e-7c6274b97482.jpg)

**Comment by RichardPerdaan** [comment]
Beste @michel334 met de laatste beta versie zal dit opgelost gaan worden.

**Comment by michel334** [comment]
Dit gaat nog steeds fout in de laatste beta versie 3.3.0-beta.1
De overige bugs gaan ook gewoon nog fout.
Als je wil heb ik een testomgeving.

**Comment by RichardPerdaan** [comment]
In versie [4.0.0-beta.1](https://github.com/myparcelnl/magento/releases/tag/4.0.0-beta.1) is dit probleem opgelost
