### ISSUE TITLE
street_additional_info error in Magento 2

### ISSUE THREAD

**Issue by soedesh** [myparcelnl/magento#381]
When I use this line to add extra info and try to print the shipping label, I get this error:

**_An error has occurred while validating the address: adriaan brouwerstraat 16 bus 4 achter graag. Check number and number suffix._** 

With only suffix there is no problem to print the label

Case: 666751
plgn version 3.2.1

**Comment by RichardPerdaan** [comment]
This issue is resolved in version [4.0.0-beta.1] (https://github.com/myparceln/magento/releases/tag/4.0.0-beta.1)
