### ISSUE TITLE
Verzendmethode tabel frontend heeft onjuiste kolomheaders

### ISSUE THREAD

**Issue by aqdennis** [myparcelnl/magento#389]
**Describe the bug**
In de frontend in de tabel met beschikbare verzendmethodes heeft de header de kolommen "Selecteer methode", "Prijs", "Titel methode" en "Titel vervoerder" terwijl de tabel alleen de methodes en de prijs toont. 

**To Reproduce**
Plugin versie 2.5.8 geinstalleerd op Magento 2.3.2. Toen had ik reeds het probleem. 
Plugin geupdate naar 3.0.3 en het probleem bestaat nog steeds.  

**Expected behavior**
Ik zou slechts 2 kolomheaders verwachten "Selecteer methode" en "Prijs" 

**Screenshots**
![image](https://user-images.githubusercontent.com/48013601/79003289-9379f700-7b52-11ea-97fa-2417bf03308b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome & Edge
 - MyParcel Plugin version 3.0.3
 - MyParcel SDK version 2.1

**Additional context**
Ik gebruik een custom theme

**Comment by RichardPerdaan** [comment]
In versie [4.0.0-beta.1](https://github.com/myparcelnl/magento/releases/tag/4.0.0-beta.1) is dit probleem opgelost
