### ISSUE TITLE
Toevoeging maximaal 4 tekens

### ISSUE THREAD

**Issue by reindert-vetter** [myparcelnl/magento#39]
Toevoeging mag maximaal 4 tekens bevatten. Toevoegingen mag als volgt ingekort worden:

gedempte - GED 
noord - N
groot, grote, greate - GRT 
noordzijde - NZ
hoog, hoge, hege - HG 
oost - O
klein(e) - KL 
oostzijde - OZ
kort(e), koart(e) - K 
verlengde - VERL
krom(me) - KR 
west - W
laag, lage, lege - LG 
westzijde - WZ
lang(e) - L 
zuid - Z
nieuw(e) - NW 
zuidzijde - ZZ

**Comment by RichardPerdaan** [comment]
Hier krijgen wij geen vragen over. Mochten deze vragen toch komen dan kunnen we de issue altijd weer openen.
