### ISSUE TITLE
Shipment email geeft geen track & trace code weer

### ISSUE THREAD

**Issue by aqdennis** [myparcelnl/magento#390]
**Describe the bug**
In mijn shipment email wil ik de track & trace code (met link) weergeven. Ik daarom in de e-mail  template de code {{var tracktrace_url}} opgenomen zoals in de handleiding beschreven staat.
Echter, in de shipment e-mail blijft de track & trace code leeg.

**To Reproduce**
1. Volg de procedure zoals beschreven in de Magento 2 plugin handleiding
2. Vanuit de backend make een shipment, maak labels en verstuur shipment e-mail

**Expected behavior**
Shipment e-mail zou track & trace code met link naar URL moeten bevatten.

**Desktop (please complete the following information):**
 - OS: Windows 10 [e.g. iOS]
 - Browser: Chrome 
 - MyParcel Plugin version 3.2.1
 - MyParcel SDK version 3.1.7

**Comment by Kroellie** [comment]
Ik had hetzelfde probleem met een custom email template in M2.3.4. In de tabel 'email_template' heb ik de bewuste template op 'is_legacy' op 1 gezet, en toen verscheen de T&T code.

**Comment by RichardPerdaan** [comment]
Beste @aqdennis en @Kroellie,

Vanmorgen is er een nieuwe versie ([3.3.0-beta.1](https://github.com/myparcelnl/magento/releases/tag/3.3.0-beta.1)) van de plugin live gezet.  
In deze versie zijn er meerdere verbeteringen en uitbreidingen gemaakt. Waaronder `Add myparcel.me track & trace urls to shipping emails`. 

Mocht je deze versie willen testen dan kan dat natuurlijk altijd.

Voor nu sluit ik dan ook de issue. Mocht het probleem nog steeds aanwezig zijn met deze versie dan kan je de issue altijd weer opnieuw openen.
