### ISSUE TITLE
Brievenbuspakketje met pakketopties toont alleen brievenbuspakketje

### ISSUE THREAD

**Issue by aqdennis** [myparcelnl/magento#391]
**Describe the bug**
Ik heb wil voor kleine zendingen de klant de optie bieden om het hetzij met een brievenbuspakketje hetzij met een gewone pakketzending te versturen. Echter, voor kleine pakketjes wordt alleen de brievenbuspakket optie getoond in de frontend.

**To Reproduce**
1. In de backend Stores -> Configuration -> MyParcel -> Checkout settings -> Mailbox settings zet "Automate Mailbox" op Yes en "Mailbox with other option" ook op "Yes"
2. Zet de Mailbox weight op bv 500 
2. Maak in de frontend een bestellling aan met een gewicht minder dan 500 en ga in de one-page-checkout naar verzenden.  Er wordt nu alleen "Brievenbuspakketje" als optie getoond.

**Expected behavior**
I zou verwachten dat gezien de instellingen ik zowel "Brievenbuspakketje" als het hele blokje voor een normale pakketbezorging te zien zou krijgen in de frontend.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - MyParcel plugin version 3.2.1
 - MyParcel SDK version 3.1.7

**Comment by adem-demir** [comment]
https://github.com/myparcelnl/magento/releases/tag/4.1.1
