### ISSUE TITLE
Problem create shipment for order to CH (non-eu)

### ISSUE THREAD

**Issue by SpikeSpade** [myparcelnl/magento#397]
**Describe the bug**
When trying to create a shipment from an order which is towards a non-eu country (Switserland CH in our case), then we get this error:
main.CRITICAL: Product data must be set for international MyParcel shipments. Use addItem(). {"exception":"[object] (MyParcelNL\\Sdk\\src\\Exception\\MissingFieldException(code: 0): Product data must be set for international MyParcel shipments. Use addItem(). at /var/www/vhosts/development/drempelhulpen_com/vendor/myparcelnl/sdk/src/Services/ConsignmentEncode.php:292)"} []

**To Reproduce**
1. Login to Magento backend and go to Sales -> Orders
2. Open an order with destination 'Switserland' 
3. Click on 'Ship' to go to the 'New Shipment' page
4. Scroll down and check 'Create MyParcel consignment' and select 'Package'
5. Click on 'Submit Shipment'

**Expected behavior**
A shipment should be created..

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox Developer edition
 - MyParcel Plugin version: 3.2.1
 - MyParcel SDK version: 3.1.7

**Additional context**
When trying to debug the problem I noticed this:
The function convertDataForCdCountry() (MyParcel/Magento/Model/Sales/TrackTraceHolder.php)
it tries to get the products using this line:
$products = $this->getItemsCollectionByShipmentId($magentoTrack->getShipment()->getId());
However the getItemsCollectionByShipmentId tries to get the products from the database, while the shipment at this point isn't in the database yet.

It would be possible for fill the $myParcelProduct variable in the upcoming foreach by using:
$magentoTrack->getShipment()->getItems().

These items contain all the required information

**Comment by tramov** [comment]
@SpikeSpade I just ran into the same problem. Does 

> It would be possible for fill the $myParcelProduct variable in the upcoming foreach by using:
> $magentoTrack->getShipment()->getItems().

Did modifying the code with this solve your problem?

**Comment by SpikeSpade** [comment]
Together with 2 small typecastings removed, it fixed my issue.

I've created a pullrequest with the changes:
https://github.com/myparcelnl/magento/pull/402

Note: all the products in the new shipment required a HS_Code and no more then 5 types of products where allowed to be in the shipment. (the validation messages didn't notify this very clearly)

**Comment by RichardPerdaan** [comment]
Hi SpikeSpade and tramov,

Thank you for reporting this issue and making the pull request. Today I will look at the pull request.

**Comment by adem-demir** [comment]
solution in https://github.com/myparcelnl/magento/pull/445
