### ISSUE TITLE
 Not all of your products are available in the requested quantity

### ISSUE THREAD

**Issue by atty31** [myparcelnl/magento#399]
**Describe the bug**
When shipments are created in Magento (vers 2.3.4) from the adminpanel the error message is displayed after the submit: " Not all of your products are available in the requested quantity"

**To Reproduce**
1. Create an order
2. Make sure that for one of the item the qty from the advanced inventory is 0
3. Try to create a shipment 
4. Make sure that backorders can be placed

**Expected behavior**
A shipment is created 

**Screenshots**
![Screenshot (68)](https://user-images.githubusercontent.com/3530315/80498438-02858700-896c-11ea-96d9-82110cda4be8.png)

**Additional context**
 - MyParcel Plugin version: 3.2.1
 - MyParcel SDK version : 3.1.4

Error message being logged:
`{"report_id":"72e1ebf83e78ab2f6abf8ef9f7958156e85e2d6739bb73c62bfeb651738c8089","exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): Not all of your products are available in the requested quantity. at /path/to/vendor/myparcelnl/magento/Model/Sales/MagentoOrderCollection.php:373)"}`

**Comment by RichardPerdaan** [comment]
Hi @atty31 ,
Are you still experiencing this problem?
I would like to help you further.

**Comment by atty31** [comment]
Srry @RichardPerdaan , but I 've raised this issue 2 years ago, I don't even remember what was about it :) .

**Comment by RichardPerdaan** [comment]
No problem @atty31 , for now I will close the issue. 
When the issue happens again, we can reopened the issue.
