### ISSUE TITLE
Shipment creation failure for 3.3.0-beta.1 in magento 2.3.3

### ISSUE THREAD

**Issue by bamboekeizer** [myparcelnl/magento#400]
Shipments cannot be created for orders

1. Create an order
2. View order and select "Create shipment"
3. Submit the create shipment form
4. See error notification: Shipment cannot be saved
5. Shipment is not created in magento nor Myparcel backend

**Expected behavior**
Shipment created

**Screenshots**
Exception log shows:
CRITICAL: Notice: Undefined offset: 0 in /vendor/myparcelnl/magento/Model/Sales/TrackTraceHolder.php on line 275 {"exception":"[object] (Exception(code: 0): Notice: Undefined offset: 0 in /vendor/myparcelnl/magento/Model/Sales/TrackTraceHolder.php on line 275 at /vendor/magento/framework/App/ErrorHandler.php:61)"} []

**Desktop (please complete the following information):**
3.3.0-beta.1 in magento 2.3.3
sdk 3.1.7

**Comment by RichardPerdaan** [comment]
This issue is resolved in version [4.0.0-beta.1] (https://github.com/myparceln/magento/releases/tag/4.0.0-beta.1)
