### ISSUE TITLE
Bug: Bulk Actions> 'Print labels directly' always prints package label 

### ISSUE THREAD

**Issue by Nikitaverh** [myparcelnl/magento#403]
When print labels directly is chosen to bulk print order, it always creates a package label, even when it should be a digital stamp or mailbox label

https://we.tl/t-p4Psj9Pccr - screenvid

**Comment by Nikitaverh** [comment]
00734362

**Comment by adem-demir** [comment]
https://github.com/myparcelnl/magento/pull/446

**Comment by RichardPerdaan** [comment]
fixed in the new version

**Comment by Kroellie** [comment]
@RichardPerdaan This was my bug report, I'm running 3.3.0 and not looking forward to installing v4 any time soon. Can you assist in a patch for my version?
