### ISSUE TITLE
Bulk Action "Print MyParcel labels" geeft onjuiste foutmelding

### ISSUE THREAD

**Issue by aqdennis** [myparcelnl/magento#404]
**Describe the bug**
I deed een bulk actie op 2 orders om de labels te printen. Ik krijg de keus op welke labels ik wil printen en als ik dan de "download" optie kies krijgt ik de foutmelding "Cannot create shipment for orders that are On Hold or digital", maar de order is niet On Hold (hij is Payment Received) en ook niet digitaal.
Sterker nog, de Shipments zijn gewoon aangemaakt, en als ik inlog bij MyParcel zie ik dat de zendingen ook gewoon zijn aangemaakt.  Het enige wat dus niet gebeurd is is het donwloaden van de labels....

**To Reproduce**
1. Ga naar orders. Selecteer er 2
2. Kies uit de actielijst "PRint MyParcel labels"
3. Kies gewenste layout in de popup en download de labels

**Expected behavior**
Ik zou verwachten dat ik de labels kan zien in hetzij de browser of dat ik een filerequester krijg waar ik ze wil bewaren.

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Magento 2.3.2
 - MyParcel Plugin 3.2.1
 - MyParcel SDK 3.1.7

**Additional context**
MyParcel checkout is disabled aangezien daar nog te veel grafische issues zijn - ik gebruik tablerates.

**Comment by AlexNauta** [comment]
Heb je toevallig een same invoice/ordernumber plugin draaien? Dit gaf bij ons problemen i.c.m. de Myparcel plugin

**Comment by aqdennis** [comment]
Dat heb ik inderdaad! Maar ja...daar wil ik ook niet echt vanaf ...

**Comment by AlexNauta** [comment]
Grote kans dat de combinatie met die plugin het dan kan zijn, ik had het een paar maanden geleden al gevonden bij een klant en gemeld bij Myparcel. Hoop dat ze het gaan fixen.

**Comment by Kroellie** [comment]
Wij zitten op magento 2.3.5-p1 met MyPa 3.2.1 en bss custom order plugin, en ik ervaar geen problemen met bulk printen.

**Comment by aqdennis** [comment]
Tja, de ene plugin is de andere niet. Ik gebruik "Fooman - Same order invoice number" ...

Wat ook wel irritant is dat als je dan een tweede keer probeert te printen dus ook voor de 2e keer een zending wordt aangemaakt ipv dat een 2e poging wordt gedaan om de labels te  downloaden. Maar da's een ander issue :)

**Comment by Calypso971** [comment]
Hier (M2.3.4) werkt de Same order invoice number plugin van Fooman op zich naar behoren, maar ik had wel een ander vreemd probleem met het downloaden van het verzendlabel; ik kreeg een halve pagina HTML te zien, maar het label werd niet gegenereerd.

Bleek te gaan om oude e-mail templates in het thema wat ik gebruikte; bleek na testen met Luma dat het namelijk allemaal wel werkte. Toen ook nog bleek dat eenmaal aangemaakte labels wel gewoon gedownload werden in m'n eigenlijke thema kwam ik uiteindelijk (heeft me toch een dag gekost) uit op de e-mail templates die verouderd waren. Deze vervangen en alles werkt naar behoren. Het hoeft helemaal niks met de hier gemelde problemen met Fooman o.i.d. te maken te hebben, maar het kan geen kwaad om even te testen; hetzij door terug te schakelen naar een standaard template, hetzij door even de templates te vervangen in je thema.

**Comment by adem-demir** [comment]
Hi,

Wij hebben dit getest met de laatste versie van ons en Magento en zien hier geen problemen in. Als het e.v.t. een conflict is met een andere plugin moeten we daar een "compability request" doen. Graag hoor ik van jullie..

Adem
