### ISSUE TITLE
Aflevering staat op volgende dag,  zelfs als MyParcel checkout niet wordt gebruikt

### ISSUE THREAD

**Issue by aqdennis** [myparcelnl/magento#405]
**Describe the bug**
We willen de klant niet laten kiezen op welk tijdstip hij zijn pakketje kan ontvangen omdat gezien de aard van wat wij leveren we dat niet kunnen garanderen. Maar die mogelijkheid blijkt niet te bestaan, je moet blijkbaar altijd een afleverdatum opgeven.
We hebben nu de hele MyParcel checkout uit staan en zelfs dan als we via de backend een label aanmaken staat aflevering op de volgende dag. Dat zou niet moeten .... als de klant niet specifiek kiest voor een afleverdatum (hetzij omdat hij dat niet wil, hetzij omdat de webshop die optie niet biedt) dan zou de optie van afleverdatum gewoon leeg moeten zijn.

**To Reproduce**
1.  Maar een pakketlabel aan via de backend.

**Expected behavior**
Geen gekozen bezorgdatum

**Screenshots**
De eerste 2 pakketjes zijn aangemaakt via de backend en hebben een "gekozen bezorgdatum" terwijl er helemaal niks gekozen is op enig moment.  De volgende 2 pakketjes zijn aangemaakt rechstreeks in de dashboard. Deze hebben geen gekozen bezorgdatum....

![image](https://user-images.githubusercontent.com/48013601/80965329-9f37a100-8e12-11ea-9de9-69fe5ec34726.png)

**Desktop (please complete the following information):**
 -   Windows 10
 -   Chrome
 -   Magento 2.3.2
 -   MyParcel Plugin 3.2.1
 -   MyParcel SDK 3.1.7

**Comment by RichardPerdaan** [comment]
Fixed in [4.1.2](https://github.com/myparcelnl/magento/releases/tag/4.1.2) of the MyParcel Magento 2 plugin
