### ISSUE TITLE
Postzegel werkt niet

### ISSUE THREAD

**Issue by michel334** [myparcelnl/magento#409]
**Describe the bug**
Postzegel werkt niet. Bedrag is altijd 0 euro.

OS: Win 10
Chrome
MyParcel 3.2.1
SDK: v3.1.7
Magento v2.3.4

**Comment by RichardPerdaan** [comment]
Beste @michel334 ,

Het is mogelijk om in de instellingen van MyParcel aan te geven wat het bedrag is voor de digitale postzegel.

Dit kan je doen onder 
`stores -> configuration -> MyParcel -> checkout instellingen -> digital stamp settings `

Ik heb dit meerdere malen op een vanilla Magento omgeving getest en ik zie daar geen problemen. Mocht de bovenstaande stappen niet werken dan kan je altijd contact met ons opnemen via de telefoon 0233030315 of mail support@myparcel.nl.

**Comment by michel334** [comment]
Beste @RichardPerdaan
Bovenstaande is mij bekend. De issue is de default waarde van het bedrag bij de digitale postzegel. Die staat direct na installatie van MyParcel op 0,91 (met een komma)
Magento accepteert echter alleen punten als decimale scheidingsteken. Als ik het bedrag aanpas naar 0.91 dan werkt de digitale postzegel wel goed. 
Alle andere bedragen bij MyParcel zijn standaard wel met een punt.
Dit soort issues kosten mij gruwelijk veel tijd :) Tijd die ik helaas moet doorbelasten naar mijn klanten die MyParcel gebruiken.

**Comment by RichardPerdaan** [comment]
In versie [4.0.0-beta.1](https://github.com/myparcelnl/magento/releases/tag/4.0.0-beta.1) is dit probleem opgelost
