### ISSUE TITLE
Huur een tester in / niet de programmeur laten testen

### ISSUE THREAD

**Issue by michel334** [myparcelnl/magento#411]
De meeste fouten zijn binnen 5 minuten te vinden op een vanilla Magento installatie

**Comment by RichardPerdaan** [comment]
Beste @michel334 ,

Momenteel hebben wij twee testers die alle code van MyParcel test. Voordat de testers ernaar kunnen kijken heeft de developer de plugin al volledig getest. Zodra er een heel test protocol is afgerond zal de plugin pas beschikbaar zijn.

Daarnaast zijn al onze testen op een vanilla Magento installatie.
