### ISSUE TITLE
No error shown to the user in case of error 'This address can not be split'

### ISSUE THREAD

**Issue by gerben86** [myparcelnl/magento#412]
**Describe the bug**
There's no error message thrown to the user when this error appears in the log:
```[2020-05-14 15:06:28] main.CRITICAL: Error in MyParcel API request: 3731 -  - This address can not be split. Please check address:```

**To Reproduce**
1. Create an order with a Belgium delivery adress where the housnumber is something like '1a1'
2. Generate a shippinglabel for this order

**Expected behavior**
I'd expect that a label is generated or a readable error is shown to the user so the user can update the delivery address.

**Actual behavior**
There's no error shown and also no label generated. So the user doesn't know what happend.
When I read the logs I see this error:
```[2020-05-14 15:06:28] main.CRITICAL: Error in MyParcel API request: 3731 -  - This address can not be split. Please check address: streetname 1 a1 Url: https://api.myparcel.nl/shipments Request: {"data":{"shipments":[{"recipient":{"cc":"BE","person":"name","postal_code":"1111","city":"BRUSSEL","email":"e@mail.com","phone":"1","street":"streetname 1 a1","street_additional_info":""},"options":{"package_type":1,"label_description":";","only_recipient":0,"signature":0,"return":0,"delivery_type":2,"large_format":0,"delivery_date":"2020-05-15 00:00:00"},"carrier":1,"reference_identifier":"10101","general_settings":{"save_recipient_address":1,"disable_auto_detect_pickup":0}}]}} {"exception":"[object] (MyParcelNL\\Sdk\\src\\Exception\\ApiException(code: 0): Error in MyParcel API request: 3731 -  - This address can not be split. Please check address: streetname 1 a1 Url: https://api.myparcel.nl/shipments Request: {\"data\":{\"shipments\":[{\"recipient\":{\"cc\":\"BE\",\"person\":\"name\",\"postal_code\":\"1111\",\"city\":\"BRUSSEL\",\"email\":\"e@mail.com\",\"phone\":\"1\",\"street\":\"streetname 1 a1\",\"street_additional_info\":\"\"},\"options\":{\"package_type\":1,\"label_description\":\"\",\"only_recipient\":0,\"signature\":0,\"return\":0,\"delivery_type\":2,\"large_format\":0,\"delivery_date\":\"2020-05-15 00:00:00\"},\"carrier\":1,\"reference_identifier\":\"10101\",\"general_settings\":{\"save_recipient_address\":1,\"disable_auto_detect_pickup\":0}}]}} at /....../vendor/myparcelnl/sdk/src/Model/MyParcelRequest.php:145)"} []```

**Desktop (please complete the following information):**
 - MyParcel Plugin version: 3.2.1

**Comment by RichardPerdaan** [comment]
This issue is resolved in version [4.0.0-beta.1] (https://github.com/myparceln/magento/releases/tag/4.0.0-beta.1)
