### ISSUE TITLE
Bulk action: error in one order causes other labels not to be created in myparcel backend

### ISSUE THREAD

**Issue by bamboekeizer** [myparcelnl/magento#424]
**Describe the bug**
When creating concept labels for a series of orders, so-called bulk action, and one of the orders raises an error, the other labels do get a myparcel concept in the admin but non of labels are actually created in the myparcel backend.

**To Reproduce**
1. Go to order list with paid orders, in processing state
2. One of the orders has an invalid street address format, having the number in front of the the street name, for a Belgium address
2. Select a series orders
3. Select Myparcel label creation
4. Select concept and then create the labels

**Expected behavior**
Shipments created in magento and in the myparcel backend for all orders except for the one with the incorrect address

**Actual behavior **
Shipments are created in magento, with a Myparcel concept indication, but labels are not created in the myparcel backend

**Desktop (please complete the following information):**
 - Windows
 - Browser chrome
 - MyParcel Plugin version 3.2.1
 - MyParcel SDK version 3.1.7

**Comment by RichardPerdaan** [comment]
Hi @bamboekeizer ,

This problem has been solved since version 4.1.0 of the MyParcel plugin and version 5.1.0 of the MyParcel SDK.
