### ISSUE TITLE
Single day delivery date text field contains wrong html

### ISSUE THREAD

**Issue by Kroellie** [myparcelnl/magento#426]
https://github.com/myparcelnl/magento/blob/3facc7d068d9540daa03a97fbe62abe84cb78dea/view/frontend/web/js/lib/myparcel.js#L568

In case deliveryWindow === 1 you put the html of the <select> box in the text field, thus showing:

`<div name="mypa-delivery-date-text" id="mypa-date" title="Delivery date"><option value="0">Dinsdag 16-06-2020</option></div>
`
Which doesn't show anything on the frontend.

**Comment by RichardPerdaan** [comment]
This issue is resolved in version [4.0.0-beta.1] (https://github.com/myparceln/magento/releases/tag/4.0.0-beta.1)
