### ISSUE TITLE
Cannot upgrade to 3.3.0

### ISSUE THREAD

**Issue by phagens** [myparcelnl/magento#437]
We proberen 3.3.0 te installeren in onze testomgeving (staat nu 2.4.2 in) maar dat lukt niet.

Nadat we Composer upgrade myparcelnl/sdk myparcelnl/magento hebben uitgevoerd kunnen we de database niet meer indexeren en werkt de hele shop niet meer goed !

In de logging staat deze melding:

[22-Jun-2020 07:35:25 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method MyParcelNL\Magento\Model\Source\DropOffDelayDays::setAttribute() in /home/jukeboxs/staging/vendor/magento/module-eav/Model/Entity/Attribute/AbstractAttribute.php:623
Stack trace:
#0 /home/jukeboxs/staging/generated/code/Magento/Catalog/Model/ResourceModel/Eav/Attribute/Interceptor.php(1181): Magento\Eav\Model\Entity\Attribute\AbstractAttribute->getSource()
#1 /home/jukeboxs/staging/vendor/magento/module-catalog/Helper/Product/Flat/Indexer.php(311): Magento\Catalog\Model\ResourceModel\Eav\Attribute\Interceptor->getSource()
#2 /home/jukeboxs/staging/vendor/magento/module-catalog/Model/Indexer/Product/Flat/TableBuilder.php(67): Magento\Catalog\Helper\Product\Flat\Indexer->getAttributes()
#3 /home/jukeboxs/staging/vendor/magento/module-catalog/Model/Indexer/Product/Flat/AbstractAction.php(152): Magento\Catalog\Model\Indexer\Product\Flat\TableBuilder->build('7', Array, '_value')
#4 /home/jukeboxs/staging/vendor/magento/module-catalog/Model/Indexer/Product/Flat/Action/Full.p in /home/jukeboxs/staging/vendor/magento/module-eav/Model/Entity/Attribute/AbstractAttribute.php on line 623

**Comment by RichardPerdaan** [comment]
Beste @phagens,

Dank je wel voor het plaatsen van de issue.
Zou je ons telefonisch willen bellen, dan gaan we samen kijken wat er aan de hand is. Het is namelijk zo dat de DropOffDelayDays de AbstractSource extends. In de AbstractSource is de setAttribute aanwezig en zal dan ook gebruikt moeten worden.

**Comment by phagens** [comment]
Hallo,

Op welk nummer kan ik u bereiken ?


m.vr.gr. – with best regards


Piet Hagens
Jukebox Revival
Florijnstraat 6 C
4879 AH  Etten-Leur

Website: www.jukebox-revival.nl
Webshop: www.jukebox-revival.eu

[cid:image001.png@01D648AF.F6727060]
P Please consider the environment before printing this e-mail

The information sent with this e-mail message is only for the strict use of the intended recipient. In the event that this e-mail message is incomplete in any way, the recipient is kindly requested to contact the sender of this message. It is not permitted to publish, copy, circulate and/or disclose any of this information to third parties without the permission of Jukebox Revival. If you are not the intended recipient of and are in possession of this e-mail message, please notify us immediately, delete the e-mail message from your inbox, and do not use it for any purpose or disclose the contents of this message to third parties, or publish, copy or store this information on an information carrier.



Van: Richard Perdaan <notifications@github.com>
Verzonden: maandag 22 juni 2020 14:10
Aan: myparcelnl/magento <magento@noreply.github.com>
CC: Jukebox Revival <info@jukebox-revival.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [myparcelnl/magento] Cannot upgrade to 3.3.0 (#437)


Beste @phagens<https://github.com/phagens>,

Dank je wel voor het plaatsen van de issue.
Zou je ons telefonisch willen bellen, dan gaan we samen kijken wat er aan de hand is. Het is namelijk zo dat de DropOffDelayDays de AbstractSource extends. In de AbstractSource is de setAttribute aanwezig en zal dan ook gebruikt moeten worden.

**Comment by phagens** [comment]
Nogmaals. Ik wil u graag bellen maar zonder telefoonnummer wordt dat lastig !

**Comment by phagens** [comment]
Heb de contributie compleet verwijderd met composer alles werkt dan weer. Indexen kunnen worden aangemaakt en alles kan worden gecompileerd.
Daarna opnieuw geïnstalleerd. De indexen kan ik nu weer aanmaken maar kan de site niet compileren (stopt bij 14% zonder enige melding). Ter info omgeving is magento 3.0

**Comment by RichardPerdaan** [comment]
Beste @phagens,

Gisteren ben ik heel de dag niet op GitHub geweest en heb daarom jouw bericht niet gezien.
Wij hebben binnen MyParcel geen persoonlijke nummers en daarom zal je ons altijd kunnen bereiken op 0233030315.

Ik zal binnen de code kijken wat er aan de hand is met de TrackingUrl.php.

**Comment by RichardPerdaan** [comment]
Beste @phagens ,

Na meerdere testen, met verschillende omgevingen is het mij niet gelukt om het probleem te kunnen recreëren.
Als je ons zou willen bellen dan kan onze IT-support afdeling met je meekijken.
