### ISSUE TITLE
Only concept labels generated for some orders

### ISSUE THREAD

**Issue by karlgram** [myparcelnl/magento#438]
Magento2 3.2.0 + Myparcel plugin 3.2.1

When generating myparcel labels with: "Print MyParcel labels" we frequently now have orders for which only a Concept label is created and not the actual labels including the download for the A4.

Can't find any issues in the default magento logs. Any suggestion on what could be wrong and how to troubleshoot?

[
<img width="396" alt="Screenshot 2020-06-23 at 15 23 03" src="https://user-images.githubusercontent.com/12182104/85408948-7bb4eb00-b565-11ea-8275-4563beabfb6a.png">
](url)

**Comment by RichardPerdaan** [comment]
Hi @karlgram,

To be able to solve this problem, I want more information about the shipment. 
What shipments are involved (package, mailbox or digital stamp)? 
What is the destination of the shipment?

Perhaps it is easier to have contact through the IT support department. The IT support employees ar going to find out what exactly is wrong and discuss it with me or another developer.

You can reach us by phone: 0233030315 or by mail support@myparcl.nl
