### ISSUE TITLE
Custom order status settings

### ISSUE THREAD

**Issue by NerdUPCollectibles** [myparcelnl/magento#439]
Als een zending verstuurd via MyParcel word word deze automatisch op 'complete' gezet in Magento.
Is het mogelijk een tussenstap te creeeren met een zelf aangemaakte order statusen? Gezien dit af en toe wat onduidelijkheden geeft bij onze klanten die in hun account al "Complete" zien staan terwijl wij de zending nog aan het verwerken zijn in het magazijn.

Bijvoorbeeld "Word ingepakt" nadat we het label aanmaken.
"Bij PostNL" na de eerste scan.
"Onderweg voor uitlevering" als hij onderweg is en pas "Complete" als deze ontvangen is door de klant?

**Comment by RichardPerdaan** [comment]
Beste @NerdUPCollectibles,

Binnen de MyParcel plugin maken we gebruik van de standaard functionaliteit van Magento.
De MyParcel plugin past niet direct de status aan maar roept de functie setMagentoTrack aan. Dit is ook de functie die de status zal gaan aanpassen. Het aanmaken van de Magento shipment is helaas een verplichte stap.

Omdat dit een standaard onderdeel is van Magento, kunnen wij dit niet op een nette mannier oplossen binnen de MyParcel plugin.
