### ISSUE TITLE
only_recipient doesn't increase order price.

### ISSUE THREAD

**Issue by TimVroom** [myparcelnl/magento#450]
**Describe the bug**
When checking the only_recipient checkbox for default delivery, the total price of the shipment doesn't get increased with the 30 cents.
Also when going back to the shipping step from payment the checkbox is unchecked again. So what is the use of this field if it doesn't work?

This is on mageplaza onestepcheckout and the magento default checkout.

**Expected behavior**
That the price of the shipment gets increased by 30 cents (so from 4.95 > 5.25)

**Screenshots**

**Desktop (please complete the following information):**
 - MyParcel Plugin version: 4.1.1
 - MyParcel SDK version v5.1.0

**Additional context**
We use multiple shipping options (one is Trunkrs), this one also prevents from properly working since it has the same issue as #447 But even when that method is disabled it doesn't work.

**Comment by Mitchell-MyParcel** [comment]
Fixed in latest version.
