### ISSUE TITLE
MyParcel is not compatible with M2.4 - Please provide a link to the latest M2.4 compatible release!!!!

### ISSUE THREAD

**Issue by WilliejanB** [myparcelnl/magento#458]
Hi,

Today we updated M2.3.5-p2 to M2.4 and we have issues with MyParcel. When I look here: "https://github.com/myparcelnl/magento" - I followed this link to install it.

It says the compatibility with these magento version:
[2.3.5-p2, 2.3.4-p2, 2.3.5-p1, 2.3.5, 2.3.3-p1, 2.3.4, 2.3.2-p2, 2.3.3, 2.3.2, 2.3.1, 2.3.0]

Please give me a link where to download a M2.4 compatible download of your extension, because at this moment we have a problem.

Best regards,
Williejan

**Comment by WilliejanB** [comment]
When can we expect the new release? This is a struggle for 21 days now! For me, it is unbelievable that MyParcel is not up to date with Magento safety patch releases and that you do not respond to any emails at all.....

**Comment by WilliejanB** [comment]
Do you realize that you are putting us in a high-risk position with your lack of care? Any idea why Magento releases updates and advice their users urgently to update a.s.a.p? This is done because they found severe security breaches in M2.3!!!!!!

We CAN'T UPDATE to M2.4 because the MyParcel extension 4.1.1. version does NOT WORK WITH M2.4

You already know this for over a month! WHY DONT YOU TAKE YOUR CUSTOMERS SERIOUS?

RELEASE 4.1.2 so we can upgrade to M2.4 you are putting us to risk with this ridiculous behavior. Just respond to emails or questions, so we know when we can update! SHAME ON YOU MY PARCEL!!!!

**Comment by Misjnoe** [comment]
@WilliejanB We apologize for the delayed release of this update. We are currently testing this version of our plug-in and are aiming on a release in this week.

**Comment by Mitchell-MyParcel** [comment]
@WilliejanB We will be releasing the update tomorrow morning.

**Comment by WilliejanB** [comment]
@Mitchell-MyParcel FINALLY! Thank you for your notification.

Will this new release also includes functionality to ship with UPS?

**Comment by Mitchell-MyParcel** [comment]
@WilliejanB The update has been released this morning. This update does not contain functionality to ship with UPS. This release mainly contains fixes. You can check the changelog for details: https://github.com/myparcelnl/magento/releases/tag/4.1.2
