### ISSUE TITLE
I have an error sometimes even creating shipment. Product data must be set for international MyParcel shipments. Use addItem().

### ISSUE THREAD

**Issue by kostia-lev** [myparcelnl/magento#464]
![117768433_386546249172228_4766199672460543164_n](https://user-images.githubusercontent.com/1144764/90342422-f43da280-e010-11ea-995c-7c2af1eaf0e4.png)

I have this error for some products, not for all. 
It shows up when I click 'Ship' in order.
Can you give me a hint how to debug this?
Thanks

**Comment by RichardPerdaan** [comment]
Hi @kostia-lev ,

Are the HS code and the country of manufacturing been entered for the products that do not go well?

**Comment by kostia-lev** [comment]
@RichardPerdaan It seems orders from Great Britain are problematic. Did they create any special version for England? my version installed: v3.2.1

**Comment by RichardPerdaan** [comment]
Best @kostia-lev ,
We do not have a separate version for England.
What you could try is to install version 3.3.0, which also includes the functionality for country or orgin.

Could you indicate what is going wrong?

**Comment by RichardPerdaan** [comment]
Hi @kostia-lev ,
Today I managed to reproduce the problem. I am now working on the solution for this. 
The fix will be included in the next version of the plugin (4.1.5-beta.2)

**Comment by RichardPerdaan** [comment]
Solved in [4.1.6-beta.1](https://github.com/myparcelnl/magento/releases/tag/4.1.6-beta.1)
