### ISSUE TITLE
Shopping cart shows all delivery options

### ISSUE THREAD

**Issue by bezigeboefjes** [myparcelnl/magento#465]
**Describe the bug**
The shopping cart shows all delivery options, for example "brievenbuspakketje", while the product is not configured to fit as a "brievenbuspakketje"

**To Reproduce**
1. Add a product to the shopping cart
2. Click on 'Shopping cart' and choose "Change Shopping cart"
3. Select Country and enter a valid postal code in the shipping estimation
4. All shipping methods are shown

**Expected behavior**
Only shipping methods which apply to the products in the shopping cart, same like in the checkout.

**Screenshots**
![image](https://user-images.githubusercontent.com/20379631/90758926-06089980-e2e0-11ea-93a1-7552d30d51cb.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Magento version: 2.3.5
 - MyParcel Plugin version: 4.1.1
 - MyParcel SDK version: 5.1.0

**Additional context**

**Comment by bezigeboefjes** [comment]
Is it possible to work around this issue? Can we hide all the options (except for the default "Thuis afgeleverd")?

This issue is currently blocking upgrading to this version. We're still on a very old version 1.x :( and we really want to upgrade (because it can potentially break in future versions of Magento)

**Comment by RichardPerdaan** [comment]
PR : #468

**Comment by bezigeboefjes** [comment]
Thanks for the PR. I will test this as soon as I've some time for that (will not be before September 19th)

**Comment by RichardPerdaan** [comment]
Fixed in [4.1.2](https://github.com/myparcelnl/magento/releases/tag/4.1.2) of the MyParcel Magento 2 plugin
