### ISSUE TITLE
Ordergrid Print MyParcel Labels Directly not working properly when ordergrid is filtered

### ISSUE THREAD

**Issue by jdereus87** [myparcelnl/magento#467]
**Versions**
- Magento 2.3.5-p1.
- MyParcel 3.3.0

**Describe the bug**
Happens in the order grid (backend). When filtering orders, on example, date from & to, selecting an order (or multiple) and using the action menu -> PrintMyParcel Labels Directly, leads to an "no items selected error"

**To Reproduce**
1. Login to backend.
2. Go to orders.
3. Use a filter, like example, date from & to. 
4. Select a few orders that have not been processed by myparcel.
5. Open action menu.
6. Print MyParcel labels directly

**Expected behavior**
It should directly make the shipments and download the labels for the selected orders.

**Screenshots**
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): No items selected

Exception #0 (Magento\Framework\Exception\LocalizedException): No items selected
<pre>#1 MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack->execute() called at [generated/code/MyParcelNL/Magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack/Interceptor.php:24]
#2 MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#3 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#4 MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#5 MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#6 MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->___callPlugins() called at [generated/code/MyParcelNL/Magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack/Interceptor.php:39]
#7 MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:162]
#8 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:99]
#9 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#10 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#11 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#12 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#13 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#14 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#15 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]
</pre>

**Comment by Aquive** [comment]
Exactly the same error applies in below configuration:

- Magento 2.3.5-p1
- MyParcel 3.2.1

**Comment by Aquive** [comment]
@RichardPerdaan you added the label "next version". What does it mean? Any timeframe available?

**Comment by Kroellie** [comment]
Hmmm... sounds familiar: #197

**Comment by RichardPerdaan** [comment]
Fixed in [4.1.2](https://github.com/myparcelnl/magento/releases/tag/4.1.2) of the MyParcel Magento 2 plugin
