### ISSUE TITLE
Automate large format shipments based on dimensions

### ISSUE THREAD

**Issue by adem-demir** [myparcelnl/magento#469]
**Is your feature request related to a problem? Please describe.**
Yes, customer will send large format shipments but the weight or price isn't different regular shipments. Only the dimensions are big.

**Describe the solution you'd like**
Automate large format shipments based on dimensions

**Additional context**
case: 00836431 customer MEIPOS LED

**Comment by TimBlom** [comment]
Alternative at product page:

![image](https://user-images.githubusercontent.com/22811561/100853247-d5600080-3487-11eb-8172-ca74ef7d16bc.png)

**Comment by RichardPerdaan** [comment]
Fixed in [4.3.0-alpha.1 ](https://github.com/myparcelnl/magento/releases/tag/4.1.5-RC.1)
