### ISSUE TITLE
Error report when printing a label in backend

### ISSUE THREAD

**Issue by rikwillems** [myparcelnl/magento#475]
When I open a shipment and try to print the label I get an error report:
`Warning: count(): Parameter must be an array or an object that implements Countable in vendor/myparcelnl/magento/Controller/Adminhtml/Shipment/CreateAndPrintMyParcelTrack.php on line 110`

**Comment by rikwillems** [comment]
Changing the line resolves my issue: 
`if (count($this->messageManager->getMessages()) == 0) {`
to
`if ($this->messageManager->getMessages()->getCount() == 0) {`

**Comment by Mitchell-MyParcel** [comment]
@rikwillems We would like to fix this issue in the coming sprint. Could you please tell us which plugin version you are using?

**Comment by rikwillems** [comment]
@Mitchell-MyParcel het gaat om versie 4.1.1.

**Comment by RichardPerdaan** [comment]
Beste @rikwillems ,

Gisteren is er een nieuwe versie van de MyParcel Magento plugin live gezet.
Het bestand CreateAndPrintMyParcelTrack.php is in deze versie ook aangepast, hierdoor zal je de error niet meer krijgen.

Ik sluit hierbij dan ook de issue.
