### ISSUE TITLE
Is it correct that city refers to postcode in this piece of javascript?

### ISSUE THREAD

**Issue by gerben86** [myparcelnl/magento#479]
Compare line 158 and line 159...
Looks like that 159 is incorrect.

https://github.com/myparcelnl/magento/blob/7537ce2c429bb73e17eb24289e9960aeb133c37f/view/frontend/web/js/checkout/shipping_method/show-myparcel-shipping-method.js#L156-L159

**Comment by Mitchell-MyParcel** [comment]
@gerben86 This issue seems to be fixed in the latest version of our plugin. Please let us know if you are still having this issue after updating.
