### ISSUE TITLE
Error when not using PostNL options or using different shippingmethod

### ISSUE THREAD

**Issue by bojanni** [myparcelnl/magento#480]
**Describe the bug**

**To Reproduce**
1. Go to checkout
2. Click on shipping method other than managed by MyParcel
3. Scroll down to place order

main.CRITICAL: Warning: key_exists() expects parameter 2 to be array, null given in /home/***/public_html/vendor/myparcelnl/magento/Model/Sales/Repository/DeliveryRepository.php on line 39 {"exception":"[object] (Exception(code: 0): Warning: key_exists() expects parameter 2 to be array, null given in /home/***/public_html/vendor/myparcelnl/magento/Model/Sales/Repository/DeliveryRepository.php on line 39 at /home/***/public_html/vendor/magento/framework/App/ErrorHandler.php:61)"}

**Expected behavior**
Order to be placed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: CENTOS7
 - Browser Opera, Chrome, Edge
 - MyParcel 4.1.2
 - MyParcel SDK 5.2.1

**Additional context**
When I disable the PostNL options none of the different (ie tablerate, flatrate) shipping methods available in our store works and the error appears.

**Comment by ArjanZeinstra** [comment]
All shipping methode are broken after enabling PostNL options in checkout page.
All shipping methodes, like our "Store pickup" will give a payment error in checkoutpage!

**Comment by EdieLemoine** [comment]
Hi @ArjanZeinstra, I resolved the problem in #490.

**Comment by Mitchell-MyParcel** [comment]
Fixed in latest version
