### ISSUE TITLE
Additional Fee in checkout not working

### ISSUE THREAD

**Issue by ArjanZeinstra** [myparcelnl/magento#489]
If you add "Handtekening ontvangst" price or others additional Fee prices wil not be updated.

1. Add  'Handtekening ontvangst' + 0.50.
2. Activate & Save
3. Add product and go to checkout
4. Select PostNL + Handtekeningontvangst.

**Expected behavior**
+0.50 will be added

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [ chrome & IE]
 - MyParcel 4.1.2
 - MyParcel SDK 5.1.2

**Comment by ArjandenOuden** [comment]
We have the same issue
![image](https://user-images.githubusercontent.com/30589212/95680079-38938c00-0bd7-11eb-8935-564a0cbab6ab.png)

There's another problem at our site. Handtekening ontvangst is automatically selected and greyed out. So it's not selectable as an option. Have to turn this off right now as it's confusing for our customers. Myparcel, please fix asap. Again how is this tested?
Using mageplaza checkout but i know this have nothing to do with this.

**Comment by Mitchell-MyParcel** [comment]
Fixed in latest version
