### ISSUE TITLE
Feature Request: Compatibility Mageplaza 2.10.0

### ISSUE THREAD

**Issue by NikitaMyParcel** [myparcelnl/magento#496]
![3](https://user-images.githubusercontent.com/54140706/95325065-f39eeb00-08a0-11eb-9978-aa4f29e89ff6.png)

![1](https://user-images.githubusercontent.com/54140706/95325069-f4d01800-08a0-11eb-8954-ef1000621673.png)

Prijs wordt niet juist getoond + verkeerde bezorgoptie in subtotaal tabel onderaan wanneer wordt gekozen voor postnl locatie.

**Comment by Nikitaverh** [comment]
00859874

**Comment by bamboekeizer** [comment]
I'm using Mageplaza onestepcheckout 4.0.0 on magento 2.3.6 and myparcel 4.1.3 and have the same issue.
The selected PostNL location is also not saved to the database. I suspect an upgrade script issue for that..

**Comment by bamboekeizer** [comment]
When you have entered an address and then clear it and specify another address, the Shipping section keeps showing the message for entering postal code and number. This blocks finishing the checkout process. You have to reload the page to resolve it, definitely not user friendly.
![image](https://user-images.githubusercontent.com/28304222/99554702-c70de100-29bf-11eb-8096-728d0ee1ab63.png)

**Comment by AlexNauta** [comment]
Having the same problems.... Hope it will be fixed soon, as Mageplaza OSC is a widely used checkout.

**Comment by RichardPerdaan** [comment]
#518

**Comment by RichardPerdaan** [comment]
Solved with version [4.1.5-RC.1 ](https://github.com/myparcelnl/magento/releases/tag/4.1.5-RC.1)
