### ISSUE TITLE
Bezorgoptie prijs wordt niet meegenomen in ordertotaal

### ISSUE THREAD

**Issue by Nikitaverh** [myparcelnl/magento#497]
**Describe the bug**
Ochtendlevering/avondlevering prijs wordt niet meegenomen in order totaal

**To Reproduce**
Kiezen voor ochtendlevering in checkout

**Expected behavior**
Prijs van ochtendlevering moet worden meegenomen

**Screenshots**
https://monosnap.com/file/EGpSiNYjB6CI2uAS5qQYaCuFIMchwG

Testomgeving MyParcel

**Comment by Nikitaverh** [comment]
00859853

**Comment by Mitchell-MyParcel** [comment]
Fixed in latest version
