### ISSUE TITLE
Picqer compatibility

### ISSUE THREAD

**Issue by robindelaater** [myparcelnl/magento#502]
**Describe the bug**
When an order is requested from the Magento API, Picqer uses the delivery address from the order. When a PostNL pickup point is selected the address is not correct because the pick up point address is not set as delivery address.

**To Reproduce**
1. create an order using a postnl pickup point
2. export to picqer and see that the address is not the pickup address, but the customers address.

**Expected behavior**
You would expect the postnl pickup point address to be set as the address for delivery.

**Comment by RichardPerdaan** [comment]
Fixed in versio [4.1.4](https://github.com/myparcelnl/magento/releases/tag/4.1.4)
