### ISSUE TITLE
White screen na het aanmaken nieuwe verzending

### ISSUE THREAD

**Issue by gjvdheuvel** [myparcelnl/magento#503]
Na het aanmaken van een nieuwe verzending krijg ik al sinds 4.1.2 een white screen met helemaal niks.
Ik kies 'create myparcel consignment', ik kies 'PostNL' ik klik op verzenden en white screen en geen myparcel verzending aangemaakt in de myparcel backend.

Het is nu al drie versies zo bij mij ik wordt er nu best wel simpel van :-)

 - MyParcel Plugin version 4.1.1 t/m 4.1.3
 - MyParcel SDK version geen idee, latest

**Comment by gjvdheuvel** [comment]
Additionele info:

Dit is de PHP error als ik de debugmode aanzet...

Fatal error: Uncaught Error: Call to undefined method MyParcelNL\Sdk\src\Helper\MyParcelCollection::setUserAgentArray() in /home/<domeinnaam>/public_html/vendor/myparcelnl/magento/Model/Sales/MagentoCollection.php:116
Stack trace: #0 /home/<domeinnaam>/public_html/vendor/myparcelnl/magento/Observer/NewShipment.php(61): MyParcelNL\Magento\Model\Sales\MagentoCollection->__construct(Object(Magento\Framework\App\ObjectManager), Object(Magento\Framework\App\Request\Http)) #1 /home/<domeinnaam>/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): MyParcelNL\Magento\Observer\NewShipment->__construct(NULL) #2 /home/<domeinnaam>/public_html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('MyParcelNL\\Mage...', Array) #3 /home/<domeinnaam>/public_html/vendor/magento/framework/Objec in /home/<domeinnaam>/public_html/vendor/myparcelnl/magento/Model/Sales/MagentoCollection.php on line 116

**Comment by gjvdheuvel** [comment]
@RichardPerdaan kan je hier wat mee ?

**Comment by RichardPerdaan** [comment]
Beste @gjvdheuvel ,

Als ik naar de laatste versie van de MyParcel Magento 2 plugin kijk en dan specifiek naar de de regel waar de error vandaan komt dat zie ik het volgende:

https://github.com/myparcelnl/magento/blob/develop/Model/Sales/MagentoCollection.php#L118

In de laatste versie van de plugin zal `setUserAgents` gebruikt moeten worden. Het kan zijn dat de SDK niet geüpdatet is waardoor de juiste functie niet gevonden kan worden. Ik adviseer om ook de SDK te updaten naar versie 5.2.2.

Mocht dit niet werken dan hoor ik het graag.

**Comment by gjvdheuvel** [comment]
Dat was het inderdaad @RichardPerdaan Super !!! Wel raar wan tin de composer update zei ie wel dat ie geupdated was, nu heb ik hem er met de hand ingekopieerd en dat pikt ie.

Dankjewel voor het wegnemen van een dikke frustratie !
