### ISSUE TITLE
Zendingen naar België geven error in 4.1.3 (preg_match() param 1 = NULL)

### ISSUE THREAD

**Issue by AlexNauta** [myparcelnl/magento#504]
**Describe the bug**
Wanneer ik upgrade naar 4.1.3, met bijbehorende SDK 5.2.2 (lagere SDK is niet compatibel, misschien handig om nog te vermelden), kunnen er geen zendingen naar België meer gedaan worden. Je krijgt dan een fatal error.
Fatal error: Uncaught TypeError: preg_match() expects parameter 1 to be string, null given in ..../vendor/myparcelnl/sdk/src/Helper/ValidateStreet.php:39 

**To Reproduce**
1. Upgrade naar myparcelnl/magento:4.1.3 en myparcelnl/sdk:5.2.2
2. Selecteer een bestelling in het orderoverzicht met een afleveradres in België
3. Verzend deze via 'Print Myparcel labels direct'
4. Neem kennis van de foutmelding

**Volledige foutmelding**
Fatal error: Uncaught TypeError: preg_match() expects parameter 1 to be string, null given in //vendor/myparcelnl/sdk/src/Helper/ValidateStreet.php:39 
Stack trace: 
#0 //vendor/myparcelnl/sdk/src/Helper/ValidateStreet.php(39): preg_match(NULL, 'ROZEMARIJNLAAN ...', NULL) 
#1 //vendor/myparcelnl/magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack.php(175): MyParcelNL\Sdk\src\Helper\ValidateStreet::validate('ROZEMARIJNLAAN ...', 'NL', 'BE') 
#2 //vendor/myparcelnl/magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack.php(103): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack->filterCorrectAddress(Array) 
#3 //vendor/myparcelnl/magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack.php(64): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndP in //vendor/myparcelnl/sdk/src/Helper/ValidateStreet.php on line 39

**Desktop (please complete the following information):**
 - Magento 2.3.5-p2
-  PHP 7.3.23 (PHP-FPM > Apache > Varnish > Nginx)
 - MyParcel Plugin 4.1.3
 - MyParcel SDK 5.2.2

**Comment by AlexNauta** [comment]
Ik heb het tijdelijk kunnen fixen door de getStreetRegexByCountry functie wat aan te passen in sdk/src/Helper/ValidateStreet.php. Deze leek niet waterdicht, en kon een NULL voeden aan de preg_match op regel 39 in sdk/src/Helper/ValidateStreet.php

**Comment by robindelaater** [comment]
Hi @AlexNauta,

We hebben er een fix voor geschreven. #273
Dit zal in de volgende release van de SDK zitten.

**Comment by gerben86** [comment]
When will the next release be? I'm facing the same issue...

**Comment by wahidnory** [comment]
> Hi @AlexNauta,
> 
> We hebben er een fix voor geschreven. #273
> Dit zal in de volgende release van de SDK zitten.

Volgens mij gaat hier iets door elkaar. De issue gaat namelijk om dat er NULL waardes uit de validator komen. Niet om taxes, de issue waar je naar verwijst.

Dus volgens mij is dit nog niet gefixt. En hoort deze issue nog open te staan.
