### ISSUE TITLE
Can't Checkout to Belgium, payment error Try again later?

### ISSUE THREAD

**Issue by ArjanZeinstra** [myparcelnl/magento#506]
Not possible to use a belgium address

**To Reproduce**

1. Update SDK v 5.2.2 and Myparcel 4.1.3
2. Checkout to NL is fine, to BE is not working. error in payment.
3. Disable my parcel for BE, try other shipping methode gives me error:
postal_code doesn't look like a postal code for country BE" from api.myparcel ??
4. Downgrade to SDK 5.2.1 and myparcel 4.1.2 is working only!

Skip checks when shipping methode not available in myparcel.js! 

**Screenshots**
![2020-11-01 14_31_07-Afrekenen](https://user-images.githubusercontent.com/16224647/97804375-bb948900-1c4f-11eb-9fa5-3597418e6958.png)

**Desktop (please complete the following information):**
 - OS: All
 - MyParcel Plugin version 4.1.3
 - MyParcel SDK version 5.2.2

**Additional context**
Update quick please OR work arround

**Comment by RichardPerdaan** [comment]
Hi @ArjanZeinstra ,
Are you still experiencing this problem?
I would like to help you further.
