### ISSUE TITLE
Order with 2 products (1 fits in mailbox, other not) leads to fit_in_mailbox-label

### ISSUE THREAD

**Issue by gerben86** [myparcelnl/magento#511]
**Describe the bug**
When a customer orders 2 products, one has the value fit_in_mailbox 3 productes and the other product doesn't fit in a mailbox the printed label is for a mailbox-package.

**To Reproduce**
1. Place an order with 2 products, one fits in mailbox, other doesn't
2. Create a shippinglabel

**Expected behavior**
The shippinglabel is for a normal package.

**Screenshots**
The label is for a mailbox-package.

**Desktop (please complete the following information):**
 - MyParcel Plugin version: 4.1.3
 - MyParcel SDK version: v5.5.2

**Comment by gerben86** [comment]
We encountered the same behaviour again today.
First I thought it could be misclicking in the dropdown, but that's not the issue, we checked it with 2 people today.

Could you have a look and let us know how to fix this?

**Comment by gerben86** [comment]
This is the rootcause of this error: https://github.com/myparcelnl/magento/issues/513
Do you have time to look at this and provide me a (temporary) fix? Becaues this leads to incorrect labels, miscommunication with customers etc...

**Comment by michel334** [comment]
Ik heb hetzelfde probleem trouwens.

**Comment by gerben86** [comment]
@Mitchell-MyParcel @RichardPerdaan Enig idee wanneer dit gefixed zal zijn? We zijn nu een half jaar verder en nog iedere dag krijgen we hier vragen/klachten over...

**Comment by RichardPerdaan** [comment]
Opgelost in [4.1.6-beta.1](https://github.com/myparcelnl/magento/releases/tag/4.1.6-beta.1)
