### ISSUE TITLE
setUserAgentArray() Method does not exist

### ISSUE THREAD

**Issue by Wiseconn-SB** [myparcelnl/magento#512]
**Describe the bug**
MyParcelNL\magento/Model/Sales/MagentoCollection

Line 116:
$this->myParcelCollection = (new MyParcelCollection())->setUserAgentArray(['Magento2'=> $this->helper->getVersion()]);

The method does not exist and is renamed on the 24th of september. It should be setUserAgents()

**Comment by RichardPerdaan** [comment]
Hi @Wiseconn-SB ,

Thank you for posting the issue. From version 4.1.3 this problem should already be solved. Would you like to check if you are using this version?

**Comment by RichardPerdaan** [comment]
Hi @Wiseconn-SB,

for now I am closing the issue. 
If this problem is still present, please let me know.

It is always possible to open the issue again.
