### ISSUE TITLE
Brievenbuspakje is shown in the checkout, while the products don't fit a brievenbuspakje!!!

### ISSUE THREAD

**Issue by gerben86** [myparcelnl/magento#513]
**Describe the bug**

**To Reproduce**
1. This are the settings for brievenbuspakje:
![image](https://user-images.githubusercontent.com/17478858/99565565-16f2a500-29cc-11eb-8149-91e304078762.png)

2. Add 2 products to the cart
One product with this option:
![image](https://user-images.githubusercontent.com/17478858/99564143-5d470480-29ca-11eb-8557-79ab6719b0ed.png)
One product with this option:
![image](https://user-images.githubusercontent.com/17478858/99564286-88c9ef00-29ca-11eb-8e77-5e86435b3856.png)

3. Go to the checkout
4. Enter a valid postcode and housenumber
5. Check the shipping options

**Expected behavior**
Brievenbuspakje is not an option in the checkout, only a normal package can be used

**Screenshots**
Brievenbuspakje is shown as an option:
![image](https://user-images.githubusercontent.com/17478858/99564031-38529180-29ca-11eb-84ef-6ca289fc1782.png)

If you remove the product which fits the brievenbuspakje, that option isn't shown anymore, so then the customer can't select a brievenbuspakje.

If you remove the product whicht doesn't fit the brievenbuspakje the customer still has the option to send it to an PostNL-location:
![image](https://user-images.githubusercontent.com/17478858/99565488-fc203080-29cb-11eb-8bd9-2293df874959.png)
That also shouldn't be the case

**Desktop (please complete the following information):**
 - Browser: Chrome
 - MyParcel Plugin version: 4.1.3 
 - MyParcel SDK version: v5.2.4

**Comment by gerben86** [comment]
@RichardPerdaan : Do you or a colleague know what the issue could be?

**Comment by Kroellie** [comment]
related? #529

**Comment by gerben86** [comment]
I don't know, but I don't use the matrix for calculating shipping costs, so doubting that it's the same.
I got a confirmation from MyParcel that this issue will be solved before the end of this month, so I expect an update (and a new version) somewhere this week.

**Comment by Kroellie** [comment]
My Matrix Rate extension is nearly similar to table rate functionality. I noticed that I always (!) get digital_stamp and mailbox rates back. No matter what option I enable or disable in MyPa config or product config. Crossing fingers for a fix this week.

**Comment by gerben86** [comment]
> My Matrix Rate extension is nearly similar to table rate functionality. I noticed that I always (!) get digital_stamp and mailbox rates back. No matter what option I enable or disable in MyPa config or product config. Crossing fingers for a fix this week.

Ah, I didn't know that. So then they could be related indeed. Hopefully @RichardPerdaan has an update for us!

**Comment by gerben86** [comment]
When will the next version be released?
We're now 4 months later...

**Comment by RichardPerdaan** [comment]
Solved in [4.1.6-beta.1](https://github.com/myparcelnl/magento/releases/tag/4.1.6-beta.1)

**Comment by NerdUPCollectibles** [comment]
@RichardPerdaan wanneer komt er een stable release voor deze bug?
