### ISSUE TITLE
Magento 2.4.1 Vervoerder met dergelijke methode niet gevonden: tablerate, null

### ISSUE THREAD

**Issue by gjportegies** [myparcelnl/magento#519]
**Describe the bug**
The MyParcel shipping method won't load and shows an error when visiting the checkout.

**To Reproduce**
1. Go to checkout
2. See error

**Expected behavior**
The MyParcel shipping methods should load.

**Desktop (please complete the following information):**
 - Browser Chrome
 - MyParcel Plugin version: 4.1.4
 - OneStepCheckout 1.2.042
 - Magento 2.4.1

**Additional context**

The error is thrown in ```\Magento\Checkout\Model\ShippingInformationManagement``` and probably caused because the shipping rate can't be loaded by code. This is maybe caused by changes in [Magento 2.4 config files](https://devdocs.magento.com/guides/v2.4/howdoi/checkout/checkout-add-custom-carrier.html) for custom shipping methods.

```
        if (!$quote->getIsVirtual()
            && !$shippingAddress->getShippingRateByCode($shippingAddress->getShippingMethod())
        ) {
            throw new NoSuchEntityException(
                __('Carrier with such method not found: %1, %2', $carrierCode, $methodCode)
            );
        }
```

**Comment by RichardPerdaan** [comment]
Solved in 4.7.0 of the MyParcel plugin
