### ISSUE TITLE
Error on printing shipping label from shipment view in adminhtml

### ISSUE THREAD

**Issue by mgroensmit** [myparcelnl/magento#523]
**Describe the bug**
MyParcel labels are created for the wrong shipment and under certain conditions generate an error.

**To Reproduce**
Preconditions:
- Ensure one of the shipment's 'entity_id' is the same integer as the 'entity_id' of an entirely unassociated order (not shipment).
- Ensure the unassociated order is made on a store that has no API key for MyParcel in the configuration it'll show a clear error.
1. Go to the shipment page of the shipment with the same entity_id as an unassociated order.
2. Click on 'Print Label'
3. Select whatever 'MyParcel options' you want.
3. Click on 'ok'
4. See error in case there is no API key for the store of the aforementioned unassociated order.

**Expected behavior**
A label is printed for the shipment

**Screenshots**
![image](https://user-images.githubusercontent.com/53430364/104008770-30cd8e80-51aa-11eb-9d51-66c0fdd9c4a9.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - chrome
 - 4.1.4
 - 5.2.4

**Additional context**
I'm pretty sure this bug is caused because in the 'MyParcelNl\Magento\Block\Sales\ShipmentAction' class in the 'getEntityId' function a shipment entity_id is returned, subsequently the request to print a label is sent to the 'MyParcelNl\Magento\Controller\Adminhtml\Shipment\CreateAndPrintMyParcelTrack' controller.

In that controler the entered ID's are treated as order id's rather than shipment id's. In the 'addOrdersToCollection' function this is made explicit.

It would appear that this code was simple copied from the MyParcelNL\Magento\Controller\Adminhtml\order\CreateAndPrintMyParcelTrack without adaptation to make it suitable for shipment entity_ids.

**Comment by RichardPerdaan** [comment]
Solved in [4.1.6-RC.1](https://github.com/myparcelnl/magento/releases/tag/4.1.6-RC.1)
