### ISSUE TITLE
Stamp and mailbox issue

### ISSUE THREAD

**Issue by Kroellie** [myparcelnl/magento#529]
Plugin version 4.1.4 - Magento 2.3.6

We're using a matrix rate shipping method as a basis for MyParcel plugin.

We noticed that when calling the estimate-shipping-methods, we still receive a fee for digital_stamp and mailbox, even though this option is disabled in the postnl settings.

This way, all our orders' shipping costs are estimated to 1,00 EUR by default.

**Comment by Kroellie** [comment]
I think I resolved my issue by adding the 

if ($this->isSettingActive(Data::CARRIERS_XML_PATH_MAP[$carrier], $settingPath)) {
 ...
}

condition to the adddMyParcelRates function.

**Comment by RichardPerdaan** [comment]
Solved in [4.1.6-beta.1](https://github.com/myparcelnl/magento/releases/tag/4.1.6-beta.1)
