### ISSUE TITLE
Empty shipping label print (shipping label creation in MyParcel does work)

### ISSUE THREAD

**Issue by florisschreuder** [myparcelnl/magento#536]
Hi MyParcel,

After creating a shipment in Magento 2 admin panel, then clicking 'Print Label', you get an almost empty page:

![image](https://user-images.githubusercontent.com/57114356/107493071-7d333200-6b8d-11eb-9070-e51c2c47ba72.png)

Tried on both A4 and A6 printing formats. Tried on several different orders.

The actual label does get created in MyParcel, so the communication with MyParcel does seem to work well. It's just the printing in Magento that doesn't function.

I can't find any error reports in var/log or var/report that seem to relate to this issue.

Thanks in advance!

**Comment by florisschreuder** [comment]
Hi MyParcel,

I've found the error message. It wasn't logged in any Magento log, but in the NGINX Error log:

`2021/02/18 11:47:33 [error] 2912#2912: *124294 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getUrl() on null in /data/web/magento2/vendor/magento/module-sales/view/frontend/templates/email/shipment/track.phtml:28
Stack trace:
#0 /data/web/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
#1 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Framework\View\Element\Template\Interceptor), '/data/web/magen...', Array)
#2 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent('render', Array)
#3 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\View\Element\Template\Interceptor), '/data/web/magen...', Array)
#4 /data/web/magento2/generated/code/Magento/Framework/View/Templa" while reading response header from upstream, client: [REMOVED], server: [REMOVED], request: "GET /storemanager/myparcel/order/CreateAndPrintMyParcelTrack/selected_ids/454/mypa_package_type/1/mypa_request_type/download/key/[REMOVED]/ HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "[REMOVED]", referrer: "[REMOVED]/storemanager/sales/order/index/key/[REMOVED]/"`

After removing this line from the Magento_Sales/view/frontend/templates/email/shipment/track.phtml file:
`<a href="<?= $block->escapeUrl($block->getTrackingUrl()->getUrl($_item)) ?>" target="_blank">`
Everything works. It's looking like the PDF download also renders an email at the same time.

**Comment by RichardPerdaan** [comment]
Hi @florisschreuder,

I have searched around, to see if multiple users are affected by this problem. I found the following github page: [https://github.com/magento/magento2/issues/25221](https://github.com/magento/magento2/issues/25221)

It seems that there is a double process of Magento that is used in the MyParcel plugin.

**Comment by Mitchell-MyParcel** [comment]
A possible fix is offered. Closing this thread due to no reaction.
