### ISSUE TITLE
In Versie 4.1.4  staat de selectie dropdown in NL en ENG door elkaar

### ISSUE THREAD

**Issue by soedesh** [myparcelnl/magento#538]
**Describe the bug**
In Versie 4.1.4  staat de selectie dropdown in NL en ENG door elkaar

**To Reproduce**
klik in het orderoverzicht op select

**Expected behavior**
dropdown menu slide open

**Screenshots**
![Orders : Operations : Sales : Magento Admin 2021-02-17 15-46-11](https://user-images.githubusercontent.com/46486914/108220720-52ba1980-7137-11eb-880d-1f1230f81b91.png)

**Comment by RichardPerdaan** [comment]
Hi @soedesh  ,
This problem has been resolved in version [4.1.6-RC.1 ](https://github.com/myparcelnl/magento/releases/tag/4.1.6-RC.1)of the MyParcel plugin.
