### ISSUE TITLE
Na Update MyParcel staat Fit in Mailbox overal onterecht op Look to Weight in plaats van 2 producten 50%

### ISSUE THREAD

**Issue by michel334** [myparcelnl/magento#541]
Update van MyParcel 3.0.3 naar 4.1.4
Open een brievenbus product
Bij de MyParcel Options staat na de update overal "Look to weight" in plaats van bijvoorbeeld "Past in brievenbuspakje 2 producten 50%"

Ik zou verwachten dat na de update alle instellingen bij de producten onderdeel MyParcel Opties niet veranderen

Zie screenshots van voor en na de MyParcel update

 - OS: Windows
 - Browser Chrome
 - MyParcel Plugin version: Update van MyParcel 3.0.3 naar 4.1.4
 - MyParcel SDK version Update van v2.1.5 => v5.2.8

![voor-update-2-producten-50-procent](https://user-images.githubusercontent.com/6500172/108975384-b936be80-7686-11eb-8547-53021a7d1a6b.jpg)
![na-update-look-to-weight](https://user-images.githubusercontent.com/6500172/108975399-bdfb7280-7686-11eb-966a-7dafbe96e107.jpg)

**Comment by RichardPerdaan** [comment]
Opgelost in [4.1.6-beta.1](https://github.com/myparcelnl/magento/releases/tag/4.1.6-beta.1)
