### ISSUE TITLE
Regelmatig worden er meer verzendopties getoond dan ingeregeld. zie bijlage.

### ISSUE THREAD

**Issue by michel334** [myparcelnl/magento#542]
Er worden vaak meer verzendopties getoond dan ingeregeld. zie bijlage.

Op onze Belgische webshop worden altijd alle (ook de niet ingeregelde) verzendopties getoond en die blijven ook staan na het invullen van de adresgegevens. Afrekenen met de juiste verzendkosten is dus bijna niet mogelijk. Op deze shop is de postcode checkout plugin niet actief. Zie ook onze Belgische testomgeving:
http://retro-deurbeslag-belgie.michelwebdesign.nl/

Op onze NL webshop verdwijnen deze verzendopties tijdens het invullen van de adresgegevens waarna wel de juiste verzendopties worden getoond. Op deze shop is de postcode checkout plugin wel actief. Zie ook testomgeving http://retro-deurbeslag.michelwebdesign.nl/

**Expected behavior**
Enkel de verzendopties tonen die zijn ingeregeld

**Screenshots**
![alle-verzendopties](https://user-images.githubusercontent.com/6500172/108985337-39622180-7691-11eb-9817-1bd7f9051e98.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - MyParcel Plugin version: 4.1.4
 - MyParcel SDK version:  5.2.8

**Comment by Mitchell-MyParcel** [comment]
@michel334 Zou je contact op willen nemen met support@myparcel.nl? We willen hier graag even met een ontwikkelaar naar kijken. Zou je login credentials mee kunnen sturen voor je omgevingen? Als je mijn naam noemt zorgen mijn collega's dat de mail bij de juiste persoon terecht komt.

**Comment by michel334** [comment]
@Mitchell-MyParcel Dat is prima bedankt, ik heb contact opgenomen en de credentials doorgegeven.

**Comment by RichardPerdaan** [comment]
Solved in 4.7.0 of the MyParcel plugin

**Comment by michel334** [comment]
We gebruiken inmiddels SendCloud. Werkt prima :)
