### ISSUE TITLE
Table rate verzendkosten Belgie kloppen niet op de 1e stap afrekenpagina (pakt NL table rate verzendkosten). Op de 2e stap klopt het wel.

### ISSUE THREAD

**Issue by michel334** [myparcelnl/magento#543]
Table rate verzendkosten Belgie kloppen niet op de 1e stap afrekenpagina (pakt NL table rate verzendkosten). Op de 2e stap klopt het wel.

OS: Windows
Browser chrome
MyParcel Plugin version: 4.1.4
MyParcel SDK version: 5.2.8
Magento: 2.3.2

**Comment by RichardPerdaan** [comment]
Opgelost in [4.1.6-beta.1](https://github.com/myparcelnl/magento/releases/tag/4.1.6-beta.1)
