### ISSUE TITLE
Afrekenen blokkeert. Knop volgende werkt niet bij verzenden naar Belgie

### ISSUE THREAD

**Issue by michel334** [myparcelnl/magento#544]
Afrekenen blokkeert. Knop volgende werkt niet bij verzenden naar Belgie. Ik kan de verzendmethode ook niet selecteren.
Dit gaat fout in combinatie met de postcode controle plugin van postcode-checkout build: b20210209
Zonder deze plugin werkt het wel, maar we hebben een goede postcode check nodig.

**Expected behavior**
Kunnen afrekenen bij verzending naar Belgie

**Screenshots**
![geen-verzendmethodes-verzending-belgie](https://user-images.githubusercontent.com/6500172/108990953-c8723800-7697-11eb-81c0-415d2544d1e5.jpg)
![verzenden-naar-belgie-niet-mogelijk](https://user-images.githubusercontent.com/6500172/108990968-cc05bf00-7697-11eb-9eb2-e27afd0d4139.jpg)

OS: Windows
Browser chrome
MyParcel Plugin version: 4.1.4
MyParcel SDK version: 5.2.8
Magento: 2.3.2

**Comment by RichardPerdaan** [comment]
Beste @michel334,

Na een aantal testen, heb ik dit probleem niet meer kunnen reproduceren. Is dit issue nog steeds relevant?
Mocht dit issue nog steeds aanwezig zijn dan wil ik dit graag gaan oppakken.

**Comment by michel334** [comment]
Beste Richard,
We gebruiken geen MyParcel meer
Groet,
Michel
