### ISSUE TITLE
Onterechte verzending naar Belgie als brievenbuspakje

### ISSUE THREAD

**Issue by michel334** [myparcelnl/magento#547]
Onterechte verzending naar Belgie als brievenbuspakje
Testomgeving:
http://retro-deurbeslag.michelwebdesign.nl/

**Expected behavior**
Brievenbuspakjes zijn niet toegestaan bij verzending naar Belgie. De belgische table rate verzendkosten gebruiken

![Onterecht-verzending-naar-belgie-als-brievenbuspakje](https://user-images.githubusercontent.com/6500172/109625540-b97c0180-7b3f-11eb-8ee0-c6d28ef15704.jpg)

OS: Windows
Browser chrome
MyParcel Plugin version: 4.1.4
MyParcel SDK version: 5.2.8
Magento: 2.3.2

Testen jullie zelf de software wel eens, allemachtig :)

**Comment by RichardPerdaan** [comment]
De volgende PR's staan open om dit probleem op te lossen:
[#537](https://github.com/myparcelnl/magento/pull/537)
[#539](https://github.com/myparcelnl/magento/pull/539)

**Comment by michel334** [comment]
Ok, bedankt

**Comment by RichardPerdaan** [comment]
Opgelost in [4.1.6-beta.1](https://github.com/myparcelnl/magento/releases/tag/4.1.6-beta.1)

**Comment by NerdUPCollectibles** [comment]
@RichardPerdaan wanneer komt er een stable release voor deze bug?
