### ISSUE TITLE
As a client I don't want to be obliged to enable 'only recipient' when enabling 'morning delivery' and 'evening delivery'

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/magento#550]
**Describe the bug**
If I do not enable 'only recipient' the additional fees of morning delivery and evening delivery are not charged. This is caused by not selecting the right radio button.

**To Reproduce**
Steps to reproduce the behavior without enabling 'only recipient' in the settings:
1. Go to 'the checkout'
2. Select 'evening delivery'
3. See wrong price

**Expected behavior**
Morning or evening delivery should be selected

**Screenshots**
![image](https://user-images.githubusercontent.com/22811561/110486885-5d8c1c80-80ed-11eb-9954-b0aa7d4b5a62.png)

**Comment by RichardPerdaan** [comment]
Hi @TimBlom  ,
This problem has been resolved in version [4.1.6-RC.1 ](https://github.com/myparcelnl/magento/releases/tag/4.1.6-RC.1)of the MyParcel plugin.
