### ISSUE TITLE
main.CRITICAL: Exception: Notice: Undefined variable: carriers in /data/web/magento2/vendor/myparcelnl/magento/Model/Quote/Checkout.php on line 213 in /data/web/magento2/vendor/magento/framework/App/ErrorHandler.php:61

### ISSUE THREAD

**Issue by victorchiriac89** [myparcelnl/magento#552]
private function get_carriers(): array
    {
        $carriersSettings = [
            ['postnl', Data::XML_PATH_POSTNL_SETTINGS]
        ];
        // Add this here
        $carriers = [];

        foreach ($carriersSettings as $carrier) {
            if ($this->helper->getBoolConfig("{$carrier[self::SELECT_CARRIER_PATH]}", 'delivery/active') ||
                $this->helper->getBoolConfig("{$carrier[self::SELECT_CARRIER_PATH]}", 'pickup/active')
            ) {
                $carriers[] = $carrier;
            }
        }

        return $carriers;
    }

**Comment by RichardPerdaan** [comment]
Solved in  [4.1.6-beta.1](https://github.com/myparcelnl/magento/releases/tag/4.1.6-beta.1)
