### ISSUE TITLE
Myparcel order via backend

### ISSUE THREAD

**Issue by kennysinkeler** [myparcelnl/magento#553]
Hi all,

Graag zou ik willen zien dat als je via de backend een order aanmaakt, ook alle myparcel options er bij komen. Zoals bij magento 1 was.
Zie:
![image](https://user-images.githubusercontent.com/10799266/110952100-1ba9e300-8346-11eb-9fdf-2bc14696ce27.png)

Dit is zoals het in magento 2 is.
![image](https://user-images.githubusercontent.com/10799266/110951915-e4d3cd00-8345-11eb-8b88-f23112014417.png)

**Comment by RichardPerdaan** [comment]
Hi @kennysinkeler,

Wanneer er een order is geplaatst dan zal je onder "ship" of "verzenden" de mogelijkheid om gebruik te maken van de MyParcel opties. Hieronder een kleine uitleg:

![screencast 2022-04-26 16-04-33](https://user-images.githubusercontent.com/11389731/165318346-4e5d2b31-2fb4-4e2e-9b74-325490ce6aa5.gif)

**Comment by RichardPerdaan** [comment]
@kennysinkeler is de bovenstaande oplossing voor jou werkbaar?
