### ISSUE TITLE
Als 18+ check standaard aan staat kan je handtekening voor ontvangst en alleen huisadres niet uitzetten

### ISSUE THREAD

**Issue by TeunSmit** [myparcelnl/magento#554]
Zodra je de 18+ check standaard activeert, staan handtekening voor ontvangst en alleen huisadres altijd op "Yes". Dit kan je niet veranderen omdat de optie "No" niet meer beschikbaar is. 
<img width="783" alt="Configuration : Settings : Stores : Magento Admin 2021-04-06 15-02-30" src="https://user-images.githubusercontent.com/54140671/113725536-b1d9ea80-96f3-11eb-945b-651ebb5ab5fc.png">

Wens: 
Mogelijk maken om 18+ standaard aan te hebben, maar handtekening voor ontvangst en alleen huisadres altijd uit te kunnen zetten. Dit voorkomt dat het nog een keer extra in de checkout geselecteerd wordt door de consument.

**Comment by RichardPerdaan** [comment]
Opgelost in [4.1.6-beta.1](https://github.com/myparcelnl/magento/releases/tag/4.1.6-beta.1)
