### ISSUE TITLE
Can't select other shipping methods

### ISSUE THREAD

**Issue by gjportegies** [myparcelnl/magento#569]
**Describe the bug**
When using version 4.1.6-beta.1 of the MyParcel module we can't select other shipping methods in the checkout.

**To Reproduce**
1. Go to checkout.
2. Fill in all needed information.
3. Select a shipping method other than Myparcel.
4. The selected method flicks back to myparcel's method.

**Expected behavior**
When selecting a different shipping method, the method should stay selected.

**Screenshots**

![myparcel-issue-1](https://user-images.githubusercontent.com/6707410/118474941-edf96580-b70b-11eb-9e07-1e1d3b059ab6.jpg)

https://user-images.githubusercontent.com/6707410/118474968-f782cd80-b70b-11eb-9209-92d0d627f402.MP4

**Desktop (please complete the following information):**
 - MyParcel Plugin version 4.1.6-beta.1
 - MyParcel SDK version 4.1.6-beta.1

**Additional context**

**Comment by RichardPerdaan** [comment]
PR: #565

**Comment by RichardPerdaan** [comment]
Hi @gjportegies,
This problem will be solved with the next version of the MyParcel Magento 2 plugin

**Comment by RichardPerdaan** [comment]
Hi @gjportegies ,
This problem has been resolved in version [4.1.6-RC.1 ](https://github.com/myparcelnl/magento/releases/tag/4.1.6-RC.1)of the MyParcel plugin.
