### ISSUE TITLE
Myparcel 4.1.6 shipping options not loading on first try checkout

### ISSUE THREAD

**Issue by gjportegies** [myparcelnl/magento#575]
**Describe the bug**
When trying to checkout the first time, the myparcel options won't load.

**To Reproduce**
1. Add a product to your cart.
2. Go to the checkout page.
3. Fill in your address information.

**Expected behavior**
Myparcel shipping options should load as espected.

**Screenshots**

https://user-images.githubusercontent.com/6707410/122201159-08099d80-ce9c-11eb-84e8-dd1155695f5a.mp4

**Desktop (please complete the following information):**
 - Magento 2.3.6-p1
 - Browser Chrome + Firefox
 - MyParcel Plugin version 4.1.6
 - MyParcel SDK version 5.2.10

**Additional context**
After filling in the required address information and reloading the page the Myparcel shipping options will load succesfully.

**Comment by RichardPerdaan** [comment]
Hi @gjportegies, 
Thank you for posting your message. It's weird that the delivery options don't pick up the address data properly.
I've tested this issue on multiple systems and haven't seen the problem on our test environments.

I would therefore like to do further research on your system. To make this possible, I would like to ask you to send an email to support@myparcel.nl. If you mention my name in the mail, then the mail will reach me.

**Comment by RichardPerdaan** [comment]
Fixed in [v4.4.0](https://github.com/myparcelnl/magento/releases/tag/v4.4.0)
