### ISSUE TITLE
No shipments, cron error

### ISSUE THREAD

**Issue by Kroellie** [myparcelnl/magento#576]
Upon fresh installation of M2.4.2 & MyPa 4.1.6-RC.1 without any orders present, I noticed the cron scheduler trying to run for an empty array, leading up to error:

Cron Job myparcel_update_status has an error: Argument 1 passed to MyParcelNL\Sdk\src\Model\MyParcelRequest::setRequestParameters() must be of the type string, null given, called in /var/www/website/html/vendor/myparcelnl/sdk/src/Helper/MyParcelCollection.php on line 360. Statistics: {"sum":0,"count":1,"realmem":0,"emalloc":0,"realmem_start":130547712,"emalloc_start":129164792} [] []

**Comment by RichardPerdaan** [comment]
Hi @Kroellie,
Do you also experience this problem with version [4.1.7](https://github.com/myparcelnl/magento/releases/tag/4.1.7) of the MyParcel plugin?
