### ISSUE TITLE
PostNL locatie not saved

### ISSUE THREAD

**Issue by bamboekeizer** [myparcelnl/magento#581]
**Describe the bug**
The selected PostNL location is not saved and hence not passed when creating a new shipment

**To Reproduce**
1. Create an order with a PostNL location
2. View the order
3. You see PostNL location as delivery option, but the address is not displayed
4. Create a shipment
5. Go to the myparcel backend and view the created shipment

**Expected behavior**
The magento backend should show the selected PostNL location address
The myparcel backend should have a label entry with the PostNL location

**Screenshots**
![image](https://user-images.githubusercontent.com/28304222/124594953-afa53a80-de60-11eb-9ad3-d1c8c1ef4114.png)

 - MyParcel Plugin version 4.1.7
 - MyParcel SDK version v5.2.10

**Additional context**
I retrieved orders in SQL before and after this version. You see the difference in the shipping_method and shipping_description fields. 
Actually, the last time I have seen delivery_options filled and PostNL location working properly was in 2019-09-13. I hoped one day it would be resolved, but because it does not work, I raised this ticket:
{"date":"2019-09-14","time":[{"start":"16:00:00","type":4,"price":{"currency":"EUR","amount":0}},{"start":"08:30:00","type":5,"price":{"currency":"EUR","amount":145}}],"location":"Bruna Noordwijkerhout","street":"Havenstraat","number":"34","postal_code":"2211EH","city":"Noordwijkerhout","cc":"NL","start_time":"16:00:00","price":0,"price_comment":"retail","comment":"Dit is een Business Point. Post en pakketten die u op werkdagen vóór de lichtingstijd afgeeft, bezorgen we binnen Nederland de volgende dag. Op zaterdag worden alléén pakketten die u afgeeft voor 15:00 uur maandag bezorgd.","phone_number":"0252-344349","opening_hours":{"monday":["09:00-18:00"],"tuesday":["09:00-18:00"],"wednesday":["09:00-18:00"],"thursday":["09:00-18:00"],"friday":["09:00-20:00"],"saturday":["09:00-17:00"],"sunday":[]},"distance":"426","latitude":"52.2618806929311","longitude":"4.49431575310721","location_code":"163427","retail_network_id":"PNPNL-01","holiday":[]}

**Comment by RichardPerdaan** [comment]
Hi @bamboekeizer,

I noticed that this problem occurs when using the mageplaza onestep checkout.
Do you have this problem with the standard Magento checkout?

**Comment by bamboekeizer** [comment]
I disabled onestepcheckout, flushed config/page caches. Created a new order with the standard checkout, but the same issue occurs.

**Comment by RichardPerdaan** [comment]
Solved in #583
