### ISSUE TITLE
Error when trying to print shipping labels

### ISSUE THREAD

**Issue by koveseb** [myparcelnl/magento#602]
After updating from Magento 2.2.11 to Magento 2.4.2 and updating MyParcel to the latest version I get the following error when trying to print a label.

Error: Call to a member function getConsignmentId() on null in /var/www/vhosts/salinto.nl/httpdocs/vendor/myparcelnl/magento/Model/Sales/MagentoShipmentCollection.php:154 Stack trace: #0 /var/www/vhosts/salinto.nl/httpdocs/vendor/myparcelnl/magento/Controller/Adminhtml/Shipment/CreateAndPrintMyParcelTrack.php(104): MyParcelNL\Magento\Model\Sales\MagentoShipmentCollection->createMyParcelConcepts() #1 /var/www/vhosts/salinto.nl/httpdocs/vendor/myparcelnl/magento/Controller/Adminhtml/Shipment/CreateAndPrintMyParcelTrack.php(60): MyParcelNL\Magento\Controller\Adminhtml\Shipment\CreateAndPrintMyParcelTrack->massAction() #2 /var/www/vhosts/salinto.nl/httpdocs/vendor/magento/framework/Interception/Interceptor.php(58): MyParcelNL\Magento\Controller\Adminhtml\Shipment\CreateAndPrintMyParcelTrack->execute() #3 /var/www/vhosts/salinto.nl/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): MyParcelNL\Magento\Controller\Adminhtml\Shipment\CreateAndPrintMyParcelTrack\Interceptor->___callParent() #4 /var/www/vhosts/salinto.nl/httpdocs/vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php(51): MyParcelNL\Magento\Controller\Adminhtml\Shipment\CreateAndPrintMyParcelTrack\Interceptor->Magento\Framework\Interception\{closure}() #5 /var/www/vhosts/salinto.nl/httpdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute() #6 /var/www/vhosts/salinto.nl/httpdocs/vendor/magento/framework/Interception/Interceptor.php(153): MyParcelNL\Magento\Controller\Adminhtml\Shipment\CreateAndPrintMyParcelTrack\Interceptor->Magento\Framework\Interception\{closure}() #7 /var/www/vhosts/salinto.nl/httpdocs/generated/code/MyParcelNL/Magento/Controller/Adminhtml/Shipment/CreateAndPrintMyParcelTrack/Interceptor.php(23): MyParcelNL\Magento\Controller\Adminhtml\Shipment\CreateAndPrintMyParcelTrack\Interceptor->___callPlugins() #8 /var/www/vhosts/salinto.nl/httpdocs/vendor/magento/framework/App/Action/Action.php(111): MyParcelNL\Magento\Controller\Adminhtml\Shipment\CreateAndPrintMyParcelTrack\Interceptor->execute() #9 /var/www/vhosts/salinto.nl/httpdocs/generated/code/MyParcelNL/Magento/Controller/Adminhtml/Shipment/CreateAndPrintMyParcelTrack/Interceptor.php(32): Magento\Framework\App\Action\Action->dispatch() #10 /var/www/vhosts/salinto.nl/httpdocs/vendor/magento/framework/App/FrontController.php(186): MyParcelNL\Magento\Controller\Adminhtml\Shipment\CreateAndPrintMyParcelTrack\Interceptor->dispatch() #11 /var/www/vhosts/salinto.nl/httpdocs/vendor/magento/framework/App/FrontController.php(118): Magento\Framework\App\FrontController->processRequest() #12 /var/www/vhosts/salinto.nl/httpdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch() #13 /var/www/vhosts/salinto.nl/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent() #14 /var/www/vhosts/salinto.nl/httpdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() #15 /var/www/vhosts/salinto.nl/httpdocs/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins() #16 /var/www/vhosts/salinto.nl/httpdocs/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch() #17 /var/www/vhosts/salinto.nl/httpdocs/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch() #18 /var/www/vhosts/salinto.nl/httpdocs/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch() #19 /var/www/vhosts/salinto.nl/httpdocs/pub/index.php(29): Magento\Framework\App\Bootstrap->run() #20 {main}

1. Go to Magento Admin > Sales > Orders 
2. Open an order
3. Click Shipments
4. Open the shipment and click Print Labels

![image](https://user-images.githubusercontent.com/32958840/136050805-2d7db67c-8619-48aa-85a5-412fb9411a72.png)
![image](https://user-images.githubusercontent.com/32958840/136050955-72296cbf-d357-4c81-aad9-0eaed9306495.png)

If on the shipment page I click Print I see the following.
![image](https://user-images.githubusercontent.com/32958840/136051113-eae06d16-5011-4e70-897d-517723bdf6ca.png)

The shipping status does change to Concept but I can't get any further than that.
![image](https://user-images.githubusercontent.com/32958840/136051334-4c85ba1d-00b2-455a-93c4-ba25d036f067.png)

When trying to print shipping labels for orders that already have a track and trace code I see the following error.
![image](https://user-images.githubusercontent.com/32958840/136051602-ffb255a5-58f2-4618-84c9-253edfbd04c9.png)

When printng labels in batch I get forwarded to the following page.
![image](https://user-images.githubusercontent.com/32958840/136055343-71853cd2-6f25-4ffc-ba84-81c675736082.png)

Any advise is appreciated.

**Comment by sebus208** [comment]
Thanks for your reaction. I don't think the issue was ever fully resolved. I also no longer work on this project. 

I do remember we solved some issues by disabling the One Step Checkout module from Amasty.
