### ISSUE TITLE
As a client I do not want to export the default shipping options which I uncheck

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/magento#603]
**Describe the bug**
As a client I do not want to export the default shipping options which I uncheck.

**To Reproduce**
[https://monosnap.com/file/V6zETx71DJuDmgKT7Hr0GhLRmxOEsn](https://monosnap.com/file/V6zETx71DJuDmgKT7Hr0GhLRmxOEsn
)

**Expected behavior**
The shipping option should not be exported.

**Comment by RichardPerdaan** [comment]
Fixed in [4.3.0-alpha.1 ](https://github.com/myparcelnl/magento/releases/tag/4.3.0-alpha.1)
