### ISSUE TITLE
As a customer I want to be able to delay a shipment

### ISSUE THREAD

**Issue by Kroellie** [myparcelnl/magento#613]
**Describe the bug**
These holidays the same story again: higher prices, and delays nonetheless. We figured out that handing over parcels to PostNL on Mondays, almost ALL shipments are delayed (heavily) with a lot of complaints thereafter. So: we don't send out on Mondays anymore. Simple solution. However: upon creating labels on Tuesday, the issue appears that there is a 'set' delivery date on the Dutch/Belgium parcels. The system refuses to create a label with the error message: "delivery_date is too early". There is no other solution than to change the database values, or cancel the order.

**Steps to reproduce the behavior:**
Set "number of days" to 1, as it is the default setting for us.
Create an order with for example a pickup point.
Wait 1 day, having it surpass the intended shipment date.
Create a label.
Witness the error.

**Comment by Kroellie** [comment]
#615 related?

**Comment by RichardPerdaan** [comment]
Hi @Kroellie ,
Thank you for posting your issue. 
On this moment I am working on the solution. 
I expect to do the final tests tomorrow and then I can share the solution with you.

I will let you know about the solution tomorrow.

**Comment by Kroellie** [comment]
Looks good to me!

**Comment by RichardPerdaan** [comment]
This issue is solved on 17 feb 2022 in version: [4.3.0-alpha.1](https://github.com/myparcelnl/magento/releases/tag/4.3.0-alpha.1)
