### ISSUE TITLE
As a client I want to automate the insurance with bigger amounts

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/magento#623]
**Is your feature request related to a problem? Please describe.**
Currently I have to manually add an insurance higher than €500,-. I want to be able to automate these higher amounts too.

**Describe the solution you'd like**
Add all the insurance amounts to the settings of the plugin so I can automate this option

**Comment by Ambertvu** [comment]
Wow! I was just looking for this as well, would be great if you could integrate this 👍

**Comment by KasperVeenstra** [comment]
Graag voor Magento 2 😇

**Comment by KasperVeenstra** [comment]
A checkbox to automate every step of €500,- will be sufficient, too.

**Comment by Chris707** [comment]
+1 
for 
Client
123655
