### ISSUE TITLE
Frontend checkout aan / uit schakelbaar maken

### ISSUE THREAD

**Issue by Kroellie** [myparcelnl/magento#63]

**Comment by reindert-vetter** [comment]
Je kan onder basis instellingen alle verzendmethodes uitzetten:
![image](https://user-images.githubusercontent.com/16726304/28974002-3725fdd6-7935-11e7-9702-924c5e050dc1.png)

Als dit toch niet werkt zoals gewenst, moet je het aangeven

**Comment by Kroellie** [comment]
Ik dacht dat ook, maar het is niet mogelijk om niks te selecteren als je eenmaal iets hebt geselecteerd.

**Comment by reindert-vetter** [comment]
Je kan ctrl (windows) of cmd (mac) intoetsen terwijl je klikt op een item, om het te deselecteren. Maar ik geeft toe, dit is niet handig en moet aangepast worden.

**Comment by RichardPerdaan** [comment]
This feature is added in version [3.1.1 ](https://github.com/myparcelnl/magento/releases/tag/3.1.1)of the MyParcel Magento 2 plugin
