### ISSUE TITLE
Fatal Error: Class Magento\InventoryApi\Api\SourceItemRepositoryInterface does not exist

### ISSUE THREAD

**Issue by pstuifzand** [myparcelnl/magento#631]
### Plugin version

4.2.0

### Magento version

2.3.7-p2

### PHP version

7.4

### What went wrong?

When you run `setup:di:compile` without MSI installed, you get the following error.

```Fatal Error: Class Magento\InventoryApi\Api\SourceItemRepositoryInterface does not exist```

I have tracked this down to the `SourceItem` class. The constructor argument is the problem.

### Reproduction steps

1. Don't use MSI
2. Run `bin/magento setup:di:compile`
3. You see the error

### Relevant log output

```shell
bin/magento set:di:comp
Compilation was started.
Area configuration aggregation... 5/8 [=================>----------]  62% 26 secs 324.0 MiB
In ClassReader.php line 43:
                                                                               
  Class Magento\InventoryApi\Api\SourceItemRepositoryInterface does not exist  
                                                                               

In ClassReader.php line 36:
                                                                               
  Class Magento\InventoryApi\Api\SourceItemRepositoryInterface does not exist  
                                                                               

setup:di:compile
```

### Additional context

MSI is not installed.

**Comment by RichardPerdaan** [comment]
Since 4.3.0 of the MyParcel plugin, we do not longer use SourceItemRepositoryInterface. 
This problem should therefore be solved.

If this problem is still present, we can always reopen the issue.
