### ISSUE TITLE
Adresgegevens zijn niet ingevuld verdubbeld en verdwijnt niet

### ISSUE THREAD

**Issue by Jilco** [myparcelnl/magento#676]
### Plugin version

4.4.0

### Magento version

2.4.3-p2

### PHP version

7.4

### What went wrong?

Doe iets in de winkelmand en ga naar checkout. Vul een email adres in dat een account heeft en het password veld verschijnt, tevens verschijnt er nogmaals de box met "Adresgegevens zijn niet ingevuld".

Ook bij auto invullen (Chrome) verschijnen er 2 velden + het veld verzendopties.

![afrekenen](https://user-images.githubusercontent.com/23727130/165142272-b6ad3c4f-7c93-4ed0-8dcb-95281ce8c65d.jpg)

### Reproduction steps

1. Product
2. Click on add to cart
3. See checkout
4. Fill in email with account

**Comment by RichardPerdaan** [comment]
Hi @Jilco .
Thank you for posting your issue. 
Would you like to see if the problem is solved after clearing magento's cache?

**Comment by Jilco** [comment]
Hi @RichardPerdaan, after cleaning cache the problem is still there. I also cleaned my browsercache, no effect

**Comment by RichardPerdaan** [comment]
Hi @Jilco,
Thank you for trying, we would like to solve the problem together with you. 
It is not possible to reproduce this problem on our test environments.

To solve this problem, I would like to ask you to send an email to support@myparcel.nl.
Then we can see together with you, where the problem is.

**Comment by jurgenmahn** [comment]
Is there already a solution for this issue?

We are facing the same issue in Magento 2.4.3 in the Mageplaza onestepcheckout with the myparcel plugin version 4.3.0

**Comment by AlexNauta** [comment]
Having the same issue here...

**Comment by RichardPerdaan** [comment]
This issue has been resolved since [4.5.0](https://github.com/myparcelnl/magento/releases/tag/v4.5.0)
