### ISSUE TITLE
Postcode veld verliest focus tijdens refresh shipping options

### ISSUE THREAD

**Issue by Kroellie** [myparcelnl/magento#68]
Bij het laden van de one step checkout module, en het initieel vullen van een adres met behulp van de google locator, laadt de MyParcel extensie de bezorgopties. Als vervolgens toch het adres aangepast wordt naar een ander adres (klant bedenkt zich, of corrigeert een fout) dan blijft MyParcel op het eerste adres staan. Geen mogelijkheid tot handmatige verversing.

**Comment by reindert-vetter** [comment]
Het gaat bij mij wel goed in de normale checkout en in de One Step Checkout van MagePlaza. In welke browser zag je dat dit verkeerd gaat? Misschien wil je een filmpje maken (bijvoorbeeld met monosnap.com) en een linkje van het filmpje hier plaatsen?

**Comment by Kroellie** [comment]
Ik gebruik Safari / OSX Sierra.

Hierbij een schermopname: https://monosnap.com/file/qvaD86WFYi1qeVikNU4mdzwz1loWts

Ik tik mijn adres 2132KH, Hoofddorp achter elkaar in.

Op Chrome werkt het wel naar behoren trouwens.

Gr.
Rene

**Comment by Kroellie** [comment]
Blijkbaar heeft het te maken met de auto-fill instellingen van safari. Als ik die uitschakel heb ik het probleem niet. Daarom sluiten we de call maar, bedankt heren!
