### ISSUE TITLE
Add PHP 8.1 compatibility

### ISSUE THREAD

**Issue by peterjaap** [myparcelnl/magento#687]
### Plugin/theme name

PHP

### Pricing

Free

### What problem does this feature solve?

So we can upgrade to Magento 2.4.4

### What should the solution look like?

PHP 8.1 compatibility

### Relevant log output

Here's the output of the PHPCompatibility code sniffer for PHP 8.0 and 8.1:

```shell
vendor/bin/phpcs -p vendor/myparcelnl/magento --standard=vendor/phpcompatibility/php-compatibility/PHPCompatibility --extensions=php,phtml --runtime-set testVersion 8.0
............................................................ 60 / 95 (63%)
...................................                          95 / 95 (100%)


Time: 2.65 secs; Memory: 14MB

vendor/bin/phpcs -p vendor/myparcelnl/magento --standard=vendor/phpcompatibility/php-compatibility/PHPCompatibility --extensions=php,phtml --runtime-set testVersion 8.1
............................................................ 60 / 95 (63%)
...................................                          95 / 95 (100%)


Time: 2.65 secs; Memory: 14MB

```

So looks like updating the constraints and we're good to go! PR here; https://github.com/myparcelnl/magento/pull/688

**Comment by RichardPerdaan** [comment]
Fixed in [v4.6.0](https://github.com/myparcelnl/magento/releases/tag/v4.6.0)
