### ISSUE TITLE
Makkelijk retourlabels aanmaken in de backend

### ISSUE THREAD

**Issue by reindert-vetter** [myparcelnl/magento#69]

**Comment by GuidoHub** [comment]
Is dit alleen backend gerelateerd of kan de klant ook zelf een retour label aanmaken? Anders open ik graag een nieuw verzoek.

**Comment by reindert-vetter** [comment]
Inderdaad, dit is alleen voor de backend. Ik heb een nieuwe issue aangemaakt: #74

**Comment by reindert-vetter** [comment]
Done:
https://github.com/myparcelnl/magento/releases/tag/2.2.0-beta.3
