### ISSUE TITLE
Upgrade not triggering in 4.6

### ISSUE THREAD

**Issue by Ambertvu** [myparcelnl/magento#704]
### Plugin version

4.6.0

### Magento version

2.4.2

### PHP version

7.4

### What went wrong?

Upgraded from 4.2.x to 4.6.0

In the backoffice it still shows:
_"The version 4.4.0 of the extension is installed on your webshop. Currently version [v4.6.0](https://github.com/myparcelnl/magento/releases/latest) is the latest stable version. If you experience an issue, we recommend that you install the latest stable version."_

However in /vendor/myparcel/magento/composer.json it says 4.6.0

Tried reinstalling, clearing cache, di/compile, upgrade..all of it. Is this a bug or is something really wrong ?

### Reproduction steps

Not exactly sure how to reproduce

**Comment by joerivanveen** [comment]
We have found the issue. You have version 4.6.0 installed, but our update-script failed on the xml file that updates the version you are shown. We will fix this in a future release.

**Comment by RichardPerdaan** [comment]
Solved in 4.7.0 of the MyParcel plugin
