### ISSUE TITLE
Set Base color and Color for selected items on Store View

### ISSUE THREAD

**Issue by GuidoHub** [myparcelnl/magento#72]
Zou graag verschillende kleuren kunnen zetten per store view. Ik maak namelijk gebruik van Multi store met dezelfde template maar verschillende kleuren per website.

**Comment by reindert-vetter** [comment]
Bedankt voor jouw aanvraag. Dit is opgelost in vanaf versie [2.2.0-beta.3](https://github.com/myparcelnl/magento/releases/tag/2.2.0-beta.3)
