### ISSUE TITLE
Order saving error: Deprecated Functionality: explode()

### ISSUE THREAD

**Issue by onepack** [myparcelnl/magento#726]
### Plugin version

4.7.0

### Magento version

2.4.4-p2

### PHP version

8.1

### What went wrong?

Creating and saving a new order from the backend

### Reproduction steps

1. Navigate to backend
2. Click on create order
3. Save order and get the error

### Relevant log output

```shell
Order saving error: Deprecated Functionality: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /home/admin/domains/domain.com/public_html/vendor/myparcelnl/magento/Model/Quote/SaveOrderBeforeSalesModelQuoteObserver.php on line 57
```

**Comment by EdieLemoine** [comment]
Duplicates #724
