### ISSUE TITLE
Delivery options and pickup locations API calls fail for some postal codes

### ISSUE THREAD

**Issue by LauHypershop** [myparcelnl/magento#758]
### Plugin version

4.1.7

### Magento version

2.4.2-p2

### PHP version

7.4

### What went wrong?

Getting delivery options or pickup locations fails for some postal codes. These postal codes are valid according to the PostNL address checker, but myParcel returns a 500 error.

### Reproduction steps

# Delivery Options
Make a request to:

https://api.myparcel.nl/delivery_options?cc=NL&number=12&postal_code=4621BD
https://api.myparcel.nl/delivery_options?cc=NL&number=120&postal_code=1231ND

Result:
```
{"data":{"delivery":[],"pickup":[],"message":"No results"},"errors":[{"status":500,"code":0,"title":"PostNL API call failed","message":"PostNL API call failed"}]}
```
Validate this postal code with https://www.postnl.nl/adres-zoeken/ and it's valid.

Compare to:

https:/api.myparcel.nl//delivery_options?cc=NL&number=29&postal_code=2289DA

Same structure, but this one returns lots of options.

# Pickup Locations
Try:
https://api.myparcel.nl/pickup_locations?cc=NL&number=12&postal_code=4621BD
https://api.myparcel.nl/pickup_locations?cc=NL&number=120&postal_code=1231ND
Receive:
```
{"message":"Internal Server Error (request_id: 1677496071.887763fc8f07d8b74)","request_id":"1677496071.887763fc8f07d8b74","errors":[{"code":0}]}
```

Compare to:
https://api.myparcel.nl/pickup_locations?cc=NL&number=29&postal_code=2289DA

Which returns a page full of options.

### Additional context

Not working:
```
# v1
curl https://api.myparcel.nl/delivery_options?cc=NL&number=12&postal_code=4621BD

# v2
curl --header "Accept: application/json;version=2.0" https://api.myparcel.nl/delivery_options?cc=NL&number=12&postal_code=4621BD&platform=1&carrier=postnl
```

Working:
```
# v1
curl https://api.myparcel.nl/delivery_options?cc=NL&number=29&postal_code=2289DA

# v2
curl --header "Accept: application/json;version=2.0" https://api.myparcel.nl/delivery_options?cc=NL&number=29&postal_code=2289DA&platform=1&carrier=postnl
```

**Comment by EdieLemoine** [comment]
Hi @LauHypershop,

Thanks for reporting this. 

We've looked into it, but unfortunately it's not something on our side. It's an issue in PostNL's own TimeFrameWebService, which we are using in our API to get delivery and pickup options.

**Request**

```shell
curl \
	--header 'apikey: ***' \
	--location 'https://api-sandbox.postnl.nl/shipment/v2_1/calculate/timeframes?StartDate=28-02-2023&EndDate=03-03-2023&CountryCode=NL&PostalCode=4621BD&HouseNumber=12&Street=Waterleliestraat&City=Bergen%20op%20Zoom'
```

**Response**

```json
{
    "Date": "2023-02-28T15:40:09+00:00",
    "ExternalRef": "63d585b2-b210-3d57-93b2-6ca9b64facc1",
    "Error": {
        "ErrorCode": "3010",
        "ErrorMessage": "PostalCode 4621BD could not be found"
    },
    "RequestId": "2b228f6b-7dae-4222-bdb4-d36d691486ec"
}
```

So, I'll close this issue as there is nothing we can do right now. If you have any more questions regarding this you can contact us directly at support@myparcel.nl.
