### ISSUE TITLE
Verzend opties exclusief/inclusief BTW

### ISSUE THREAD

**Issue by RichardPerdaan** [myparcelnl/magento#77]
Als het tarief ingesteld wordt exclusief btw, voor PostNL pakket in Nederland wordt dat tarief in de backend getoond inclusief BTW.

Afhalen op een postkantoor worden de tarieven getoond exclusief BTW

@00216603

**Comment by RichardPerdaan** [comment]
@ 00220194

**Comment by reindert-vetter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Verzend opties exclusief/inclusief BTW (#77)](https://trello.com/c/rfh3O2Dn/17-verzend-opties-exclusief-inclusief-btw-77)

**Comment by RichardPerdaan** [comment]
Dit Probleem is opgelost door de meerdere releases die plaats hebben gevonden.
