### ISSUE TITLE
Checkout onderdelen vertalen

### ISSUE THREAD

**Issue by RichardPerdaan** [myparcelnl/magento#78]
Vertalen van tekst in tekst zoals "bezorgopties" en "Ophalen bij een PostNl locatie"

@00216603

**Comment by reindert-vetter** [comment]
Het is al mogelijk om ```Ophalen bij een PostNl locatie``` te vertalen

**Comment by RichardPerdaan** [comment]
Dit probleem is opgelost sinds versie 2.4.0 van de myparcel magento 2 plugin
