### ISSUE TITLE
Verzendopties worden getoond in verzendkosten berekening

### ISSUE THREAD

**Issue by Chris707** [myparcelnl/magento#82]
![m2_ch](https://user-images.githubusercontent.com/25433104/30059925-760d123a-9241-11e7-8076-8f814c99e871.png)

**Comment by Chris707** [comment]
Zie Case: 218866

**Comment by reindert-vetter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Verzendopties worden getoond in verzendkosten berekening (#82)](https://trello.com/c/Yxa8OhIJ/21-verzendopties-worden-getoond-in-verzendkosten-berekening-82)

**Comment by RichardPerdaan** [comment]
Dit is een functionaliteit van Magento zelf.
Magento kijkt namelijk welke verzendmethoden er mogelijk zijn en laat ze hier dan ook zien.
Wij hebben vanuit de MyParcel plugin hier geen invloed op.
