### ISSUE TITLE
Invalid scope website when upgrading to 4.14.0

### ISSUE THREAD

**Issue by janssensjelle** [myparcelnl/magento#833]
### Plugin version

4.14.0

### Magento version

2.4.6-p4

### PHP version

8.2

### What went wrong?

Migration script causes invalid scopes

### Reproduction steps

1. Upgrade to 4.14.0 from 4.13.0
2. Start setup:upgrade

### Relevant log output

```shell
Module 'MyParcelNL_Magento':
Upgrading data..
Migrating postnl for scope default (2)
Migrating dhlforyou for scope default (2)
Migrating dhleuroplus for scope default (2)
Migrating dhlparcelconnect for scope default (2)
Migrating ups for scope default (2)
Migrating dpd for scope default (2)
Migrating postnl for scope stores (2)
Migrating dhlforyou for scope stores (2)
Migrating dhleuroplus for scope stores (2)
Migrating dhlparcelconnect for scope stores (2)
Migrating ups for scope stores (2)
Migrating dpd for scope stores (2)
Migrating postnl for scope website (0)
Enabling caches:
Current status:
layout: 1
block_html: 1
full_page: 1
Invalid scope website
```

### Additional context

It creates invalid configuration like in the screenshot
![Screenshot 2024-04-02 at 09 43 03](https://github.com/myparcelnl/magento/assets/10356515/1c5e67b5-2a79-4022-90a3-193bdf7dcbdc)

Also happens when clearing config table from all myparcel configuration.

**Comment by joerivanveen** [comment]
Good morning @janssensjelle  Can you share the contents of the config table regarding **all** paths starting with 'myparcel' so I can investigate further? You may e-mail the data or screenshot to our support email address, or paste it in this thread.

**Comment by joerivanveen** [comment]
Thank you for reporting the issue, I started working on this.
On a separate note, your entries are not at all what I was expecting, are you upgrading from a very old version, or a Belgian version? Is the screenshot from after you deleted `myparcel%` related entries?

**Comment by joerivanveen** [comment]
Can you confirm or deny whether the scope `website` (without ‘s’) exists in your conifg table, and wheter there is a row with scope `default` and scope_id `2`? If so, these are indeed illegal, and then the migration should maybe discard them rather than throw an error. The question is because I am having trouble reproducing your error at the moment.

**Comment by janssensjelle** [comment]
I had the previous version, v4.13.0 working before. 

There indeed is a scope website without 's' from a very old module. Setup:upgrade was working fine before with this in the config table.

![Screenshot 2024-04-02 at 11 10 18](https://github.com/myparcelnl/magento/assets/10356515/e6eed853-8a1a-4778-a177-b860a3cd76e1)

**Comment by joerivanveen** [comment]
Hi, thank you for working with me on this so quickly. It is correct that only since 4.14.0 the scopes are used in a migration within the myparcel plugin. I think it might be better if the migration just ignores invalid scopes instead of throwing an error, will make a pr to that effect.

**Comment by janssensjelle** [comment]
To be honest, I think this migration script should not touch any other config entries other than the ones it owns.
