### ISSUE TITLE
minified css not found

### ISSUE THREAD

**Issue by GuidoHub** [myparcelnl/magento#88]
Wanneer minify css is geactiveerd in de backend kan de module de css niet meer vinden. Hij blijft namelijk zoeken naar onderstaande file maar die is er niet meer, in de plaats daarvan is de minified versie aanwezig.

/pub/static/frontend/Smartwave/porto/nl_NL/MyParcelNL_Magento/css/checkout/options-dynamic.css

Cache, etc is geleegd.

**Comment by reindert-vetter** [comment]
Waarschijnlijk opgelost in 2.2.1-beta.2
Zou je dit willen controleren?

**Comment by GuidoHub** [comment]
Na wat fouten bij het updaten van 1.1.9 naar 2.2.1 heb ik het eindelijk aan de gang. Ik krijg nu niet meer de foutmelding.

**Comment by reindert-vetter** [comment]
Fijn om te horen! 👍 Als je nog iets tegenkomt, laat het mij dan weten.
