### ISSUE TITLE
Extra spaties in postcode leiden tot niet herkennen adres

### ISSUE THREAD

**Issue by patrick-bigbridge** [myparcelnl/magento#97]
Als een gebruiker een extra voorloop- of naloop spatie in zijn postcode invuld, wordt het adres niet herkend.

Bij het kopiëren van een postcode worden vaak extra spaties meegenomen, terwijl de gebruiker dat niet in de gaten heeft. Het trimmen van input door de extensie is dus wenselijk.

![image](https://user-images.githubusercontent.com/17122199/31120447-b1bf2d3c-a834-11e7-9249-abfb824a1fb2.png)

**Comment by GuidoHub** [comment]
Heel eerlijk, dit lijkt me niet iets dat MyParcel voor zijn rekening moet nemen. Zou de data controle eerder  laten uitvoeren door de Magento checkout of andere checkout extensie die gebruikt wordt. Ik krijg namelijk in mijn onepagecheckout netjes de melding dat de postcode niet klopt.

**Comment by patrick-bigbridge** [comment]
Dag Guido,

In dit geval klopt de postcode wel, het wordt alleen gevolgd/voorafgegaan door een spatie. Mogelijk dat onepagecheckout aangeeft dat zo'n postcode niet klopt, maar voor de gebruiker is dat natuurlijk niet duidelijk, omdat je spaties niet kunt zien. 

De myparcel extensie leest zelf het postcode-veld uit en stuurt dit naar de server. Zowel de javascript code als de server-code van myParcel kan eenvoudigweg de overtollige spaties weghalen. Daarmee wordt de extensie weer een stukje beter.

Ons alternatief is dat we hiervoor zelf een fix schrijven, maar we vinden het beter als het bij de bron wordt opgelost.

**Comment by RichardPerdaan** [comment]
Beste Patrick,

Dank je wel voor het melden van jouw issue. Ik ben hier mee aan de slag gegaan en heb voor jou een oplossing. Deze oplossing heb ik in de volgende branche toegepast: fix-postcode_white_space.

Via de volgende link kan je zien wat ik heb aangepast: https://github.com/myparcelnl/magento/commit/fa7b2604be095bfb9943f41d51fe1849413205ed

Zou je dit in jouw code kunnen toevoegen?

@GuidoHub 
Wij moeten de postcode en huisnummer naar PostNL sturen, om de juiste opties binnen te halen. Als PostNL aangeeft dat de postcode niet klopt dan kunnen we niet anders dan het bericht tonen dat de postcode in combinatie met het huisnummer niet correct is.

**Comment by GuidoHub** [comment]
@RichardPerdaan Maar de invoer blijft alsnog foutief en wordt ook foutief opgeslagen als je alleen de data manipuleert die naar PostNL wordt gestuurd. Geeft dit naderhand geen problemen met het aanmaken van labels?

**Comment by RichardPerdaan** [comment]
@GuidoHub 
Wat nu gedaan wordt is dat de gegevens gemanipuleerd word, dit is om de opties goed te tonen. Echter worden de gegevens niet opgeslagen. Doordat het niet wordt opgeslagen heeft dit ook geen effect met het aanmaken van de labels.

**Comment by patrick-bigbridge** [comment]
Bedankt Richard, ik kan hier mee verder!

**Comment by GuidoHub** [comment]
@patrick-bigbridge 
Heb jij toevallig de postcode controle van magento uitgezet in `<root>vendor/magento/module-directory/etc/zip_code.xml`

@RichardPerdaan 
Ik snap de keuze om de plugin verder te laten gaan maar standaard zou deze invoer niet geldig zijn. In mijn situatie is het nu heel vreemd dat ik aangeef dat de postcode onjuist is maar jullie extensie toch een resultaat geeft. Is het mogelijk om dit optioneel te maken?

**Comment by patrick-bigbridge** [comment]
@GuidoHub Nee, dat heb ik niet. 
Ik heb helaas ook geen tijd om dit verder te bespreken. Ik heb nog een boel andere dingen te doen. :)

**Comment by RichardPerdaan** [comment]
De oplossing is hier te vinden: fa7b260
