### ISSUE TITLE
Critical error getting options.min.css

### ISSUE THREAD

**Issue by GuidoHub** [myparcelnl/magento#99]
Ik krijg de onderstaande error ontzettend vaak in mijn exception.log. De file zelf is wel aanwezig op de locatie die wordt aangegeven 'frontend/Smartwave/porto/nl_NL/MyParcelNL_Magento/css/checkout/options.min.css'

[2017-10-04 09:40:24] main.CRITICAL: Magento\Framework\View\Asset\File\NotFoundException: Unable to get content for 'frontend/Smartwave/porto/nl_NL/MyParcelNL_Magento/css/checkout/options.min.css' in /xxx/xxx/xxx/vendor/magento/framework/View/Asset/File.php:165
Stack trace:
#0 /xxx/xxx/xxx/vendor/magento/framework/View/Asset/MergeStrategy/Direct.php(73): Magento\Framework\View\Asset\File->getContent()
#1 /xxx/xxx/xxx/vendor/magento/framework/View/Asset/MergeStrategy/Direct.php(52): Magento\Framework\View\Asset\MergeStrategy\Direct->composeMergedContent(Array, Object(Magento\Framework\View\Asset\File))
#2 /xxx/xxx/xxx/vendor/magento/framework/View/Asset/MergeStrategy/FileExists.php(44): Magento\Framework\View\Asset\MergeStrategy\Direct->merge(Array, Object(Magento\Framework\View\Asset\File))
#3 /xxx/xxx/xxx/vendor/magento/framework/View/Asset/Merged.php(97): Magento\Framework\View\Asset\MergeStrategy\FileExists->merge(Array, Object(Magento\Framework\View\Asset\File))
#4 /xxx/xxx/xxx/vendor/magento/framework/View/Asset/Merged.php(157): Magento\Framework\View\Asset\Merged->initialize()
#5 /xxx/xxx/xxx/vendor/magento/framework/View/Page/Config/Renderer.php(358): Magento\Framework\View\Asset\Merged->rewind()
#6 /xxx/xxx/xxx/vendor/magento/framework/View/Page/Config/Renderer.php(251): Magento\Framework\View\Page\Config\Renderer->renderAssetHtml('<link  rel="sty...', Object(Magento\Framework\View\Asset\Merged))
#7 /xxx/xxx/xxx/vendor/magento/framework/View/Page/Config/Renderer.php(226): Magento\Framework\View\Page\Config\Renderer->renderAssetGroup(Object(Magento\Framework\View\Asset\PropertyGroup))
#8 /xxx/xxx/xxx/vendor/magento/framework/View/Page/Config/Renderer.php(99): Magento\Framework\View\Page\Config\Renderer->renderAssets(Array)
#9 /xxx/xxx/xxx/vendor/magento/framework/View/Result/Page.php(235): Magento\Framework\View\Page\Config\Renderer->renderHeadContent()
#10 /xxx/xxx/xxx/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#11 /xxx/xxx/xxx/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#12 /xxx/xxx/xxx/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#13 /xxx/xxx/xxx/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#14 /xxx/xxx/xxx/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#15 /xxx/xxx/xxx/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#16 /xxx/xxx/xxx/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#17 /xxx/xxx/xxx/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#18 /xxx/xxx/xxx/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#19 /xxx/xxx/xxx/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(26): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#20 /xxx/xxx/xxx/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#21 /xxx/xxx/xxx/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#22 /xxx/xxx/xxx/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#23 {main} [] []

**Comment by reindert-vetter** [comment]
@00231366

**Comment by GuidoHub** [comment]
Is er ondertussen een oplossing of is het gerelateerd aan mijn omgeving? Mijn exception.log loopt namelijk helemaal vol.

**Comment by GuidoHub** [comment]
/public_html/vendor/myparcelnl/magento/view/frontend/layout/default_head_blocks.xml

regel 4 aangepast naar het onderstaande:

<css src="MyParcelNL_Magento::css/checkout/options.css" />

Daarna opnieuw opnieuw content:deploy uitgevoerd, cache geleegd en de melding was verdwenen. In mijn geval was deze vervanging door een soort gelijke melding van een andere extensie, na dezelfde fix te hebben doorgevoerd was ook deze verdwenen.

**Comment by reindert-vetter** [comment]
Bedankt voor het uitzoeken. We zullen dit binnenkort verwerken in een nieuwe versie.
